//! Bulk operations for Advertisement entities
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateAdvertisementDto;
use crate::application::service::AdvertisementService;
use crate::domain::entity::Advertisement;

/// Bulk operation handler for Advertisement entities.
///
/// Wraps `AdvertisementService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type AdvertisementBulkService = GenericBulkService<Advertisement, CreateAdvertisementDto, AdvertisementService>;

// <<< CUSTOM
// END CUSTOM
