//! Bulk operations for LoyaltyPointEntry entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateLoyaltyPointEntryDto;
use crate::application::service::LoyaltyPointEntryService;
use crate::domain::entity::LoyaltyPointEntry;

/// Bulk operation handler for LoyaltyPointEntry entities.
///
/// Wraps `LoyaltyPointEntryService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type LoyaltyPointEntryBulkService = GenericBulkService<LoyaltyPointEntry, CreateLoyaltyPointEntryDto, LoyaltyPointEntryService>;

// <<< CUSTOM
// END CUSTOM
