//! Bulk operations
//!
//! Generated by backbone-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::*;

pub mod ad_performance_bulk;
pub mod advertisement_bulk;
pub mod provider_promo_bulk;
pub mod promo_campaign_bulk;

pub use ad_performance_bulk::AdPerformanceBulkService;
pub use advertisement_bulk::AdvertisementBulkService;
pub use provider_promo_bulk::ProviderPromoBulkService;
pub use promo_campaign_bulk::PromoCampaignBulkService;

// <<< CUSTOM
// END CUSTOM
