//! Bulk operations for PromoBundle entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreatePromoBundleDto;
use crate::application::service::PromoBundleService;
use crate::domain::entity::PromoBundle;

/// Bulk operation handler for PromoBundle entities.
///
/// Wraps `PromoBundleService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type PromoBundleBulkService = GenericBulkService<PromoBundle, CreatePromoBundleDto, PromoBundleService>;

// <<< CUSTOM
// END CUSTOM
