//! CouponCode DTOs (Data Transfer Objects)
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::CouponCode;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new CouponCode
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateCouponCodeDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub code: String,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "pricing_rule_id")]
    pub pricing_rule_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 280)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "max_use")]
    pub max_use: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "used_count")]
    pub used_count: i32,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "valid_from")]
    pub valid_from: DateTime<Utc>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "valid_upto")]
    pub valid_upto: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_active")]
    pub is_active: bool,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a CouponCode
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateCouponCodeDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub code: String,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "pricing_rule_id")]
    pub pricing_rule_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 280)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "max_use")]
    pub max_use: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "used_count")]
    pub used_count: i32,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "valid_from")]
    pub valid_from: DateTime<Utc>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "valid_upto")]
    pub valid_upto: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_active")]
    pub is_active: bool,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a CouponCode
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchCouponCodeDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "pricing_rule_id")]
    pub pricing_rule_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 280)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "max_use")]
    pub max_use: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "used_count")]
    pub used_count: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "valid_from")]
    pub valid_from: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "valid_upto")]
    pub valid_upto: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "is_active")]
    pub is_active: Option<bool>,
}

impl PatchCouponCodeDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.code.is_some() || self.pricing_rule_id.is_some() || self.description.is_some() || self.max_use.is_some() || self.used_count.is_some() || self.valid_from.is_some() || self.valid_upto.is_some() || self.is_active.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for CouponCode entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct CouponCodeResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub code: String,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub pricing_rule_id: Uuid,
    pub description: Option<String>,
    pub max_use: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub used_count: i32,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub valid_from: DateTime<Utc>,
    pub valid_upto: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_active: bool,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for CouponCode entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct CouponCodeListResponseDto {
    /// List of items
    pub items: Vec<CouponCodeResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl CouponCodeListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<CouponCodeResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct CouponCodeSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub code: String,
    pub pricing_rule_id: Uuid,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<CouponCode> for CouponCodeResponseDto {
    fn from(entity: CouponCode) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            code: entity.code,
            pricing_rule_id: entity.pricing_rule_id,
            description: entity.description,
            max_use: entity.max_use,
            used_count: entity.used_count,
            valid_from: entity.valid_from,
            valid_upto: entity.valid_upto,
            is_active: entity.is_active,
            metadata: entity.metadata,
        }
    }
}

impl From<CouponCode> for CouponCodeSummaryDto {
    fn from(entity: CouponCode) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            code: entity.code,
            pricing_rule_id: entity.pricing_rule_id,
            created_at,
        }
    }
}

impl From<CreateCouponCodeDto> for CouponCode {
    fn from(dto: CreateCouponCodeDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            code: dto.code,
            pricing_rule_id: dto.pricing_rule_id,
            description: dto.description,
            max_use: dto.max_use,
            used_count: dto.used_count,
            valid_from: dto.valid_from,
            valid_upto: dto.valid_upto,
            is_active: dto.is_active,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&CouponCode> for CouponCodeResponseDto {
    fn from(entity: &CouponCode) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            code: entity.code.clone(),
            pricing_rule_id: entity.pricing_rule_id.clone(),
            description: entity.description.clone(),
            max_use: entity.max_use.clone(),
            used_count: entity.used_count.clone(),
            valid_from: entity.valid_from.clone(),
            valid_upto: entity.valid_upto.clone(),
            is_active: entity.is_active.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateCouponCodeDto> for CouponCode {
    fn from_create_dto(dto: CreateCouponCodeDto) -> backbone_core::ServiceResult<Self> {
        Ok(CouponCode::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateCouponCodeDto> for CouponCode {
    fn apply_update(mut self, dto: UpdateCouponCodeDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.code = dto.code;
        self.pricing_rule_id = dto.pricing_rule_id;
        self.description = dto.description;
        self.max_use = dto.max_use;
        self.used_count = dto.used_count;
        self.valid_from = dto.valid_from;
        self.valid_upto = dto.valid_upto;
        self.is_active = dto.is_active;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to CouponCode here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
