//! LoyaltyPointEntry DTOs (Data Transfer Objects)
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::LoyaltyPointEntry;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::LoyaltyEntryType;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new LoyaltyPointEntry
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateLoyaltyPointEntryDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "loyalty_program_id")]
    pub loyalty_program_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "customer_id")]
    pub customer_id: Uuid,
    #[serde(alias = "entry_type")]
    pub entry_type: LoyaltyEntryType,
    pub points: Decimal,
    #[serde(alias = "purchase_amount")]
    pub purchase_amount: Decimal,
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "source_type")]
    pub source_type: String,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "source_id")]
    pub source_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "posting_date")]
    pub posting_date: DateTime<Utc>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "expiry_date")]
    pub expiry_date: Option<DateTime<Utc>>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a LoyaltyPointEntry
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateLoyaltyPointEntryDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "loyalty_program_id")]
    pub loyalty_program_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "customer_id")]
    pub customer_id: Uuid,
    #[serde(alias = "entry_type")]
    pub entry_type: LoyaltyEntryType,
    pub points: Decimal,
    #[serde(alias = "purchase_amount")]
    pub purchase_amount: Decimal,
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "source_type")]
    pub source_type: String,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "source_id")]
    pub source_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "posting_date")]
    pub posting_date: DateTime<Utc>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "expiry_date")]
    pub expiry_date: Option<DateTime<Utc>>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a LoyaltyPointEntry
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchLoyaltyPointEntryDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "loyalty_program_id")]
    pub loyalty_program_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "customer_id")]
    pub customer_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "entry_type")]
    pub entry_type: Option<LoyaltyEntryType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub points: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "purchase_amount")]
    pub purchase_amount: Option<Decimal>,
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "source_type")]
    pub source_type: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "source_id")]
    pub source_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "posting_date")]
    pub posting_date: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "expiry_date")]
    pub expiry_date: Option<DateTime<Utc>>,
}

impl PatchLoyaltyPointEntryDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.loyalty_program_id.is_some() || self.customer_id.is_some() || self.entry_type.is_some() || self.points.is_some() || self.purchase_amount.is_some() || self.source_type.is_some() || self.source_id.is_some() || self.posting_date.is_some() || self.expiry_date.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for LoyaltyPointEntry entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct LoyaltyPointEntryResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub loyalty_program_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub customer_id: Uuid,
    pub entry_type: LoyaltyEntryType,
    pub points: Decimal,
    pub purchase_amount: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub source_type: String,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub source_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub posting_date: DateTime<Utc>,
    pub expiry_date: Option<DateTime<Utc>>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for LoyaltyPointEntry entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct LoyaltyPointEntryListResponseDto {
    /// List of items
    pub items: Vec<LoyaltyPointEntryResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl LoyaltyPointEntryListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<LoyaltyPointEntryResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct LoyaltyPointEntrySummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub loyalty_program_id: Uuid,
    pub customer_id: Uuid,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<LoyaltyPointEntry> for LoyaltyPointEntryResponseDto {
    fn from(entity: LoyaltyPointEntry) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            loyalty_program_id: entity.loyalty_program_id,
            customer_id: entity.customer_id,
            entry_type: entity.entry_type,
            points: entity.points,
            purchase_amount: entity.purchase_amount,
            source_type: entity.source_type,
            source_id: entity.source_id,
            posting_date: entity.posting_date,
            expiry_date: entity.expiry_date,
            metadata: entity.metadata,
        }
    }
}

impl From<LoyaltyPointEntry> for LoyaltyPointEntrySummaryDto {
    fn from(entity: LoyaltyPointEntry) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            loyalty_program_id: entity.loyalty_program_id,
            customer_id: entity.customer_id,
            created_at,
        }
    }
}

impl From<CreateLoyaltyPointEntryDto> for LoyaltyPointEntry {
    fn from(dto: CreateLoyaltyPointEntryDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            loyalty_program_id: dto.loyalty_program_id,
            customer_id: dto.customer_id,
            entry_type: dto.entry_type,
            points: dto.points,
            purchase_amount: dto.purchase_amount,
            source_type: dto.source_type,
            source_id: dto.source_id,
            posting_date: dto.posting_date,
            expiry_date: dto.expiry_date,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&LoyaltyPointEntry> for LoyaltyPointEntryResponseDto {
    fn from(entity: &LoyaltyPointEntry) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            loyalty_program_id: entity.loyalty_program_id.clone(),
            customer_id: entity.customer_id.clone(),
            entry_type: entity.entry_type.clone(),
            points: entity.points.clone(),
            purchase_amount: entity.purchase_amount.clone(),
            source_type: entity.source_type.clone(),
            source_id: entity.source_id.clone(),
            posting_date: entity.posting_date.clone(),
            expiry_date: entity.expiry_date.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateLoyaltyPointEntryDto> for LoyaltyPointEntry {
    fn from_create_dto(dto: CreateLoyaltyPointEntryDto) -> backbone_core::ServiceResult<Self> {
        Ok(LoyaltyPointEntry::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateLoyaltyPointEntryDto> for LoyaltyPointEntry {
    fn apply_update(mut self, dto: UpdateLoyaltyPointEntryDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.loyalty_program_id = dto.loyalty_program_id;
        self.customer_id = dto.customer_id;
        self.entry_type = dto.entry_type;
        self.points = dto.points;
        self.purchase_amount = dto.purchase_amount;
        self.source_type = dto.source_type;
        self.source_id = dto.source_id;
        self.posting_date = dto.posting_date;
        self.expiry_date = dto.expiry_date;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to LoyaltyPointEntry here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
