//! LoyaltyProgram DTOs (Data Transfer Objects)
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::LoyaltyProgram;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::LoyaltyProgramType;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new LoyaltyProgram
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateLoyaltyProgramDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 140)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "program_name")]
    pub program_name: String,
    #[serde(alias = "program_type")]
    pub program_type: LoyaltyProgramType,
    #[serde(alias = "collection_factor")]
    pub collection_factor: Decimal,
    #[serde(alias = "conversion_factor")]
    pub conversion_factor: Decimal,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "expiry_duration_days")]
    pub expiry_duration_days: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "from_date")]
    pub from_date: DateTime<Utc>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "to_date")]
    pub to_date: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_active")]
    pub is_active: bool,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a LoyaltyProgram
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateLoyaltyProgramDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 140)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "program_name")]
    pub program_name: String,
    #[serde(alias = "program_type")]
    pub program_type: LoyaltyProgramType,
    #[serde(alias = "collection_factor")]
    pub collection_factor: Decimal,
    #[serde(alias = "conversion_factor")]
    pub conversion_factor: Decimal,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "expiry_duration_days")]
    pub expiry_duration_days: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "from_date")]
    pub from_date: DateTime<Utc>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "to_date")]
    pub to_date: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_active")]
    pub is_active: bool,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a LoyaltyProgram
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchLoyaltyProgramDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 140)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "program_name")]
    pub program_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "program_type")]
    pub program_type: Option<LoyaltyProgramType>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "collection_factor")]
    pub collection_factor: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "conversion_factor")]
    pub conversion_factor: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "expiry_duration_days")]
    pub expiry_duration_days: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "from_date")]
    pub from_date: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "to_date")]
    pub to_date: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "is_active")]
    pub is_active: Option<bool>,
}

impl PatchLoyaltyProgramDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.program_name.is_some() || self.program_type.is_some() || self.collection_factor.is_some() || self.conversion_factor.is_some() || self.expiry_duration_days.is_some() || self.from_date.is_some() || self.to_date.is_some() || self.is_active.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for LoyaltyProgram entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct LoyaltyProgramResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub program_name: String,
    pub program_type: LoyaltyProgramType,
    pub collection_factor: Decimal,
    pub conversion_factor: Decimal,
    pub expiry_duration_days: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub from_date: DateTime<Utc>,
    pub to_date: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_active: bool,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for LoyaltyProgram entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct LoyaltyProgramListResponseDto {
    /// List of items
    pub items: Vec<LoyaltyProgramResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl LoyaltyProgramListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<LoyaltyProgramResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct LoyaltyProgramSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub program_name: String,
    pub program_type: LoyaltyProgramType,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<LoyaltyProgram> for LoyaltyProgramResponseDto {
    fn from(entity: LoyaltyProgram) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            program_name: entity.program_name,
            program_type: entity.program_type,
            collection_factor: entity.collection_factor,
            conversion_factor: entity.conversion_factor,
            expiry_duration_days: entity.expiry_duration_days,
            from_date: entity.from_date,
            to_date: entity.to_date,
            is_active: entity.is_active,
            metadata: entity.metadata,
        }
    }
}

impl From<LoyaltyProgram> for LoyaltyProgramSummaryDto {
    fn from(entity: LoyaltyProgram) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            program_name: entity.program_name,
            program_type: entity.program_type,
            created_at,
        }
    }
}

impl From<CreateLoyaltyProgramDto> for LoyaltyProgram {
    fn from(dto: CreateLoyaltyProgramDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            program_name: dto.program_name,
            program_type: dto.program_type,
            collection_factor: dto.collection_factor,
            conversion_factor: dto.conversion_factor,
            expiry_duration_days: dto.expiry_duration_days,
            from_date: dto.from_date,
            to_date: dto.to_date,
            is_active: dto.is_active,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&LoyaltyProgram> for LoyaltyProgramResponseDto {
    fn from(entity: &LoyaltyProgram) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            program_name: entity.program_name.clone(),
            program_type: entity.program_type.clone(),
            collection_factor: entity.collection_factor.clone(),
            conversion_factor: entity.conversion_factor.clone(),
            expiry_duration_days: entity.expiry_duration_days.clone(),
            from_date: entity.from_date.clone(),
            to_date: entity.to_date.clone(),
            is_active: entity.is_active.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateLoyaltyProgramDto> for LoyaltyProgram {
    fn from_create_dto(dto: CreateLoyaltyProgramDto) -> backbone_core::ServiceResult<Self> {
        Ok(LoyaltyProgram::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateLoyaltyProgramDto> for LoyaltyProgram {
    fn apply_update(mut self, dto: UpdateLoyaltyProgramDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.program_name = dto.program_name;
        self.program_type = dto.program_type;
        self.collection_factor = dto.collection_factor;
        self.conversion_factor = dto.conversion_factor;
        self.expiry_duration_days = dto.expiry_duration_days;
        self.from_date = dto.from_date;
        self.to_date = dto.to_date;
        self.is_active = dto.is_active;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to LoyaltyProgram here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
