//! PromoBundle DTOs (Data Transfer Objects)
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::PromoBundle;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::BundleMatch;
use crate::domain::entity::RateOrDiscount;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new PromoBundle
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreatePromoBundleDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 140)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub title: String,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub priority: i32,
    #[serde(alias = "match_type")]
    pub match_type: BundleMatch,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "required_distinct")]
    pub required_distinct: Option<i32>,
    pub reward: RateOrDiscount,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "discount_percentage")]
    pub discount_percentage: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "discount_amount")]
    pub discount_amount: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "reward_item_id")]
    pub reward_item_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "reward_qty")]
    pub reward_qty: Option<Decimal>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    #[serde(alias = "min_order_amount")]
    pub min_order_amount: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub stackable: bool,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "valid_from")]
    pub valid_from: DateTime<Utc>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "valid_to")]
    pub valid_to: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_active")]
    pub is_active: bool,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a PromoBundle
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdatePromoBundleDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 140)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub title: String,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub priority: i32,
    #[serde(alias = "match_type")]
    pub match_type: BundleMatch,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "required_distinct")]
    pub required_distinct: Option<i32>,
    pub reward: RateOrDiscount,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "discount_percentage")]
    pub discount_percentage: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "discount_amount")]
    pub discount_amount: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "reward_item_id")]
    pub reward_item_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "reward_qty")]
    pub reward_qty: Option<Decimal>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    #[serde(alias = "min_order_amount")]
    pub min_order_amount: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub stackable: bool,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "valid_from")]
    pub valid_from: DateTime<Utc>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "valid_to")]
    pub valid_to: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_active")]
    pub is_active: bool,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a PromoBundle
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchPromoBundleDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 140)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub priority: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "match_type")]
    pub match_type: Option<BundleMatch>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "required_distinct")]
    pub required_distinct: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reward: Option<RateOrDiscount>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "discount_percentage")]
    pub discount_percentage: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "discount_amount")]
    pub discount_amount: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "reward_item_id")]
    pub reward_item_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "reward_qty")]
    pub reward_qty: Option<Decimal>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "min_order_amount")]
    pub min_order_amount: Option<Decimal>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub stackable: Option<bool>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "valid_from")]
    pub valid_from: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "valid_to")]
    pub valid_to: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "is_active")]
    pub is_active: Option<bool>,
}

impl PatchPromoBundleDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.title.is_some() || self.priority.is_some() || self.match_type.is_some() || self.required_distinct.is_some() || self.reward.is_some() || self.discount_percentage.is_some() || self.discount_amount.is_some() || self.reward_item_id.is_some() || self.reward_qty.is_some() || self.currency.is_some() || self.min_order_amount.is_some() || self.stackable.is_some() || self.valid_from.is_some() || self.valid_to.is_some() || self.is_active.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for PromoBundle entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PromoBundleResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub title: String,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub priority: i32,
    pub match_type: BundleMatch,
    pub required_distinct: Option<i32>,
    pub reward: RateOrDiscount,
    pub discount_percentage: Option<Decimal>,
    pub discount_amount: Option<Decimal>,
    pub reward_item_id: Option<Uuid>,
    pub reward_qty: Option<Decimal>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    pub min_order_amount: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub stackable: bool,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub valid_from: DateTime<Utc>,
    pub valid_to: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_active: bool,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for PromoBundle entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PromoBundleListResponseDto {
    /// List of items
    pub items: Vec<PromoBundleResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl PromoBundleListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<PromoBundleResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PromoBundleSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub title: String,
    pub priority: i32,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<PromoBundle> for PromoBundleResponseDto {
    fn from(entity: PromoBundle) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            title: entity.title,
            priority: entity.priority,
            match_type: entity.match_type,
            required_distinct: entity.required_distinct,
            reward: entity.reward,
            discount_percentage: entity.discount_percentage,
            discount_amount: entity.discount_amount,
            reward_item_id: entity.reward_item_id,
            reward_qty: entity.reward_qty,
            currency: entity.currency,
            min_order_amount: entity.min_order_amount,
            stackable: entity.stackable,
            valid_from: entity.valid_from,
            valid_to: entity.valid_to,
            is_active: entity.is_active,
            metadata: entity.metadata,
        }
    }
}

impl From<PromoBundle> for PromoBundleSummaryDto {
    fn from(entity: PromoBundle) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            title: entity.title,
            priority: entity.priority,
            created_at,
        }
    }
}

impl From<CreatePromoBundleDto> for PromoBundle {
    fn from(dto: CreatePromoBundleDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            title: dto.title,
            priority: dto.priority,
            match_type: dto.match_type,
            required_distinct: dto.required_distinct,
            reward: dto.reward,
            discount_percentage: dto.discount_percentage,
            discount_amount: dto.discount_amount,
            reward_item_id: dto.reward_item_id,
            reward_qty: dto.reward_qty,
            currency: dto.currency,
            min_order_amount: dto.min_order_amount,
            stackable: dto.stackable,
            valid_from: dto.valid_from,
            valid_to: dto.valid_to,
            is_active: dto.is_active,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&PromoBundle> for PromoBundleResponseDto {
    fn from(entity: &PromoBundle) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            title: entity.title.clone(),
            priority: entity.priority.clone(),
            match_type: entity.match_type.clone(),
            required_distinct: entity.required_distinct.clone(),
            reward: entity.reward.clone(),
            discount_percentage: entity.discount_percentage.clone(),
            discount_amount: entity.discount_amount.clone(),
            reward_item_id: entity.reward_item_id.clone(),
            reward_qty: entity.reward_qty.clone(),
            currency: entity.currency.clone(),
            min_order_amount: entity.min_order_amount.clone(),
            stackable: entity.stackable.clone(),
            valid_from: entity.valid_from.clone(),
            valid_to: entity.valid_to.clone(),
            is_active: entity.is_active.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreatePromoBundleDto> for PromoBundle {
    fn from_create_dto(dto: CreatePromoBundleDto) -> backbone_core::ServiceResult<Self> {
        Ok(PromoBundle::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdatePromoBundleDto> for PromoBundle {
    fn apply_update(mut self, dto: UpdatePromoBundleDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.title = dto.title;
        self.priority = dto.priority;
        self.match_type = dto.match_type;
        self.required_distinct = dto.required_distinct;
        self.reward = dto.reward;
        self.discount_percentage = dto.discount_percentage;
        self.discount_amount = dto.discount_amount;
        self.reward_item_id = dto.reward_item_id;
        self.reward_qty = dto.reward_qty;
        self.currency = dto.currency;
        self.min_order_amount = dto.min_order_amount;
        self.stackable = dto.stackable;
        self.valid_from = dto.valid_from;
        self.valid_to = dto.valid_to;
        self.is_active = dto.is_active;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to PromoBundle here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
