//! PromoBundleComponent DTOs (Data Transfer Objects)
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::PromoBundleComponent;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::ApplyOn;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new PromoBundleComponent
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreatePromoBundleComponentDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "bundle_id")]
    pub bundle_id: Uuid,
    #[serde(alias = "apply_on")]
    pub apply_on: ApplyOn,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "item_id")]
    pub item_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "item_group_id")]
    pub item_group_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "brand_id")]
    pub brand_id: Option<Uuid>,
    #[serde(alias = "min_qty")]
    pub min_qty: Decimal,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a PromoBundleComponent
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdatePromoBundleComponentDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "bundle_id")]
    pub bundle_id: Uuid,
    #[serde(alias = "apply_on")]
    pub apply_on: ApplyOn,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "item_id")]
    pub item_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "item_group_id")]
    pub item_group_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "brand_id")]
    pub brand_id: Option<Uuid>,
    #[serde(alias = "min_qty")]
    pub min_qty: Decimal,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a PromoBundleComponent
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchPromoBundleComponentDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "bundle_id")]
    pub bundle_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "apply_on")]
    pub apply_on: Option<ApplyOn>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "item_id")]
    pub item_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "item_group_id")]
    pub item_group_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "brand_id")]
    pub brand_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "min_qty")]
    pub min_qty: Option<Decimal>,
}

impl PatchPromoBundleComponentDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.bundle_id.is_some() || self.apply_on.is_some() || self.item_id.is_some() || self.item_group_id.is_some() || self.brand_id.is_some() || self.min_qty.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for PromoBundleComponent entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PromoBundleComponentResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub bundle_id: Uuid,
    pub apply_on: ApplyOn,
    pub item_id: Option<Uuid>,
    pub item_group_id: Option<Uuid>,
    pub brand_id: Option<Uuid>,
    pub min_qty: Decimal,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for PromoBundleComponent entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PromoBundleComponentListResponseDto {
    /// List of items
    pub items: Vec<PromoBundleComponentResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl PromoBundleComponentListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<PromoBundleComponentResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PromoBundleComponentSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub bundle_id: Uuid,
    pub apply_on: ApplyOn,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<PromoBundleComponent> for PromoBundleComponentResponseDto {
    fn from(entity: PromoBundleComponent) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            bundle_id: entity.bundle_id,
            apply_on: entity.apply_on,
            item_id: entity.item_id,
            item_group_id: entity.item_group_id,
            brand_id: entity.brand_id,
            min_qty: entity.min_qty,
            metadata: entity.metadata,
        }
    }
}

impl From<PromoBundleComponent> for PromoBundleComponentSummaryDto {
    fn from(entity: PromoBundleComponent) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            bundle_id: entity.bundle_id,
            apply_on: entity.apply_on,
            created_at,
        }
    }
}

impl From<CreatePromoBundleComponentDto> for PromoBundleComponent {
    fn from(dto: CreatePromoBundleComponentDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            bundle_id: dto.bundle_id,
            apply_on: dto.apply_on,
            item_id: dto.item_id,
            item_group_id: dto.item_group_id,
            brand_id: dto.brand_id,
            min_qty: dto.min_qty,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&PromoBundleComponent> for PromoBundleComponentResponseDto {
    fn from(entity: &PromoBundleComponent) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            bundle_id: entity.bundle_id.clone(),
            apply_on: entity.apply_on.clone(),
            item_id: entity.item_id.clone(),
            item_group_id: entity.item_group_id.clone(),
            brand_id: entity.brand_id.clone(),
            min_qty: entity.min_qty.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreatePromoBundleComponentDto> for PromoBundleComponent {
    fn from_create_dto(dto: CreatePromoBundleComponentDto) -> backbone_core::ServiceResult<Self> {
        Ok(PromoBundleComponent::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdatePromoBundleComponentDto> for PromoBundleComponent {
    fn apply_update(mut self, dto: UpdatePromoBundleComponentDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.bundle_id = dto.bundle_id;
        self.apply_on = dto.apply_on;
        self.item_id = dto.item_id;
        self.item_group_id = dto.item_group_id;
        self.brand_id = dto.brand_id;
        self.min_qty = dto.min_qty;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to PromoBundleComponent here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
