//! ProviderPromo DTOs (Data Transfer Objects)
//!
//! Auto-generated by backbone-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::ProviderPromo;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::PromoEligibility;
use crate::domain::entity::PromoType;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new ProviderPromo
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateProviderPromoDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub provider_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub outlet_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 100)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub promo_name: String,
    #[cfg_attr(feature = "validation", validate(range(max = 20)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub promo_code: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    pub promo_type: PromoType,
    pub discount_value: Decimal,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max_discount: Option<Decimal>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub min_order_amount: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub min_weight_kg: Option<Decimal>,
    pub applicable_services: serde_json::Value,
    pub applicable_categories: serde_json::Value,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub valid_from: DateTime<Utc>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub valid_until: DateTime<Utc>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub usage_limit: Option<i32>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub usage_limit_per_customer: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub usage_count: i32,
    pub eligible_customers: PromoEligibility,
    pub eligible_tiers: serde_json::Value,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_active: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_public: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_stackable: bool,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub banner_url: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 2000)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub terms_conditions: Option<String>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a ProviderPromo
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateProviderPromoDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub provider_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub outlet_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 100)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub promo_name: String,
    #[cfg_attr(feature = "validation", validate(range(max = 20)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub promo_code: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    pub promo_type: PromoType,
    pub discount_value: Decimal,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max_discount: Option<Decimal>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub min_order_amount: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub min_weight_kg: Option<Decimal>,
    pub applicable_services: serde_json::Value,
    pub applicable_categories: serde_json::Value,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub valid_from: DateTime<Utc>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub valid_until: DateTime<Utc>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub usage_limit: Option<i32>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub usage_limit_per_customer: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub usage_count: i32,
    pub eligible_customers: PromoEligibility,
    pub eligible_tiers: serde_json::Value,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_active: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_public: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_stackable: bool,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub banner_url: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 2000)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub terms_conditions: Option<String>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a ProviderPromo
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchProviderPromoDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub provider_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub outlet_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub promo_name: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub promo_code: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub promo_type: Option<PromoType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub discount_value: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_discount: Option<Decimal>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub min_order_amount: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub min_weight_kg: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub applicable_services: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub applicable_categories: Option<serde_json::Value>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub valid_from: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub valid_until: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub usage_limit: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub usage_limit_per_customer: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub usage_count: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub eligible_customers: Option<PromoEligibility>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub eligible_tiers: Option<serde_json::Value>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_active: Option<bool>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_public: Option<bool>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_stackable: Option<bool>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub banner_url: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub terms_conditions: Option<String>,
}

impl PatchProviderPromoDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.provider_id.is_some() || self.outlet_id.is_some() || self.promo_name.is_some() || self.promo_code.is_some() || self.description.is_some() || self.promo_type.is_some() || self.discount_value.is_some() || self.max_discount.is_some() || self.currency.is_some() || self.min_order_amount.is_some() || self.min_weight_kg.is_some() || self.applicable_services.is_some() || self.applicable_categories.is_some() || self.valid_from.is_some() || self.valid_until.is_some() || self.usage_limit.is_some() || self.usage_limit_per_customer.is_some() || self.usage_count.is_some() || self.eligible_customers.is_some() || self.eligible_tiers.is_some() || self.is_active.is_some() || self.is_public.is_some() || self.is_stackable.is_some() || self.banner_url.is_some() || self.terms_conditions.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for ProviderPromo entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ProviderPromoResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub provider_id: Uuid,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub outlet_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub promo_name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub promo_code: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    pub promo_type: PromoType,
    pub discount_value: Decimal,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_discount: Option<Decimal>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub min_order_amount: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub min_weight_kg: Option<Decimal>,
    pub applicable_services: serde_json::Value,
    pub applicable_categories: serde_json::Value,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub valid_from: DateTime<Utc>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub valid_until: DateTime<Utc>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub usage_limit: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub usage_limit_per_customer: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub usage_count: i32,
    pub eligible_customers: PromoEligibility,
    pub eligible_tiers: serde_json::Value,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_active: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_public: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_stackable: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub banner_url: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub terms_conditions: Option<String>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for ProviderPromo entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ProviderPromoListResponseDto {
    /// List of items
    pub items: Vec<ProviderPromoResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl ProviderPromoListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<ProviderPromoResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ProviderPromoSummaryDto {
    pub id: Uuid,
    pub provider_id: Uuid,
    pub outlet_id: Option<Uuid>,
    pub promo_name: String,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<ProviderPromo> for ProviderPromoResponseDto {
    fn from(entity: ProviderPromo) -> Self {
        Self {
            id: entity.id,
            provider_id: entity.provider_id,
            outlet_id: entity.outlet_id,
            promo_name: entity.promo_name,
            promo_code: entity.promo_code,
            description: entity.description,
            promo_type: entity.promo_type,
            discount_value: entity.discount_value,
            max_discount: entity.max_discount,
            currency: entity.currency,
            min_order_amount: entity.min_order_amount,
            min_weight_kg: entity.min_weight_kg,
            applicable_services: entity.applicable_services,
            applicable_categories: entity.applicable_categories,
            valid_from: entity.valid_from,
            valid_until: entity.valid_until,
            usage_limit: entity.usage_limit,
            usage_limit_per_customer: entity.usage_limit_per_customer,
            usage_count: entity.usage_count,
            eligible_customers: entity.eligible_customers,
            eligible_tiers: entity.eligible_tiers,
            is_active: entity.is_active,
            is_public: entity.is_public,
            is_stackable: entity.is_stackable,
            banner_url: entity.banner_url,
            terms_conditions: entity.terms_conditions,
            metadata: entity.metadata,
        }
    }
}

impl From<ProviderPromo> for ProviderPromoSummaryDto {
    fn from(entity: ProviderPromo) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            provider_id: entity.provider_id,
            outlet_id: entity.outlet_id,
            promo_name: entity.promo_name,
            created_at,
        }
    }
}

impl From<CreateProviderPromoDto> for ProviderPromo {
    fn from(dto: CreateProviderPromoDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            provider_id: dto.provider_id,
            outlet_id: dto.outlet_id,
            promo_name: dto.promo_name,
            promo_code: dto.promo_code,
            description: dto.description,
            promo_type: dto.promo_type,
            discount_value: dto.discount_value,
            max_discount: dto.max_discount,
            currency: dto.currency,
            min_order_amount: dto.min_order_amount,
            min_weight_kg: dto.min_weight_kg,
            applicable_services: dto.applicable_services,
            applicable_categories: dto.applicable_categories,
            valid_from: dto.valid_from,
            valid_until: dto.valid_until,
            usage_limit: dto.usage_limit,
            usage_limit_per_customer: dto.usage_limit_per_customer,
            usage_count: dto.usage_count,
            eligible_customers: dto.eligible_customers,
            eligible_tiers: dto.eligible_tiers,
            is_active: dto.is_active,
            is_public: dto.is_public,
            is_stackable: dto.is_stackable,
            banner_url: dto.banner_url,
            terms_conditions: dto.terms_conditions,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&ProviderPromo> for ProviderPromoResponseDto {
    fn from(entity: &ProviderPromo) -> Self {
        Self {
            id: entity.id.clone(),
            provider_id: entity.provider_id.clone(),
            outlet_id: entity.outlet_id.clone(),
            promo_name: entity.promo_name.clone(),
            promo_code: entity.promo_code.clone(),
            description: entity.description.clone(),
            promo_type: entity.promo_type.clone(),
            discount_value: entity.discount_value.clone(),
            max_discount: entity.max_discount.clone(),
            currency: entity.currency.clone(),
            min_order_amount: entity.min_order_amount.clone(),
            min_weight_kg: entity.min_weight_kg.clone(),
            applicable_services: entity.applicable_services.clone(),
            applicable_categories: entity.applicable_categories.clone(),
            valid_from: entity.valid_from.clone(),
            valid_until: entity.valid_until.clone(),
            usage_limit: entity.usage_limit.clone(),
            usage_limit_per_customer: entity.usage_limit_per_customer.clone(),
            usage_count: entity.usage_count.clone(),
            eligible_customers: entity.eligible_customers.clone(),
            eligible_tiers: entity.eligible_tiers.clone(),
            is_active: entity.is_active.clone(),
            is_public: entity.is_public.clone(),
            is_stackable: entity.is_stackable.clone(),
            banner_url: entity.banner_url.clone(),
            terms_conditions: entity.terms_conditions.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateProviderPromoDto> for ProviderPromo {
    fn from_create_dto(dto: CreateProviderPromoDto) -> backbone_core::ServiceResult<Self> {
        Ok(ProviderPromo::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateProviderPromoDto> for ProviderPromo {
    fn apply_update(mut self, dto: UpdateProviderPromoDto) -> backbone_core::ServiceResult<Self> {
        self.provider_id = dto.provider_id;
        self.outlet_id = dto.outlet_id;
        self.promo_name = dto.promo_name;
        self.promo_code = dto.promo_code;
        self.description = dto.description;
        self.promo_type = dto.promo_type;
        self.discount_value = dto.discount_value;
        self.max_discount = dto.max_discount;
        self.currency = dto.currency;
        self.min_order_amount = dto.min_order_amount;
        self.min_weight_kg = dto.min_weight_kg;
        self.applicable_services = dto.applicable_services;
        self.applicable_categories = dto.applicable_categories;
        self.valid_from = dto.valid_from;
        self.valid_until = dto.valid_until;
        self.usage_limit = dto.usage_limit;
        self.usage_limit_per_customer = dto.usage_limit_per_customer;
        self.usage_count = dto.usage_count;
        self.eligible_customers = dto.eligible_customers;
        self.eligible_tiers = dto.eligible_tiers;
        self.is_active = dto.is_active;
        self.is_public = dto.is_public;
        self.is_stackable = dto.is_stackable;
        self.banner_url = dto.banner_url;
        self.terms_conditions = dto.terms_conditions;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to ProviderPromo here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

