//! GraphQL schema composition for Promo module
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Provides both standalone `build_schema()` and composable `inject_services()`
//! methods. Use `inject_services()` to compose module GraphQL services into
//! a shared app-level schema.

use std::sync::Arc;
use async_graphql::*;

use super::{AdPerformanceQuery, AdPerformanceMutation};
use super::{AdvertisementQuery, AdvertisementMutation};
use super::{ProviderPromoQuery, ProviderPromoMutation};
use super::{PromoCampaignQuery, PromoCampaignMutation};

use crate::application::service::AdPerformanceService;
use crate::application::service::AdvertisementService;
use crate::application::service::ProviderPromoService;
use crate::application::service::PromoCampaignService;

/// Merged Query root for Promo module
#[derive(MergedObject, Default)]
pub struct PromoQuery(AdPerformanceQuery, AdvertisementQuery, ProviderPromoQuery, PromoCampaignQuery);

/// Merged Mutation root for Promo module
#[derive(MergedObject, Default)]
pub struct PromoMutation(AdPerformanceMutation, AdvertisementMutation, ProviderPromoMutation, PromoCampaignMutation);

/// Inject all Promo services into a schema builder
pub fn inject_services<Q: ObjectType + 'static, M: ObjectType + 'static, S: SubscriptionType + 'static>(
    builder: SchemaBuilder<Q, M, S>,
    module: &crate::PromoModule,
) -> SchemaBuilder<Q, M, S> {
    builder
        .data(module.ad_performance_service.clone())
        .data(module.advertisement_service.clone())
        .data(module.provider_promo_service.clone())
        .data(module.promo_campaign_service.clone())
}

/// Build the GraphQL schema for Promo module (standalone)
pub fn build_schema(module: &crate::PromoModule) -> Schema<PromoQuery, PromoMutation, EmptySubscription> {
    let builder = Schema::build(PromoQuery::default(), PromoMutation::default(), EmptySubscription);
    inject_services(builder, module).finish()
}
