//! gRPC service registration
//!
//! Generated by backbone-schema. Do not edit manually.

use tonic::transport::Server;

use super::grpc::ad_performance_grpc_service::AdPerformanceGrpcService;
use super::grpc::advertisement_grpc_service::AdvertisementGrpcService;
use super::grpc::provider_promo_grpc_service::ProviderPromoGrpcService;
use super::grpc::promo_campaign_grpc_service::PromoCampaignGrpcService;

/// gRPC server for Promo module
pub struct PromoGrpcServer {
    ad_performance_service: AdPerformanceGrpcService,
    advertisement_service: AdvertisementGrpcService,
    provider_promo_service: ProviderPromoGrpcService,
    promo_campaign_service: PromoCampaignGrpcService,
}

impl PromoGrpcServer {
    /// Create a new gRPC server from module
    pub fn new(module: &super::PromoModule) -> Self {
        Self {
            ad_performance_service: AdPerformanceGrpcService::new(module.ad_performance_service.clone()),
            advertisement_service: AdvertisementGrpcService::new(module.advertisement_service.clone()),
            provider_promo_service: ProviderPromoGrpcService::new(module.provider_promo_service.clone()),
            promo_campaign_service: PromoCampaignGrpcService::new(module.promo_campaign_service.clone()),
        }
    }

    /// Start the gRPC server
    pub async fn serve(self, addr: std::net::SocketAddr) -> Result<(), tonic::transport::Error> {
        Server::builder()
            .add_service(self.ad_performance_service.into_service())
            .add_service(self.advertisement_service.into_service())
            .add_service(self.provider_promo_service.into_service())
            .add_service(self.promo_campaign_service.into_service())
            .serve(addr)
            .await
    }
}
