//! Domain specifications
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Combinators (AND/OR/NOT) come from `backbone_core::Specification`.

pub use backbone_core::{Specification, AndSpecification, OrSpecification, NotSpecification};

pub mod coupon_code_specification;
pub mod coupon_redemption_specification;
pub mod loyalty_program_specification;
pub mod loyalty_point_entry_specification;
pub mod pricing_rule_specification;
pub mod promo_bundle_specification;
pub mod promo_bundle_component_specification;

// <<< CUSTOM
// END CUSTOM
