//! Domain specifications
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Combinators (AND/OR/NOT) come from `backbone_core::Specification`.

pub use backbone_core::{Specification, AndSpecification, OrSpecification, NotSpecification};

pub mod ad_performance_specification;
pub mod advertisement_specification;
pub mod provider_promo_specification;
pub mod promo_campaign_specification;

// <<< CUSTOM
// END CUSTOM
