//! Domain policy for LoyaltyProgram aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::LoyaltyProgram;

/// Domain policy for LoyaltyProgram — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<LoyaltyProgram>` in the `// <<< CUSTOM` zone.
pub type LoyaltyProgramDomainPolicy = PermitAllPolicy<LoyaltyProgram>;

// <<< CUSTOM
// END CUSTOM
