//! Application service for AdPerformance entities
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `ad_performance_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateAdPerformanceDto, UpdateAdPerformanceDto};
use crate::domain::entity::AdPerformance;
use crate::infrastructure::persistence::AdPerformanceRepository;

/// Application service for AdPerformance entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `ad_performance_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct AdPerformanceServiceCustom {
///     inner: Arc<AdPerformanceService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type AdPerformanceService = GenericCrudService<
    AdPerformance,
    CreateAdPerformanceDto,
    UpdateAdPerformanceDto,
    AdPerformanceRepository,
>;

// <<< CUSTOM
// END CUSTOM
