//! Application service for Advertisement entities
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `advertisement_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateAdvertisementDto, UpdateAdvertisementDto};
use crate::domain::entity::Advertisement;
use crate::infrastructure::persistence::AdvertisementRepository;

/// Application service for Advertisement entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `advertisement_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct AdvertisementServiceCustom {
///     inner: Arc<AdvertisementService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type AdvertisementService = GenericCrudService<
    Advertisement,
    CreateAdvertisementDto,
    UpdateAdvertisementDto,
    AdvertisementRepository,
>;

// <<< CUSTOM
// END CUSTOM
