//! Application service for CouponRedemption entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `coupon_redemption_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateCouponRedemptionDto, UpdateCouponRedemptionDto};
use crate::domain::entity::CouponRedemption;
use crate::infrastructure::persistence::CouponRedemptionRepository;

/// Application service for CouponRedemption entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `coupon_redemption_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct CouponRedemptionServiceCustom {
///     inner: Arc<CouponRedemptionService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type CouponRedemptionService = GenericCrudService<
    CouponRedemption,
    CreateCouponRedemptionDto,
    UpdateCouponRedemptionDto,
    CouponRedemptionRepository,
>;

// <<< CUSTOM
// END CUSTOM
