//! Application service for LoyaltyOrderPoints entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `loyalty_order_points_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateLoyaltyOrderPointsDto, UpdateLoyaltyOrderPointsDto};
use crate::domain::entity::LoyaltyOrderPoints;
use crate::infrastructure::persistence::LoyaltyOrderPointsRepository;

/// Application service for LoyaltyOrderPoints entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `loyalty_order_points_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct LoyaltyOrderPointsServiceCustom {
///     inner: Arc<LoyaltyOrderPointsService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type LoyaltyOrderPointsService = GenericCrudService<
    LoyaltyOrderPoints,
    CreateLoyaltyOrderPointsDto,
    UpdateLoyaltyOrderPointsDto,
    LoyaltyOrderPointsRepository,
>;

// <<< CUSTOM
// END CUSTOM
