//! Application services
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Each entity service is a type alias over `GenericCrudService`.

pub mod error;
pub use error::{ServiceError, ServiceResult};

mod ad_performance_service;
mod advertisement_service;
mod provider_promo_service;
mod promo_campaign_service;

// <<< CUSTOM
// END CUSTOM

pub use ad_performance_service::AdPerformanceService;
pub use advertisement_service::AdvertisementService;
pub use provider_promo_service::ProviderPromoService;
pub use promo_campaign_service::PromoCampaignService;
// <<< CUSTOM
// END CUSTOM
