//! Application service for PromoBundleComponent entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `promo_bundle_component_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreatePromoBundleComponentDto, UpdatePromoBundleComponentDto};
use crate::domain::entity::PromoBundleComponent;
use crate::infrastructure::persistence::PromoBundleComponentRepository;

/// Application service for PromoBundleComponent entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `promo_bundle_component_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct PromoBundleComponentServiceCustom {
///     inner: Arc<PromoBundleComponentService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type PromoBundleComponentService = GenericCrudService<
    PromoBundleComponent,
    CreatePromoBundleComponentDto,
    UpdatePromoBundleComponentDto,
    PromoBundleComponentRepository,
>;

// <<< CUSTOM
// END CUSTOM
