//! Application service for PromoBundle entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `promo_bundle_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreatePromoBundleDto, UpdatePromoBundleDto};
use crate::domain::entity::PromoBundle;
use crate::infrastructure::persistence::PromoBundleRepository;

/// Application service for PromoBundle entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `promo_bundle_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct PromoBundleServiceCustom {
///     inner: Arc<PromoBundleService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type PromoBundleService = GenericCrudService<
    PromoBundle,
    CreatePromoBundleDto,
    UpdatePromoBundleDto,
    PromoBundleRepository,
>;

// <<< CUSTOM
// END CUSTOM
