//! Application service for PromoBundleGift entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `promo_bundle_gift_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreatePromoBundleGiftDto, UpdatePromoBundleGiftDto};
use crate::domain::entity::PromoBundleGift;
use crate::infrastructure::persistence::PromoBundleGiftRepository;

/// Application service for PromoBundleGift entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `promo_bundle_gift_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct PromoBundleGiftServiceCustom {
///     inner: Arc<PromoBundleGiftService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type PromoBundleGiftService = GenericCrudService<
    PromoBundleGift,
    CreatePromoBundleGiftDto,
    UpdatePromoBundleGiftDto,
    PromoBundleGiftRepository,
>;

// <<< CUSTOM
// END CUSTOM
