//! Application service for PromoCampaign entities
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `promo_campaign_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreatePromoCampaignDto, UpdatePromoCampaignDto};
use crate::domain::entity::PromoCampaign;
use crate::infrastructure::persistence::PromoCampaignRepository;

/// Application service for PromoCampaign entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `promo_campaign_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct PromoCampaignServiceCustom {
///     inner: Arc<PromoCampaignService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type PromoCampaignService = GenericCrudService<
    PromoCampaign,
    CreatePromoCampaignDto,
    UpdatePromoCampaignDto,
    PromoCampaignRepository,
>;

// <<< CUSTOM
// END CUSTOM
