//! Command handlers for Promo module
//!
//! Commands represent write operations that modify state.
//! Part of CQRS pattern implementation.
//!
//! Generated by backbone-schema. Custom code sections are preserved.

// Commands will be generated here by backbone-schema
// Use: backbone schema generate promo --target cqrs
