-- CouponCode Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the promo.coupon_codes table.
-- Customize this file to add your initial data.

-- INSERT INTO promo.coupon_codes (
--     id,
--     company_id,
--     code,
--     pricing_rule_id,
--     description,
--     max_use,
--     used_count,
--     valid_from,
--     valid_upto,
--     is_active,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert reference data
-- Uncomment and modify the following:

-- INSERT INTO promo.coupon_codes (id, code, name, is_active, created_at, updated_at) VALUES
--     (gen_random_uuid(), 'SAMPLE1', 'Sample 1', true, NOW(), NOW()),
--     (gen_random_uuid(), 'SAMPLE2', 'Sample 2', true, NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

