-- LoyaltyOrderPoints Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the promo.loyalty_order_points table.
-- Customize this file to add your initial data.

-- INSERT INTO promo.loyalty_order_points (
--     id,
--     company_id,
--     loyalty_program_id,
--     customer_id,
--     order_ref_type,
--     order_ref_id,
--     coupon_code_id,
--     grant_base_amount,
--     granted_points,
--     spent_points,
--     granted_reversed_points,
--     spent_reversed_points,
--     granted_at,
--     spent_at,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO promo.loyalty_order_points (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

