-- LoyaltyProgram Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the promo.loyalty_programs table.
-- Customize this file to add your initial data.

-- INSERT INTO promo.loyalty_programs (
--     id,
--     company_id,
--     program_name,
--     program_type,
--     collection_factor,
--     conversion_factor,
--     expiry_duration_days,
--     from_date,
--     to_date,
--     is_active,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert reference data
-- Uncomment and modify the following:

-- INSERT INTO promo.loyalty_programs (id, code, name, is_active, created_at, updated_at) VALUES
--     (gen_random_uuid(), 'SAMPLE1', 'Sample 1', true, NOW(), NOW()),
--     (gen_random_uuid(), 'SAMPLE2', 'Sample 2', true, NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

