-- PricingRule Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the promo.pricing_rules table.
-- Customize this file to add your initial data.

-- INSERT INTO promo.pricing_rules (
--     id,
--     company_id,
--     title,
--     priority,
--     apply_on,
--     item_id,
--     item_group_id,
--     brand_id,
--     customer_id,
--     customer_group_id,
--     min_qty,
--     max_qty,
--     min_amount,
--     rate_or_discount,
--     rate,
--     discount_percentage,
--     discount_amount,
--     currency,
--     valid_from,
--     valid_to,
--     coupon_required,
--     is_active,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert reference data
-- Uncomment and modify the following:

-- INSERT INTO promo.pricing_rules (id, code, name, is_active, created_at, updated_at) VALUES
--     (gen_random_uuid(), 'SAMPLE1', 'Sample 1', true, NOW(), NOW()),
--     (gen_random_uuid(), 'SAMPLE2', 'Sample 2', true, NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

