-- PromoBundleComponent Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the promo.promo_bundle_components table.
-- Customize this file to add your initial data.

-- INSERT INTO promo.promo_bundle_components (
--     id,
--     company_id,
--     bundle_id,
--     apply_on,
--     item_id,
--     item_group_id,
--     brand_id,
--     min_qty,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO promo.promo_bundle_components (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

