-- PromoBundleGift Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the promo.promo_bundle_gifts table.
-- Customize this file to add your initial data.

-- INSERT INTO promo.promo_bundle_gifts (
--     id,
--     company_id,
--     bundle_id,
--     gift_item_id,
--     gift_qty,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO promo.promo_bundle_gifts (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

