-- Enum types for promo module
-- Generated by backbone-schema

-- Create ad_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'ad_type') THEN
        CREATE TYPE ad_type AS ENUM ('banner', 'featured', 'promoted', 'popup', 'push', 'sms', 'email');
    END IF;
END
$$;

-- Create ad_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'ad_status') THEN
        CREATE TYPE ad_status AS ENUM ('draft', 'pending', 'active', 'paused', 'completed', 'rejected');
    END IF;
END
$$;

-- Create ad_placement enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'ad_placement') THEN
        CREATE TYPE ad_placement AS ENUM ('home_top', 'home_middle', 'search_results', 'service_detail', 'checkout', 'order_complete');
    END IF;
END
$$;

-- Create ad_billing_model enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'ad_billing_model') THEN
        CREATE TYPE ad_billing_model AS ENUM ('cpm', 'cpc', 'cpa', 'flat_rate');
    END IF;
END
$$;

-- Create promo_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'promo_type') THEN
        CREATE TYPE promo_type AS ENUM ('percentage', 'fixed_amount', 'free_delivery', 'free_pickup', 'buy_x_get_y', 'cashback');
    END IF;
END
$$;

-- Create promo_eligibility enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'promo_eligibility') THEN
        CREATE TYPE promo_eligibility AS ENUM ('all', 'new_customer', 'returning_customer', 'loyalty_member', 'specific_tiers');
    END IF;
END
$$;

-- Create campaign_promo_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'campaign_promo_type') THEN
        CREATE TYPE campaign_promo_type AS ENUM ('percentage', 'fixed_amount', 'free_delivery', 'free_item', 'cashback', 'bundle');
    END IF;
END
$$;

-- Create campaign_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'campaign_status') THEN
        CREATE TYPE campaign_status AS ENUM ('draft', 'scheduled', 'active', 'paused', 'ended', 'cancelled');
    END IF;
END
$$;

-- Create campaign_target enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'campaign_target') THEN
        CREATE TYPE campaign_target AS ENUM ('all', 'new_users', 'returning', 'inactive', 'specific', 'loyal');
    END IF;
END
$$;

-- Create campaign_funder enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'campaign_funder') THEN
        CREATE TYPE campaign_funder AS ENUM ('platform', 'provider', 'shared');
    END IF;
END
$$;

