-- Migration: Create advertisements table
-- Generated by backbone-schema

CREATE TABLE IF NOT EXISTS advertisements (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    ad_number TEXT NOT NULL,
    provider_id UUID NOT NULL,
    placement ad_placement NOT NULL,
    position INTEGER,
    headline TEXT,
    description TEXT,
    image_url TEXT NOT NULL,
    image_url_mobile TEXT,
    click_url TEXT,
    action_type TEXT,
    action_reference TEXT,
    target_zones JSONB NOT NULL DEFAULT '[]'::jsonb,
    target_services JSONB NOT NULL DEFAULT '[]'::jsonb,
    target_audience TEXT NOT NULL DEFAULT 'all',
    status ad_status NOT NULL DEFAULT 'draft',
    start_at TIMESTAMPTZ NOT NULL,
    end_at TIMESTAMPTZ NOT NULL,
    currency TEXT NOT NULL DEFAULT 'IDR',
    billing_model ad_billing_model NOT NULL DEFAULT 'cpm',
    bid_amount NUMERIC NOT NULL,
    daily_budget NUMERIC,
    total_budget NUMERIC,
    budget_spent NUMERIC NOT NULL DEFAULT 0,
    max_impressions INTEGER,
    max_clicks INTEGER,
    frequency_cap INTEGER,
    total_impressions INTEGER NOT NULL DEFAULT 0,
    total_clicks INTEGER NOT NULL DEFAULT 0,
    total_conversions INTEGER NOT NULL DEFAULT 0,
    conversion_value NUMERIC NOT NULL DEFAULT 0,
    click_through_rate NUMERIC,
    conversion_rate NUMERIC,
    approved_at TIMESTAMPTZ,
    approved_by UUID,
    rejection_reason TEXT,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_advertisements_ad_number ON advertisements (ad_number) WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_advertisements_provider_id_status ON advertisements (provider_id, status);

CREATE INDEX IF NOT EXISTS idx_advertisements_status_start_at_end_at ON advertisements (status, start_at, end_at);

CREATE INDEX IF NOT EXISTS idx_advertisements_placement_status ON advertisements (placement, status);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_advertisements_metadata_gin ON advertisements USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_advertisements_metadata_deleted_at ON advertisements ((metadata->>'deleted_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION advertisements_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS advertisements_insert_audit ON advertisements;
CREATE TRIGGER advertisements_insert_audit BEFORE INSERT ON advertisements
    FOR EACH ROW EXECUTE FUNCTION advertisements_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS advertisements_update_audit ON advertisements;
CREATE TRIGGER advertisements_update_audit BEFORE UPDATE ON advertisements
    FOR EACH ROW EXECUTE FUNCTION advertisements_audit_timestamp();

