-- Foreign key constraints for promo module
-- Generated by backbone-schema

ALTER TABLE ad_performances ADD CONSTRAINT fk_ad_performances_advertisement_id FOREIGN KEY (advertisement_id) REFERENCES advertisements (id);

