-- Audit Triggers Migration for promo module
-- Generated by backbone-schema
--
-- This migration adds automatic timestamp management triggers
-- to all tables with audit metadata fields.
--
-- Triggers automatically set:
--   - metadata->'created_at' on INSERT
--   - metadata->'updated_at' on INSERT and UPDATE

-- ==============================================================================
-- Table: AdPerformance (ad_performances)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION ad_performances_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS ad_performances_insert_audit ON ad_performances;
CREATE TRIGGER ad_performances_insert_audit BEFORE INSERT ON ad_performances
    FOR EACH ROW EXECUTE FUNCTION ad_performances_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS ad_performances_update_audit ON ad_performances;
CREATE TRIGGER ad_performances_update_audit BEFORE UPDATE ON ad_performances
    FOR EACH ROW EXECUTE FUNCTION ad_performances_audit_timestamp();

-- ==============================================================================
-- Table: Advertisement (advertisements)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION advertisements_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS advertisements_insert_audit ON advertisements;
CREATE TRIGGER advertisements_insert_audit BEFORE INSERT ON advertisements
    FOR EACH ROW EXECUTE FUNCTION advertisements_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS advertisements_update_audit ON advertisements;
CREATE TRIGGER advertisements_update_audit BEFORE UPDATE ON advertisements
    FOR EACH ROW EXECUTE FUNCTION advertisements_audit_timestamp();

-- ==============================================================================
-- Table: ProviderPromo (provider_promos)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION provider_promos_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS provider_promos_insert_audit ON provider_promos;
CREATE TRIGGER provider_promos_insert_audit BEFORE INSERT ON provider_promos
    FOR EACH ROW EXECUTE FUNCTION provider_promos_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS provider_promos_update_audit ON provider_promos;
CREATE TRIGGER provider_promos_update_audit BEFORE UPDATE ON provider_promos
    FOR EACH ROW EXECUTE FUNCTION provider_promos_audit_timestamp();

-- ==============================================================================
-- Table: PromoCampaign (promo_campaigns)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION promo_campaigns_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS promo_campaigns_insert_audit ON promo_campaigns;
CREATE TRIGGER promo_campaigns_insert_audit BEFORE INSERT ON promo_campaigns
    FOR EACH ROW EXECUTE FUNCTION promo_campaigns_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS promo_campaigns_update_audit ON promo_campaigns;
CREATE TRIGGER promo_campaigns_update_audit BEFORE UPDATE ON promo_campaigns
    FOR EACH ROW EXECUTE FUNCTION promo_campaigns_audit_timestamp();

