-- Migration: Create pricing_rules table
-- Generated by metaphor-schema

-- Create rule_scope enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'rule_scope') THEN
        CREATE TYPE rule_scope AS ENUM ('line', 'order');
    END IF;
END
$$;

-- Create apply_on enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'apply_on') THEN
        CREATE TYPE apply_on AS ENUM ('item', 'item_group', 'brand', 'all');
    END IF;
END
$$;

-- Create rate_or_discount enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'rate_or_discount') THEN
        CREATE TYPE rate_or_discount AS ENUM ('rate', 'discount_percentage', 'discount_amount');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS promo;

CREATE TABLE IF NOT EXISTS promo.pricing_rules (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    title TEXT NOT NULL,
    priority INTEGER NOT NULL DEFAULT 0 CHECK (priority >= 0),
    scope rule_scope NOT NULL DEFAULT 'line',
    min_order_amount NUMERIC(18, 2) NOT NULL DEFAULT 0 CHECK (min_order_amount >= 0),
    stackable BOOLEAN NOT NULL DEFAULT FALSE,
    apply_on apply_on NOT NULL DEFAULT 'item',
    item_id UUID,
    item_group_id UUID,
    brand_id UUID,
    customer_id UUID,
    customer_group_id UUID,
    min_qty NUMERIC(18, 4) NOT NULL DEFAULT 0 CHECK (min_qty >= 0),
    max_qty NUMERIC(18, 4) CHECK (max_qty >= 0),
    min_amount NUMERIC(18, 2) NOT NULL DEFAULT 0 CHECK (min_amount >= 0),
    rate_or_discount rate_or_discount NOT NULL DEFAULT 'discount_percentage',
    rate NUMERIC(18, 2) CHECK (rate >= 0),
    discount_percentage NUMERIC(9, 4) CHECK (discount_percentage >= 0),
    discount_amount NUMERIC(18, 2) CHECK (discount_amount >= 0),
    currency TEXT NOT NULL DEFAULT 'IDR',
    valid_from TIMESTAMPTZ NOT NULL,
    valid_to TIMESTAMPTZ,
    coupon_required BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_pricing_rules_company_id_is_active_apply_on ON promo.pricing_rules (company_id, is_active, apply_on);

CREATE INDEX IF NOT EXISTS idx_pricing_rules_company_id_item_id_is_active ON promo.pricing_rules (company_id, item_id, is_active);

CREATE INDEX IF NOT EXISTS idx_pricing_rules_company_id_priority ON promo.pricing_rules (company_id, priority);

CREATE INDEX IF NOT EXISTS idx_pricing_rules_valid_from_valid_to ON promo.pricing_rules (valid_from, valid_to);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_pricing_rules_metadata_gin ON promo.pricing_rules USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_pricing_rules_metadata_deleted_at ON promo.pricing_rules ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_pricing_rules_metadata_created_at ON promo.pricing_rules ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_pricing_rules_metadata_updated_at ON promo.pricing_rules ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION promo.pricing_rules_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS pricing_rules_insert_audit ON promo.pricing_rules;
CREATE TRIGGER pricing_rules_insert_audit BEFORE INSERT ON promo.pricing_rules
    FOR EACH ROW EXECUTE FUNCTION promo.pricing_rules_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS pricing_rules_update_audit ON promo.pricing_rules;
CREATE TRIGGER pricing_rules_update_audit BEFORE UPDATE ON promo.pricing_rules
    FOR EACH ROW EXECUTE FUNCTION promo.pricing_rules_audit_timestamp();
