-- Migration: Create loyalty_programs table
-- Generated by metaphor-schema

-- Create loyalty_program_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'loyalty_program_type') THEN
        CREATE TYPE loyalty_program_type AS ENUM ('single_tier', 'multiple_tier');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS promo;

CREATE TABLE IF NOT EXISTS promo.loyalty_programs (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    program_name TEXT NOT NULL,
    program_type loyalty_program_type NOT NULL DEFAULT 'single_tier',
    collection_factor NUMERIC(18, 6) NOT NULL CHECK (collection_factor >= 0),
    conversion_factor NUMERIC(18, 6) NOT NULL CHECK (conversion_factor >= 0),
    expiry_duration_days INTEGER,
    from_date TIMESTAMPTZ NOT NULL,
    to_date TIMESTAMPTZ,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_loyalty_programs_company_id_is_active ON promo.loyalty_programs (company_id, is_active);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_loyalty_programs_metadata_gin ON promo.loyalty_programs USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_loyalty_programs_metadata_deleted_at ON promo.loyalty_programs ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_loyalty_programs_metadata_created_at ON promo.loyalty_programs ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_loyalty_programs_metadata_updated_at ON promo.loyalty_programs ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION promo.loyalty_programs_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS loyalty_programs_insert_audit ON promo.loyalty_programs;
CREATE TRIGGER loyalty_programs_insert_audit BEFORE INSERT ON promo.loyalty_programs
    FOR EACH ROW EXECUTE FUNCTION promo.loyalty_programs_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS loyalty_programs_update_audit ON promo.loyalty_programs;
CREATE TRIGGER loyalty_programs_update_audit BEFORE UPDATE ON promo.loyalty_programs
    FOR EACH ROW EXECUTE FUNCTION promo.loyalty_programs_audit_timestamp();
