-- Audit Triggers Migration for promo module
-- Generated by metaphor-schema
--
-- This migration adds automatic timestamp management triggers
-- to all tables with audit metadata fields.
--
-- Triggers automatically set:
--   - metadata->'created_at' on INSERT
--   - metadata->'updated_at' on INSERT and UPDATE

-- ==============================================================================
-- Table: CouponCode (promo.coupon_codes)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION promo.coupon_codes_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS coupon_codes_insert_audit ON promo.coupon_codes;
CREATE TRIGGER coupon_codes_insert_audit BEFORE INSERT ON promo.coupon_codes
    FOR EACH ROW EXECUTE FUNCTION promo.coupon_codes_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS coupon_codes_update_audit ON promo.coupon_codes;
CREATE TRIGGER coupon_codes_update_audit BEFORE UPDATE ON promo.coupon_codes
    FOR EACH ROW EXECUTE FUNCTION promo.coupon_codes_audit_timestamp();

-- ==============================================================================
-- Table: CouponRedemption (promo.coupon_redemptions)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION promo.coupon_redemptions_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS coupon_redemptions_insert_audit ON promo.coupon_redemptions;
CREATE TRIGGER coupon_redemptions_insert_audit BEFORE INSERT ON promo.coupon_redemptions
    FOR EACH ROW EXECUTE FUNCTION promo.coupon_redemptions_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS coupon_redemptions_update_audit ON promo.coupon_redemptions;
CREATE TRIGGER coupon_redemptions_update_audit BEFORE UPDATE ON promo.coupon_redemptions
    FOR EACH ROW EXECUTE FUNCTION promo.coupon_redemptions_audit_timestamp();

-- ==============================================================================
-- Table: LoyaltyProgram (promo.loyalty_programs)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION promo.loyalty_programs_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS loyalty_programs_insert_audit ON promo.loyalty_programs;
CREATE TRIGGER loyalty_programs_insert_audit BEFORE INSERT ON promo.loyalty_programs
    FOR EACH ROW EXECUTE FUNCTION promo.loyalty_programs_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS loyalty_programs_update_audit ON promo.loyalty_programs;
CREATE TRIGGER loyalty_programs_update_audit BEFORE UPDATE ON promo.loyalty_programs
    FOR EACH ROW EXECUTE FUNCTION promo.loyalty_programs_audit_timestamp();

-- ==============================================================================
-- Table: LoyaltyPointEntry (promo.loyalty_point_entries)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION promo.loyalty_point_entries_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS loyalty_point_entries_insert_audit ON promo.loyalty_point_entries;
CREATE TRIGGER loyalty_point_entries_insert_audit BEFORE INSERT ON promo.loyalty_point_entries
    FOR EACH ROW EXECUTE FUNCTION promo.loyalty_point_entries_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS loyalty_point_entries_update_audit ON promo.loyalty_point_entries;
CREATE TRIGGER loyalty_point_entries_update_audit BEFORE UPDATE ON promo.loyalty_point_entries
    FOR EACH ROW EXECUTE FUNCTION promo.loyalty_point_entries_audit_timestamp();

-- ==============================================================================
-- Table: PricingRule (promo.pricing_rules)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION promo.pricing_rules_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS pricing_rules_insert_audit ON promo.pricing_rules;
CREATE TRIGGER pricing_rules_insert_audit BEFORE INSERT ON promo.pricing_rules
    FOR EACH ROW EXECUTE FUNCTION promo.pricing_rules_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS pricing_rules_update_audit ON promo.pricing_rules;
CREATE TRIGGER pricing_rules_update_audit BEFORE UPDATE ON promo.pricing_rules
    FOR EACH ROW EXECUTE FUNCTION promo.pricing_rules_audit_timestamp();

-- ==============================================================================
-- Table: PromoBundle (promo.promo_bundles)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION promo.promo_bundles_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS promo_bundles_insert_audit ON promo.promo_bundles;
CREATE TRIGGER promo_bundles_insert_audit BEFORE INSERT ON promo.promo_bundles
    FOR EACH ROW EXECUTE FUNCTION promo.promo_bundles_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS promo_bundles_update_audit ON promo.promo_bundles;
CREATE TRIGGER promo_bundles_update_audit BEFORE UPDATE ON promo.promo_bundles
    FOR EACH ROW EXECUTE FUNCTION promo.promo_bundles_audit_timestamp();

-- ==============================================================================
-- Table: PromoBundleComponent (promo.promo_bundle_components)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION promo.promo_bundle_components_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS promo_bundle_components_insert_audit ON promo.promo_bundle_components;
CREATE TRIGGER promo_bundle_components_insert_audit BEFORE INSERT ON promo.promo_bundle_components
    FOR EACH ROW EXECUTE FUNCTION promo.promo_bundle_components_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS promo_bundle_components_update_audit ON promo.promo_bundle_components;
CREATE TRIGGER promo_bundle_components_update_audit BEFORE UPDATE ON promo.promo_bundle_components
    FOR EACH ROW EXECUTE FUNCTION promo.promo_bundle_components_audit_timestamp();

