-- Company RLS fence for promo module (ADR-0008)
-- Generated by metaphor-schema. Requires the app to connect as a
-- non-superuser role; migrations/seeders run as the owner and bypass.

-- Migration: company row-level-security fence for promo.coupon_codes
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE promo.coupon_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE promo.coupon_codes FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS coupon_codes_company_isolation ON promo.coupon_codes;
CREATE POLICY coupon_codes_company_isolation ON promo.coupon_codes
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for promo.coupon_redemptions
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE promo.coupon_redemptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE promo.coupon_redemptions FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS coupon_redemptions_company_isolation ON promo.coupon_redemptions;
CREATE POLICY coupon_redemptions_company_isolation ON promo.coupon_redemptions
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for promo.loyalty_programs
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE promo.loyalty_programs ENABLE ROW LEVEL SECURITY;
ALTER TABLE promo.loyalty_programs FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS loyalty_programs_company_isolation ON promo.loyalty_programs;
CREATE POLICY loyalty_programs_company_isolation ON promo.loyalty_programs
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for promo.loyalty_point_entries
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE promo.loyalty_point_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE promo.loyalty_point_entries FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS loyalty_point_entries_company_isolation ON promo.loyalty_point_entries;
CREATE POLICY loyalty_point_entries_company_isolation ON promo.loyalty_point_entries
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for promo.pricing_rules
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE promo.pricing_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE promo.pricing_rules FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS pricing_rules_company_isolation ON promo.pricing_rules;
CREATE POLICY pricing_rules_company_isolation ON promo.pricing_rules
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for promo.promo_bundles
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE promo.promo_bundles ENABLE ROW LEVEL SECURITY;
ALTER TABLE promo.promo_bundles FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS promo_bundles_company_isolation ON promo.promo_bundles;
CREATE POLICY promo_bundles_company_isolation ON promo.promo_bundles
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for promo.promo_bundle_components
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE promo.promo_bundle_components ENABLE ROW LEVEL SECURITY;
ALTER TABLE promo.promo_bundle_components FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS promo_bundle_components_company_isolation ON promo.promo_bundle_components;
CREATE POLICY promo_bundle_components_company_isolation ON promo.promo_bundle_components
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

