-- Down migration for promo module
-- Generated by backbone-schema


DROP TABLE IF EXISTS promo_campaigns CASCADE;
DROP TABLE IF EXISTS provider_promos CASCADE;
DROP TABLE IF EXISTS advertisements CASCADE;
DROP TABLE IF EXISTS ad_performances CASCADE;

DROP TYPE IF EXISTS ad_type CASCADE;
DROP TYPE IF EXISTS ad_status CASCADE;
DROP TYPE IF EXISTS ad_placement CASCADE;
DROP TYPE IF EXISTS ad_billing_model CASCADE;
DROP TYPE IF EXISTS promo_type CASCADE;
DROP TYPE IF EXISTS promo_eligibility CASCADE;
DROP TYPE IF EXISTS campaign_promo_type CASCADE;
DROP TYPE IF EXISTS campaign_status CASCADE;
DROP TYPE IF EXISTS campaign_target CASCADE;
DROP TYPE IF EXISTS campaign_funder CASCADE;
