//! Domain events for AdPerformance entity
//!
//! Generated by backbone-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::AdPerformance;

/// Domain events for AdPerformance — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<AdPerformance>)` variant.
pub type AdPerformanceEvent = CrudEvent<AdPerformance>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for AdPerformance events.
pub type AdPerformanceEventPublisher = Arc<dyn CrudEventPublisher<AdPerformance> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopAdPerformanceEventPublisher = NoOpCrudEventPublisher<AdPerformance>;
