//! Domain events for Advertisement entity
//!
//! Generated by backbone-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Advertisement;

/// Domain events for Advertisement — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Advertisement>)` variant.
pub type AdvertisementEvent = CrudEvent<Advertisement>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Advertisement events.
pub type AdvertisementEventPublisher = Arc<dyn CrudEventPublisher<Advertisement> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopAdvertisementEventPublisher = NoOpCrudEventPublisher<Advertisement>;
