//! Domain events for CouponRedemption entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::CouponRedemption;

/// Domain events for CouponRedemption — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<CouponRedemption>)` variant.
pub type CouponRedemptionEvent = CrudEvent<CouponRedemption>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for CouponRedemption events.
pub type CouponRedemptionEventPublisher = Arc<dyn CrudEventPublisher<CouponRedemption> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopCouponRedemptionEventPublisher = NoOpCrudEventPublisher<CouponRedemption>;
