//! Event handler trait for CouponCode events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::CouponCodeEvent;

/// Event handler for CouponCode events.
/// Implement this trait to react to CouponCode lifecycle events.
pub trait CouponCodeEventHandler: EventHandler<CouponCodeEvent> {}
