//! Event handler trait for CouponRedemption events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::CouponRedemptionEvent;

/// Event handler for CouponRedemption events.
/// Implement this trait to react to CouponRedemption lifecycle events.
pub trait CouponRedemptionEventHandler: EventHandler<CouponRedemptionEvent> {}
