//! Domain events for CouponCode entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::CouponCode;

/// Domain events for CouponCode — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<CouponCode>)` variant.
pub type CouponCodeEvent = CrudEvent<CouponCode>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for CouponCode events.
pub type CouponCodeEventPublisher = Arc<dyn CrudEventPublisher<CouponCode> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopCouponCodeEventPublisher = NoOpCrudEventPublisher<CouponCode>;
