//! Domain events for LoyaltyPointEntry entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::LoyaltyPointEntry;

/// Domain events for LoyaltyPointEntry — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<LoyaltyPointEntry>)` variant.
pub type LoyaltyPointEntryEvent = CrudEvent<LoyaltyPointEntry>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for LoyaltyPointEntry events.
pub type LoyaltyPointEntryEventPublisher = Arc<dyn CrudEventPublisher<LoyaltyPointEntry> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopLoyaltyPointEntryEventPublisher = NoOpCrudEventPublisher<LoyaltyPointEntry>;
