//! Domain events for LoyaltyOrderPoints entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::LoyaltyOrderPoints;

/// Domain events for LoyaltyOrderPoints — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<LoyaltyOrderPoints>)` variant.
pub type LoyaltyOrderPointsEvent = CrudEvent<LoyaltyOrderPoints>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for LoyaltyOrderPoints events.
pub type LoyaltyOrderPointsEventPublisher = Arc<dyn CrudEventPublisher<LoyaltyOrderPoints> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopLoyaltyOrderPointsEventPublisher = NoOpCrudEventPublisher<LoyaltyOrderPoints>;
