//! Event handler trait for LoyaltyOrderPoints events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::LoyaltyOrderPointsEvent;

/// Event handler for LoyaltyOrderPoints events.
/// Implement this trait to react to LoyaltyOrderPoints lifecycle events.
pub trait LoyaltyOrderPointsEventHandler: EventHandler<LoyaltyOrderPointsEvent> {}
