//! Domain events for PromoBundleGift entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::PromoBundleGift;

/// Domain events for PromoBundleGift — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<PromoBundleGift>)` variant.
pub type PromoBundleGiftEvent = CrudEvent<PromoBundleGift>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for PromoBundleGift events.
pub type PromoBundleGiftEventPublisher = Arc<dyn CrudEventPublisher<PromoBundleGift> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopPromoBundleGiftEventPublisher = NoOpCrudEventPublisher<PromoBundleGift>;
