//! Event handler trait for PromoBundleGift events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::PromoBundleGiftEvent;

/// Event handler for PromoBundleGift events.
/// Implement this trait to react to PromoBundleGift lifecycle events.
pub trait PromoBundleGiftEventHandler: EventHandler<PromoBundleGiftEvent> {}
