//! Event handler trait for PromoBundleComponent events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::PromoBundleComponentEvent;

/// Event handler for PromoBundleComponent events.
/// Implement this trait to react to PromoBundleComponent lifecycle events.
pub trait PromoBundleComponentEventHandler: EventHandler<PromoBundleComponentEvent> {}
