//! Domain events for PromoBundle entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::PromoBundle;

/// Domain events for PromoBundle — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<PromoBundle>)` variant.
pub type PromoBundleEvent = CrudEvent<PromoBundle>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for PromoBundle events.
pub type PromoBundleEventPublisher = Arc<dyn CrudEventPublisher<PromoBundle> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopPromoBundleEventPublisher = NoOpCrudEventPublisher<PromoBundle>;
