//! Event handler trait for ProviderPromo events
//!
//! Generated by backbone-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::ProviderPromoEvent;

/// Event handler for ProviderPromo events.
/// Implement this trait to react to ProviderPromo lifecycle events.
pub trait ProviderPromoEventHandler: EventHandler<ProviderPromoEvent> {}
