//! Event subscriber type aliases for Promo module
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::GenericEventSubscriber;

use crate::domain::event::CouponCodeEvent;
use crate::domain::event::CouponRedemptionEvent;
use crate::domain::event::LoyaltyProgramEvent;
use crate::domain::event::LoyaltyPointEntryEvent;
use crate::domain::event::PricingRuleEvent;
use crate::domain::event::PromoBundleEvent;
use crate::domain::event::PromoBundleComponentEvent;

/// Subscriber for CouponCode events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type CouponCodeEventSubscriber = GenericEventSubscriber<CouponCodeEvent>;

/// Subscriber for CouponRedemption events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type CouponRedemptionEventSubscriber = GenericEventSubscriber<CouponRedemptionEvent>;

/// Subscriber for LoyaltyProgram events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type LoyaltyProgramEventSubscriber = GenericEventSubscriber<LoyaltyProgramEvent>;

/// Subscriber for LoyaltyPointEntry events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type LoyaltyPointEntryEventSubscriber = GenericEventSubscriber<LoyaltyPointEntryEvent>;

/// Subscriber for PricingRule events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type PricingRuleEventSubscriber = GenericEventSubscriber<PricingRuleEvent>;

/// Subscriber for PromoBundle events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type PromoBundleEventSubscriber = GenericEventSubscriber<PromoBundleEvent>;

/// Subscriber for PromoBundleComponent events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type PromoBundleComponentEventSubscriber = GenericEventSubscriber<PromoBundleComponentEvent>;

// <<< CUSTOM
// END CUSTOM
