//! Event subscriber type aliases for Promo module
//!
//! Generated by backbone-schema. Do not edit manually.

use backbone_messaging::GenericEventSubscriber;

use crate::domain::event::AdPerformanceEvent;
use crate::domain::event::AdvertisementEvent;
use crate::domain::event::ProviderPromoEvent;
use crate::domain::event::PromoCampaignEvent;

/// Subscriber for AdPerformance events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type AdPerformanceEventSubscriber = GenericEventSubscriber<AdPerformanceEvent>;

/// Subscriber for Advertisement events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type AdvertisementEventSubscriber = GenericEventSubscriber<AdvertisementEvent>;

/// Subscriber for ProviderPromo events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type ProviderPromoEventSubscriber = GenericEventSubscriber<ProviderPromoEvent>;

/// Subscriber for PromoCampaign events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type PromoCampaignEventSubscriber = GenericEventSubscriber<PromoCampaignEvent>;

// <<< CUSTOM
// END CUSTOM
