//! CouponRedemption seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial CouponRedemption data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// COUPONREDEMPTION SEEDER
// ============================================================================

/// Seeder for coupon_redemption
pub struct SeedCouponRedemptionSeeder;

impl SeedCouponRedemptionSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedCouponRedemptionSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedCouponRedemptionSeeder {
    fn name(&self) -> &'static str {
        "SeedCouponRedemptionSeeder"
    }

    fn order(&self) -> i32 {
        2
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if promo.coupon_redemptions table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM promo.coupon_redemptions")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/coupon_redemption_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM promo.coupon_redemptions")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

