//! LoyaltyPointEntry seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial LoyaltyPointEntry data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// LOYALTYPOINTENTRY SEEDER
// ============================================================================

/// Seeder for loyalty_point_entry
pub struct SeedLoyaltyPointEntrySeeder;

impl SeedLoyaltyPointEntrySeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedLoyaltyPointEntrySeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedLoyaltyPointEntrySeeder {
    fn name(&self) -> &'static str {
        "SeedLoyaltyPointEntrySeeder"
    }

    fn order(&self) -> i32 {
        4
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if promo.loyalty_point_entries table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM promo.loyalty_point_entries")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/loyalty_point_entry_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM promo.loyalty_point_entries")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

