//! PricingRule seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial PricingRule data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// PRICINGRULE SEEDER
// ============================================================================

/// Seeder for pricing_rule
pub struct SeedPricingRuleSeeder;

impl SeedPricingRuleSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedPricingRuleSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedPricingRuleSeeder {
    fn name(&self) -> &'static str {
        "SeedPricingRuleSeeder"
    }

    fn order(&self) -> i32 {
        5
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if promo.pricing_rules table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM promo.pricing_rules")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/pricing_rule_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM promo.pricing_rules")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

