//! PromoBundleComponent seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial PromoBundleComponent data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// PROMOBUNDLECOMPONENT SEEDER
// ============================================================================

/// Seeder for promo_bundle_component
pub struct SeedPromoBundleComponentSeeder;

impl SeedPromoBundleComponentSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedPromoBundleComponentSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedPromoBundleComponentSeeder {
    fn name(&self) -> &'static str {
        "SeedPromoBundleComponentSeeder"
    }

    fn order(&self) -> i32 {
        7
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if promo.promo_bundle_components table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM promo.promo_bundle_components")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/promo_bundle_component_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM promo.promo_bundle_components")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

