//! PromoCampaign seeder
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Seeds initial PromoCampaign data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// PROMOCAMPAIGN SEEDER
// ============================================================================

/// Seeder for promo_campaign
pub struct SeedPromoCampaignSeeder;

impl SeedPromoCampaignSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedPromoCampaignSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedPromoCampaignSeeder {
    fn name(&self) -> &'static str {
        "SeedPromoCampaignSeeder"
    }

    fn order(&self) -> i32 {
        4
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if promo_campaigns table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM promo_campaigns")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/promo_campaign_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM promo_campaigns")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

