//! PromoBundleGift seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial PromoBundleGift data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// PROMOBUNDLEGIFT SEEDER
// ============================================================================

/// Seeder for promo_bundle_gift
pub struct SeedPromoBundleGiftSeeder;

impl SeedPromoBundleGiftSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedPromoBundleGiftSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedPromoBundleGiftSeeder {
    fn name(&self) -> &'static str {
        "SeedPromoBundleGiftSeeder"
    }

    fn order(&self) -> i32 {
        9
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if promo.promo_bundle_gifts table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM promo.promo_bundle_gifts")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/promo_bundle_gift_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM promo.promo_bundle_gifts")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>
