//! ProviderPromo seeder
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Seeds initial ProviderPromo data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// PROVIDERPROMO SEEDER
// ============================================================================

/// Seeder for provider_promo
pub struct SeedProviderPromoSeeder;

impl SeedProviderPromoSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedProviderPromoSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedProviderPromoSeeder {
    fn name(&self) -> &'static str {
        "SeedProviderPromoSeeder"
    }

    fn order(&self) -> i32 {
        3
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if provider_promos table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM provider_promos")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/provider_promo_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM provider_promos")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

