//! Repository trait for CouponCode aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the CouponCode aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::CouponCode;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct CouponCodePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl CouponCodePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct CouponCodePaginatedResult {
    pub data: Vec<CouponCode>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct CouponCodeFilter {
    pub company_id: Option<Uuid>,
    pub code: Option<String>,
    pub pricing_rule_id: Option<Uuid>,
    pub description: Option<String>,
    pub is_active: Option<bool>,
}

impl CouponCodeFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.code.is_some() || self.pricing_rule_id.is_some() || self.description.is_some() || self.is_active.is_some()
    }
}

/// Repository trait for CouponCode aggregate
///
/// This trait defines the persistence contract for CouponCode entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait CouponCodeRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new coupon_code entity
    async fn save(&self, entity: &CouponCode) -> Result<CouponCode>;

    /// Find coupon_code by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<CouponCode>>;

    /// Find all coupon_code entities
    async fn find_all(&self) -> Result<Vec<CouponCode>>;

    /// Update coupon_code by ID
    async fn update(&self, id: &str, entity: &CouponCode) -> Result<Option<CouponCode>>;

    /// Delete coupon_code by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List coupon_code with pagination
    async fn list(&self, params: CouponCodePaginationParams) -> Result<CouponCodePaginatedResult>;

    /// List coupon_code with pagination and filters
    async fn list_with_filters(&self, params: CouponCodePaginationParams, filters: CouponCodeFilter) -> Result<CouponCodePaginatedResult>;

    /// Count all coupon_code entities
    async fn count(&self) -> Result<u64>;

    /// Count coupon_code entities matching filters
    async fn count_with_filters(&self, filters: CouponCodeFilter) -> Result<u64>;

    /// Check if coupon_code exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete coupon_code by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted coupon_code by ID
    async fn restore(&self, id: &str) -> Result<Option<CouponCode>>;

    /// List soft-deleted coupon_code entities
    async fn list_deleted(&self, params: CouponCodePaginationParams) -> Result<CouponCodePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save coupon_code entities
    async fn bulk_save(&self, entities: &[CouponCode]) -> Result<Vec<CouponCode>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
