//! Repository trait for CouponRedemption aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the CouponRedemption aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::CouponRedemption;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct CouponRedemptionPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl CouponRedemptionPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct CouponRedemptionPaginatedResult {
    pub data: Vec<CouponRedemption>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct CouponRedemptionFilter {
    pub company_id: Option<Uuid>,
    pub coupon_id: Option<Uuid>,
    pub pricing_rule_id: Option<Uuid>,
    pub source_type: Option<String>,
    pub source_id: Option<Uuid>,
}

impl CouponRedemptionFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.coupon_id.is_some() || self.pricing_rule_id.is_some() || self.source_type.is_some() || self.source_id.is_some()
    }
}

/// Repository trait for CouponRedemption aggregate
///
/// This trait defines the persistence contract for CouponRedemption entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait CouponRedemptionRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new coupon_redemption entity
    async fn save(&self, entity: &CouponRedemption) -> Result<CouponRedemption>;

    /// Find coupon_redemption by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<CouponRedemption>>;

    /// Find all coupon_redemption entities
    async fn find_all(&self) -> Result<Vec<CouponRedemption>>;

    /// Update coupon_redemption by ID
    async fn update(&self, id: &str, entity: &CouponRedemption) -> Result<Option<CouponRedemption>>;

    /// Delete coupon_redemption by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List coupon_redemption with pagination
    async fn list(&self, params: CouponRedemptionPaginationParams) -> Result<CouponRedemptionPaginatedResult>;

    /// List coupon_redemption with pagination and filters
    async fn list_with_filters(&self, params: CouponRedemptionPaginationParams, filters: CouponRedemptionFilter) -> Result<CouponRedemptionPaginatedResult>;

    /// Count all coupon_redemption entities
    async fn count(&self) -> Result<u64>;

    /// Count coupon_redemption entities matching filters
    async fn count_with_filters(&self, filters: CouponRedemptionFilter) -> Result<u64>;

    /// Check if coupon_redemption exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete coupon_redemption by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted coupon_redemption by ID
    async fn restore(&self, id: &str) -> Result<Option<CouponRedemption>>;

    /// List soft-deleted coupon_redemption entities
    async fn list_deleted(&self, params: CouponRedemptionPaginationParams) -> Result<CouponRedemptionPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save coupon_redemption entities
    async fn bulk_save(&self, entities: &[CouponRedemption]) -> Result<Vec<CouponRedemption>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
