//! Repository trait for LoyaltyOrderPoints aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the LoyaltyOrderPoints aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::LoyaltyOrderPoints;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct LoyaltyOrderPointsPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl LoyaltyOrderPointsPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct LoyaltyOrderPointsPaginatedResult {
    pub data: Vec<LoyaltyOrderPoints>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct LoyaltyOrderPointsFilter {
    pub company_id: Option<Uuid>,
    pub loyalty_program_id: Option<Uuid>,
    pub customer_id: Option<Uuid>,
    pub order_ref_type: Option<String>,
    pub order_ref_id: Option<Uuid>,
    pub coupon_code_id: Option<Uuid>,
}

impl LoyaltyOrderPointsFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.loyalty_program_id.is_some() || self.customer_id.is_some() || self.order_ref_type.is_some() || self.order_ref_id.is_some() || self.coupon_code_id.is_some()
    }
}

/// Repository trait for LoyaltyOrderPoints aggregate
///
/// This trait defines the persistence contract for LoyaltyOrderPoints entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait LoyaltyOrderPointsRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new loyalty_order_points entity
    async fn save(&self, entity: &LoyaltyOrderPoints) -> Result<LoyaltyOrderPoints>;

    /// Find loyalty_order_points by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<LoyaltyOrderPoints>>;

    /// Find all loyalty_order_points entities
    async fn find_all(&self) -> Result<Vec<LoyaltyOrderPoints>>;

    /// Update loyalty_order_points by ID
    async fn update(&self, id: &str, entity: &LoyaltyOrderPoints) -> Result<Option<LoyaltyOrderPoints>>;

    /// Delete loyalty_order_points by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List loyalty_order_points with pagination
    async fn list(&self, params: LoyaltyOrderPointsPaginationParams) -> Result<LoyaltyOrderPointsPaginatedResult>;

    /// List loyalty_order_points with pagination and filters
    async fn list_with_filters(&self, params: LoyaltyOrderPointsPaginationParams, filters: LoyaltyOrderPointsFilter) -> Result<LoyaltyOrderPointsPaginatedResult>;

    /// Count all loyalty_order_points entities
    async fn count(&self) -> Result<u64>;

    /// Count loyalty_order_points entities matching filters
    async fn count_with_filters(&self, filters: LoyaltyOrderPointsFilter) -> Result<u64>;

    /// Check if loyalty_order_points exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete loyalty_order_points by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted loyalty_order_points by ID
    async fn restore(&self, id: &str) -> Result<Option<LoyaltyOrderPoints>>;

    /// List soft-deleted loyalty_order_points entities
    async fn list_deleted(&self, params: LoyaltyOrderPointsPaginationParams) -> Result<LoyaltyOrderPointsPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save loyalty_order_points entities
    async fn bulk_save(&self, entities: &[LoyaltyOrderPoints]) -> Result<Vec<LoyaltyOrderPoints>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
