//! Repository traits
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! DDD Repository traits - define persistence contracts for aggregates.
//! Implementations should be in the infrastructure layer.


pub mod ad_performance_repository;
pub mod advertisement_repository;
pub mod provider_promo_repository;
pub mod promo_campaign_repository;

// Re-exports
pub use ad_performance_repository::{
    AdPerformanceRepository,
    AdPerformancePaginationParams,
    AdPerformancePaginatedResult,
    AdPerformanceFilter,
};
pub use advertisement_repository::{
    AdvertisementRepository,
    AdvertisementPaginationParams,
    AdvertisementPaginatedResult,
    AdvertisementFilter,
};
pub use provider_promo_repository::{
    ProviderPromoRepository,
    ProviderPromoPaginationParams,
    ProviderPromoPaginatedResult,
    ProviderPromoFilter,
};
pub use promo_campaign_repository::{
    PromoCampaignRepository,
    PromoCampaignPaginationParams,
    PromoCampaignPaginatedResult,
    PromoCampaignFilter,
};
