//! Repository traits
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DDD Repository traits - define persistence contracts for aggregates.
//! Implementations should be in the infrastructure layer.


pub mod coupon_code_repository;
pub mod coupon_redemption_repository;
pub mod loyalty_program_repository;
pub mod loyalty_point_entry_repository;
pub mod pricing_rule_repository;
pub mod promo_bundle_repository;
pub mod promo_bundle_component_repository;

// Re-exports
pub use coupon_code_repository::{
    CouponCodeRepository,
    CouponCodePaginationParams,
    CouponCodePaginatedResult,
    CouponCodeFilter,
};
pub use coupon_redemption_repository::{
    CouponRedemptionRepository,
    CouponRedemptionPaginationParams,
    CouponRedemptionPaginatedResult,
    CouponRedemptionFilter,
};
pub use loyalty_program_repository::{
    LoyaltyProgramRepository,
    LoyaltyProgramPaginationParams,
    LoyaltyProgramPaginatedResult,
    LoyaltyProgramFilter,
};
pub use loyalty_point_entry_repository::{
    LoyaltyPointEntryRepository,
    LoyaltyPointEntryPaginationParams,
    LoyaltyPointEntryPaginatedResult,
    LoyaltyPointEntryFilter,
};
pub use pricing_rule_repository::{
    PricingRuleRepository,
    PricingRulePaginationParams,
    PricingRulePaginatedResult,
    PricingRuleFilter,
};
pub use promo_bundle_repository::{
    PromoBundleRepository,
    PromoBundlePaginationParams,
    PromoBundlePaginatedResult,
    PromoBundleFilter,
};
pub use promo_bundle_component_repository::{
    PromoBundleComponentRepository,
    PromoBundleComponentPaginationParams,
    PromoBundleComponentPaginatedResult,
    PromoBundleComponentFilter,
};
