//! Repository trait for PricingRule aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the PricingRule aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{PricingRule, ApplyOn, RateOrDiscount};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PricingRulePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl PricingRulePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct PricingRulePaginatedResult {
    pub data: Vec<PricingRule>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PricingRuleFilter {
    pub company_id: Option<Uuid>,
    pub title: Option<String>,
    pub apply_on: Option<ApplyOn>,
    pub item_id: Option<Uuid>,
    pub item_group_id: Option<Uuid>,
    pub brand_id: Option<Uuid>,
    pub customer_id: Option<Uuid>,
    pub customer_group_id: Option<Uuid>,
    pub rate_or_discount: Option<RateOrDiscount>,
    pub currency: Option<String>,
    pub coupon_required: Option<bool>,
    pub is_active: Option<bool>,
}

impl PricingRuleFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.title.is_some() || self.apply_on.is_some() || self.item_id.is_some() || self.item_group_id.is_some() || self.brand_id.is_some() || self.customer_id.is_some() || self.customer_group_id.is_some() || self.rate_or_discount.is_some() || self.currency.is_some() || self.coupon_required.is_some() || self.is_active.is_some()
    }
}

/// Repository trait for PricingRule aggregate
///
/// This trait defines the persistence contract for PricingRule entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait PricingRuleRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new pricing_rule entity
    async fn save(&self, entity: &PricingRule) -> Result<PricingRule>;

    /// Find pricing_rule by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<PricingRule>>;

    /// Find all pricing_rule entities
    async fn find_all(&self) -> Result<Vec<PricingRule>>;

    /// Update pricing_rule by ID
    async fn update(&self, id: &str, entity: &PricingRule) -> Result<Option<PricingRule>>;

    /// Delete pricing_rule by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List pricing_rule with pagination
    async fn list(&self, params: PricingRulePaginationParams) -> Result<PricingRulePaginatedResult>;

    /// List pricing_rule with pagination and filters
    async fn list_with_filters(&self, params: PricingRulePaginationParams, filters: PricingRuleFilter) -> Result<PricingRulePaginatedResult>;

    /// Count all pricing_rule entities
    async fn count(&self) -> Result<u64>;

    /// Count pricing_rule entities matching filters
    async fn count_with_filters(&self, filters: PricingRuleFilter) -> Result<u64>;

    /// Check if pricing_rule exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete pricing_rule by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted pricing_rule by ID
    async fn restore(&self, id: &str) -> Result<Option<PricingRule>>;

    /// List soft-deleted pricing_rule entities
    async fn list_deleted(&self, params: PricingRulePaginationParams) -> Result<PricingRulePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save pricing_rule entities
    async fn bulk_save(&self, entities: &[PricingRule]) -> Result<Vec<PricingRule>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
