//! Repository trait for PromoBundleComponent aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the PromoBundleComponent aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{PromoBundleComponent, ApplyOn};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PromoBundleComponentPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl PromoBundleComponentPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct PromoBundleComponentPaginatedResult {
    pub data: Vec<PromoBundleComponent>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PromoBundleComponentFilter {
    pub company_id: Option<Uuid>,
    pub bundle_id: Option<Uuid>,
    pub apply_on: Option<ApplyOn>,
    pub item_id: Option<Uuid>,
    pub item_group_id: Option<Uuid>,
    pub brand_id: Option<Uuid>,
}

impl PromoBundleComponentFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.bundle_id.is_some() || self.apply_on.is_some() || self.item_id.is_some() || self.item_group_id.is_some() || self.brand_id.is_some()
    }
}

/// Repository trait for PromoBundleComponent aggregate
///
/// This trait defines the persistence contract for PromoBundleComponent entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait PromoBundleComponentRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new promo_bundle_component entity
    async fn save(&self, entity: &PromoBundleComponent) -> Result<PromoBundleComponent>;

    /// Find promo_bundle_component by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<PromoBundleComponent>>;

    /// Find all promo_bundle_component entities
    async fn find_all(&self) -> Result<Vec<PromoBundleComponent>>;

    /// Update promo_bundle_component by ID
    async fn update(&self, id: &str, entity: &PromoBundleComponent) -> Result<Option<PromoBundleComponent>>;

    /// Delete promo_bundle_component by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List promo_bundle_component with pagination
    async fn list(&self, params: PromoBundleComponentPaginationParams) -> Result<PromoBundleComponentPaginatedResult>;

    /// List promo_bundle_component with pagination and filters
    async fn list_with_filters(&self, params: PromoBundleComponentPaginationParams, filters: PromoBundleComponentFilter) -> Result<PromoBundleComponentPaginatedResult>;

    /// Count all promo_bundle_component entities
    async fn count(&self) -> Result<u64>;

    /// Count promo_bundle_component entities matching filters
    async fn count_with_filters(&self, filters: PromoBundleComponentFilter) -> Result<u64>;

    /// Check if promo_bundle_component exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete promo_bundle_component by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted promo_bundle_component by ID
    async fn restore(&self, id: &str) -> Result<Option<PromoBundleComponent>>;

    /// List soft-deleted promo_bundle_component entities
    async fn list_deleted(&self, params: PromoBundleComponentPaginationParams) -> Result<PromoBundleComponentPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save promo_bundle_component entities
    async fn bulk_save(&self, entities: &[PromoBundleComponent]) -> Result<Vec<PromoBundleComponent>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
