//! Repository trait for PromoBundleGift aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the PromoBundleGift aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::PromoBundleGift;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PromoBundleGiftPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl PromoBundleGiftPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct PromoBundleGiftPaginatedResult {
    pub data: Vec<PromoBundleGift>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PromoBundleGiftFilter {
    pub company_id: Option<Uuid>,
    pub bundle_id: Option<Uuid>,
    pub gift_item_id: Option<Uuid>,
}

impl PromoBundleGiftFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.bundle_id.is_some() || self.gift_item_id.is_some()
    }
}

/// Repository trait for PromoBundleGift aggregate
///
/// This trait defines the persistence contract for PromoBundleGift entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait PromoBundleGiftRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new promo_bundle_gift entity
    async fn save(&self, entity: &PromoBundleGift) -> Result<PromoBundleGift>;

    /// Find promo_bundle_gift by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<PromoBundleGift>>;

    /// Find all promo_bundle_gift entities
    async fn find_all(&self) -> Result<Vec<PromoBundleGift>>;

    /// Update promo_bundle_gift by ID
    async fn update(&self, id: &str, entity: &PromoBundleGift) -> Result<Option<PromoBundleGift>>;

    /// Delete promo_bundle_gift by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List promo_bundle_gift with pagination
    async fn list(&self, params: PromoBundleGiftPaginationParams) -> Result<PromoBundleGiftPaginatedResult>;

    /// List promo_bundle_gift with pagination and filters
    async fn list_with_filters(&self, params: PromoBundleGiftPaginationParams, filters: PromoBundleGiftFilter) -> Result<PromoBundleGiftPaginatedResult>;

    /// Count all promo_bundle_gift entities
    async fn count(&self) -> Result<u64>;

    /// Count promo_bundle_gift entities matching filters
    async fn count_with_filters(&self, filters: PromoBundleGiftFilter) -> Result<u64>;

    /// Check if promo_bundle_gift exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete promo_bundle_gift by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted promo_bundle_gift by ID
    async fn restore(&self, id: &str) -> Result<Option<PromoBundleGift>>;

    /// List soft-deleted promo_bundle_gift entities
    async fn list_deleted(&self, params: PromoBundleGiftPaginationParams) -> Result<PromoBundleGiftPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save promo_bundle_gift entities
    async fn bulk_save(&self, entities: &[PromoBundleGift]) -> Result<Vec<PromoBundleGift>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
