//! Repository for CouponRedemption entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<CouponRedemption, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::CouponRedemption;

/// Table name for CouponRedemption entities
pub const TABLE_NAME: &str = "promo.coupon_redemptions";

/// Repository for CouponRedemption entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct CouponRedemptionRepository(
    backbone_orm::GenericCrudRepository<CouponRedemption, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for CouponRedemptionRepository {
    type Target = backbone_orm::GenericCrudRepository<CouponRedemption, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl CouponRedemptionRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(CouponRedemptionRepository, CouponRedemption, soft_delete);
