//! Repository for CouponRedemption entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written CouponRedemption SQL (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<CouponRedemption, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use rust_decimal::Decimal;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use crate::domain::entity::CouponRedemption;

/// Table name for CouponRedemption entities
pub const TABLE_NAME: &str = "promo.coupon_redemptions";

/// Repository for CouponRedemption entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct CouponRedemptionRepository(
    backbone_orm::GenericCrudRepository<CouponRedemption, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for CouponRedemptionRepository {
    type Target = backbone_orm::GenericCrudRepository<CouponRedemption, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl CouponRedemptionRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// Hand-written CouponRedemption SQL. Lives here (not in the write service) per the module's 4-layer
/// rule: services orchestrate and own the unit of work, repositories hold the SQL.
impl CouponRedemptionRepository {
    /// Claim the (coupon, source_type, source_id) redemption slot exactly once, selecting the
    /// coupon's own `pricing_rule_id` into the ledger row. `Ok(None)` = this source already redeemed (a
    /// replay), and the caller must NOT burn a second use — it re-reads via [`Self::find_existing`].
    ///
    /// Arbitration is SELECT-first: the module's own chain no longer carries the
    /// one-redemption-per-source unique (the composing service's decorator re-declares it
    /// org-scoped, ADR-0029), so an insert-conflict cannot be the gate on an undecorated
    /// database. The caller's NOWAIT coupon-row lock serializes writers for one coupon; the
    /// read decides replay vs fresh, and the insert's untargeted `ON CONFLICT DO NOTHING`
    /// stays as the decorated-database belt (the decorator's unique is unnamed-able by the
    /// module — no conflict target).
    ///
    /// Takes the CALLER'S connection so this and the guarded counter bump commit as one unit (an
    /// exhausted coupon rolls the claim back).
    pub async fn claim(
        &self,
        conn: &mut sqlx::PgConnection,
        coupon_id: Uuid,
        source_type: &str,
        source_id: Uuid,
    ) -> Result<Option<Uuid>, sqlx::Error> {
        let existing = sqlx::query_scalar::<_, Uuid>(
            r#"SELECT pricing_rule_id FROM promo.coupon_redemptions
               WHERE coupon_id = $1 AND source_type = $2 AND source_id = $3
                 AND (metadata->>'deleted_at') IS NULL"#,
        )
        .bind(coupon_id)
        .bind(source_type)
        .bind(source_id)
        .fetch_optional(&mut *conn)
        .await?;
        if existing.is_some() {
            return Ok(None);
        }
        let row = sqlx::query(
            r#"
            INSERT INTO promo.coupon_redemptions (coupon_id, pricing_rule_id,
                source_type, source_id)
            SELECT $1, c.pricing_rule_id, $2, $3
            FROM promo.coupon_codes c
            WHERE c.id = $1
            ON CONFLICT DO NOTHING
            RETURNING pricing_rule_id
            "#,
        )
        .bind(coupon_id)
        .bind(source_type)
        .bind(source_id)
        .fetch_optional(conn)
        .await?;
        Ok(row.map(|r| r.get("pricing_rule_id")))
    }

    /// The rule a replayed source already redeemed. Errors if absent — a losing claim proves the row
    /// exists, so this is `fetch_one`, not an optional read. Same caller-owned-tx contract as
    /// [`Self::claim`].
    pub async fn find_existing(
        &self,
        conn: &mut sqlx::PgConnection,
        coupon_id: Uuid,
        source_type: &str,
        source_id: Uuid,
    ) -> Result<Uuid, sqlx::Error> {
        sqlx::query_scalar(
            r#"SELECT pricing_rule_id FROM promo.coupon_redemptions
               WHERE coupon_id = $1 AND source_type = $2 AND source_id = $3
                 AND (metadata->>'deleted_at') IS NULL"#,
        )
        .bind(coupon_id)
        .bind(source_type)
        .bind(source_id)
        .fetch_one(conn)
        .await
    }
}

backbone_core::impl_crud_repository!(CouponRedemptionRepository, CouponRedemption, soft_delete);
