//! Repository for CouponCode entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<CouponCode, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::CouponCode;

/// Table name for CouponCode entities
pub const TABLE_NAME: &str = "promo.coupon_codes";

/// Repository for CouponCode entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct CouponCodeRepository(
    backbone_orm::GenericCrudRepository<CouponCode, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for CouponCodeRepository {
    type Target = backbone_orm::GenericCrudRepository<CouponCode, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl CouponCodeRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(CouponCodeRepository, CouponCode, soft_delete);
