//! Repository for LoyaltyPointEntry entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written LoyaltyPointEntry SQL (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<LoyaltyPointEntry, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use rust_decimal::Decimal;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::LoyaltyPointEntry;

/// Table name for LoyaltyPointEntry entities
pub const TABLE_NAME: &str = "promo.loyalty_point_entries";

/// Repository for LoyaltyPointEntry entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct LoyaltyPointEntryRepository(
    backbone_orm::GenericCrudRepository<LoyaltyPointEntry, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for LoyaltyPointEntryRepository {
    type Target = backbone_orm::GenericCrudRepository<LoyaltyPointEntry, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl LoyaltyPointEntryRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row an accrual writes. Mirrors the raw column shape rather than the `LoyaltyPointEntry`
/// entity; `entry_type` is the literal `'earned'` in the SQL. `points` is whole (floored by the
/// caller) and is NOT money; `purchase_amount` is expected already money-rounded.
pub struct NewAccrualRow<'a> {
    pub company_id: Uuid,
    pub loyalty_program_id: Uuid,
    pub customer_id: Uuid,
    pub points: Decimal,
    pub purchase_amount: Decimal,
    pub source_type: &'a str,
    pub source_id: Uuid,
    pub at: chrono::DateTime<chrono::Utc>,
    pub expiry: Option<chrono::DateTime<chrono::Utc>>,
}

/// The exact row a redemption writes. `points` is stored NEGATIVE (the ledger is signed, so the
/// balance is a plain SUM) and `purchase_amount` is the literal `0` in the SQL.
pub struct NewRedemptionRow<'a> {
    pub company_id: Uuid,
    pub loyalty_program_id: Uuid,
    pub customer_id: Uuid,
    /// Already negated by the caller.
    pub points: Decimal,
    pub source_type: &'a str,
    pub source_id: Uuid,
    pub at: chrono::DateTime<chrono::Utc>,
}

/// A prior redemption found on replay — its `points` are the stored (negative) value.
pub struct PriorRedemptionRow {
    pub id: Uuid,
    pub points: Decimal,
}

/// Hand-written LoyaltyPointEntry SQL. Lives here (not in the write service) per the module's 4-layer
/// rule: services orchestrate and own the unit of work, repositories hold the SQL.
impl LoyaltyPointEntryRepository {
    /// Claim the `(company, source_type, source_id, earned)` accrual slot. `Ok(None)` = this document
    /// already earned (a replayed paid event) — one document earns at most once, however many times the
    /// event is redelivered.
    ///
    /// RLS scope (ADR-0008): company on the accrual request — the caller wraps this in
    /// `with_company_scope(Some(company_id))` so the INSERT passes the WITH CHECK fence (accrual is
    /// event-driven and has no ambient scope of its own).
    pub async fn claim_accrual(
        &self,
        pool: &PgPool,
        a: &NewAccrualRow<'_>,
    ) -> Result<Option<Uuid>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"
                INSERT INTO promo.loyalty_point_entries
                    (company_id, loyalty_program_id, customer_id, entry_type, points, purchase_amount,
                     source_type, source_id, posting_date, expiry_date)
                VALUES ($1, $2, $3, 'earned', $4, $5, $6, $7, $8, $9)
                ON CONFLICT (company_id, source_type, source_id, entry_type)
                    WHERE (metadata->>'deleted_at') IS NULL
                DO NOTHING
                RETURNING id
                "#,
            )
            .bind(a.company_id)
            .bind(a.loyalty_program_id)
            .bind(a.customer_id)
            .bind(a.points)
            .bind(a.purchase_amount)
            .bind(a.source_type)
            .bind(a.source_id)
            .bind(a.at)
            .bind(a.expiry),
        )
        .await?;
        Ok(row.map(|r| r.get("id")))
    }

    /// Serialize every balance-changing op for one (company, customer, program) — the lock that stops
    /// concurrent redemptions overselling the balance. Transaction-scoped: it releases on commit or
    /// rollback, so the caller never unlocks explicitly.
    ///
    /// Takes the CALLER'S connection — the lock is worthless on any other. The caller has already bound
    /// the company on it (`bind_company_on`) — don't re-bind here.
    pub async fn lock_member_balance(
        &self,
        conn: &mut sqlx::PgConnection,
        company_id: Uuid,
        customer_id: Uuid,
        loyalty_program_id: Uuid,
    ) -> Result<(), sqlx::Error> {
        let lock_key = format!("{company_id}:{customer_id}:{loyalty_program_id}");
        sqlx::query("SELECT pg_advisory_xact_lock(hashtextextended($1, 0))")
            .bind(&lock_key)
            .execute(conn)
            .await?;
        Ok(())
    }

    /// A prior `redeemed` entry for this exact source, if any — the idempotent-replay short-circuit.
    /// Same caller-owned-tx contract as [`Self::lock_member_balance`].
    pub async fn find_redemption_by_source(
        &self,
        conn: &mut sqlx::PgConnection,
        company_id: Uuid,
        source_type: &str,
        source_id: Uuid,
    ) -> Result<Option<PriorRedemptionRow>, sqlx::Error> {
        let row = sqlx::query(
            r#"SELECT id, points FROM promo.loyalty_point_entries
               WHERE company_id = $1 AND source_type = $2 AND source_id = $3 AND entry_type = 'redeemed'
                 AND (metadata->>'deleted_at') IS NULL"#,
        )
        .bind(company_id)
        .bind(source_type)
        .bind(source_id)
        .fetch_optional(conn)
        .await?;
        Ok(row.map(|r| PriorRedemptionRow { id: r.get("id"), points: r.get("points") }))
    }

    /// The member's balance: Σ signed points (earned +, redeemed/expired −). Read under the advisory
    /// lock, so it cannot be raced. Same caller-owned-tx contract as [`Self::lock_member_balance`].
    pub async fn available_balance(
        &self,
        conn: &mut sqlx::PgConnection,
        company_id: Uuid,
        customer_id: Uuid,
        loyalty_program_id: Uuid,
    ) -> Result<Decimal, sqlx::Error> {
        sqlx::query_scalar(
            r#"SELECT COALESCE(SUM(points), 0) FROM promo.loyalty_point_entries
               WHERE company_id = $1 AND customer_id = $2 AND loyalty_program_id = $3
                 AND (metadata->>'deleted_at') IS NULL"#,
        )
        .bind(company_id)
        .bind(customer_id)
        .bind(loyalty_program_id)
        .fetch_one(conn)
        .await
    }

    /// Write the redemption entry. The caller has already checked it against the balance under the
    /// lock. Same caller-owned-tx contract as [`Self::lock_member_balance`].
    pub async fn insert_redemption(
        &self,
        conn: &mut sqlx::PgConnection,
        r: &NewRedemptionRow<'_>,
    ) -> Result<Uuid, sqlx::Error> {
        sqlx::query_scalar(
            r#"
            INSERT INTO promo.loyalty_point_entries
                (company_id, loyalty_program_id, customer_id, entry_type, points, purchase_amount,
                 source_type, source_id, posting_date)
            VALUES ($1, $2, $3, 'redeemed', $4, 0, $5, $6, $7)
            RETURNING id
            "#,
        )
        .bind(r.company_id)
        .bind(r.loyalty_program_id)
        .bind(r.customer_id)
        .bind(r.points)
        .bind(r.source_type)
        .bind(r.source_id)
        .bind(r.at)
        .fetch_one(conn)
        .await
    }
}

backbone_core::impl_crud_repository!(LoyaltyPointEntryRepository, LoyaltyPointEntry, soft_delete);
