//! Repository for PricingRule entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<PricingRule, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::PricingRule;

/// Table name for PricingRule entities
pub const TABLE_NAME: &str = "promo.pricing_rules";

/// Repository for PricingRule entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct PricingRuleRepository(
    backbone_orm::GenericCrudRepository<PricingRule, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for PricingRuleRepository {
    type Target = backbone_orm::GenericCrudRepository<PricingRule, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl PricingRuleRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(PricingRuleRepository, PricingRule, soft_delete);
