//! Repository for PricingRule entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written PricingRule SQL (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<PricingRule, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use rust_decimal::Decimal;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::PricingRule;

/// Table name for PricingRule entities
pub const TABLE_NAME: &str = "promo.pricing_rules";

/// Repository for PricingRule entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct PricingRuleRepository(
    backbone_orm::GenericCrudRepository<PricingRule, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for PricingRuleRepository {
    type Target = backbone_orm::GenericCrudRepository<PricingRule, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl PricingRuleRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The dimensions a line-scope rule search filters on. Mirrors the query's bind list, not an entity.
pub struct LineRuleQuery {
    pub company_id: Uuid,
    pub at: chrono::DateTime<chrono::Utc>,
    pub item_id: Uuid,
    pub item_group_id: Option<Uuid>,
    pub brand_id: Option<Uuid>,
    pub customer_id: Option<Uuid>,
    pub customer_group_id: Option<Uuid>,
    pub quantity: Decimal,
    /// The line's gross (quantity × list_price), matched against the rule's `min_amount` floor.
    pub gross: Decimal,
}

/// A structurally-matching `scope=line` rule, projected exactly as resolution needs it. The enum
/// columns come back as `::text` so the service reads them as plain strings.
pub struct LineRuleRow {
    pub id: Uuid,
    pub priority: i32,
    pub apply_on: String,
    pub customer_id: Option<Uuid>,
    pub customer_group_id: Option<Uuid>,
    pub coupon_required: bool,
    pub rate_or_discount: String,
    pub rate: Option<Decimal>,
    pub discount_percentage: Option<Decimal>,
    pub discount_amount: Option<Decimal>,
    pub valid_from: chrono::DateTime<chrono::Utc>,
}

/// A structurally-matching `scope=order` rule, projected for the cart's order pass.
pub struct OrderRuleRow {
    pub id: Uuid,
    pub priority: i32,
    pub customer_id: Option<Uuid>,
    pub customer_group_id: Option<Uuid>,
    pub coupon_required: bool,
    pub rate_or_discount: String,
    pub discount_percentage: Option<Decimal>,
    pub discount_amount: Option<Decimal>,
    pub stackable: bool,
    pub valid_from: chrono::DateTime<chrono::Utc>,
}

/// Hand-written PricingRule SQL. Lives here (not in the write service) per the module's 4-layer rule:
/// services orchestrate, repositories hold the SQL. These are the STRUCTURAL filters only — the
/// coupon gate, the specificity tie-break and the winner pick stay in the service, where they belong.
impl PricingRuleRepository {
    /// Structural `scope=line` candidates: active, in-window, selector + audience + qty/amount all
    /// match.
    ///
    /// RLS scope (ADR-0008): the query carries its company — the caller wraps this in
    /// `with_company_scope(Some(company_id))` so it is fenced on `app.company_id` even off the request
    /// path. The explicit `company_id = $1` filter stays as defense-in-depth.
    pub async fn find_line_candidates(
        &self,
        pool: &PgPool,
        q: &LineRuleQuery,
    ) -> Result<Vec<LineRuleRow>, sqlx::Error> {
        let rows = company_scope::fetch_all_rows_scoped(
            pool,
            sqlx::query(
                r#"
                SELECT id, priority, apply_on::text AS apply_on, customer_id, customer_group_id,
                       coupon_required, rate_or_discount::text AS rate_or_discount,
                       rate, discount_percentage, discount_amount, valid_from
                FROM promo.pricing_rules
                WHERE company_id = $1
                  AND is_active = true
                  AND scope = 'line'
                  AND (metadata->>'deleted_at') IS NULL
                  AND valid_from <= $2
                  AND (valid_to IS NULL OR valid_to >= $2)
                  AND (
                        apply_on = 'all'
                     OR (apply_on = 'item'       AND item_id = $3)
                     OR (apply_on = 'item_group' AND item_group_id = $4)
                     OR (apply_on = 'brand'      AND brand_id = $5)
                  )
                  AND (customer_id IS NULL OR customer_id = $6)
                  AND (customer_group_id IS NULL OR customer_group_id = $7)
                  AND min_qty <= $8
                  AND (max_qty IS NULL OR max_qty >= $8)
                  AND min_amount <= $9
                "#,
            )
            .bind(q.company_id)
            .bind(q.at)
            .bind(q.item_id)
            .bind(q.item_group_id)
            .bind(q.brand_id)
            .bind(q.customer_id)
            .bind(q.customer_group_id)
            .bind(q.quantity)
            .bind(q.gross),
        )
        .await?;
        Ok(rows
            .into_iter()
            .map(|r| LineRuleRow {
                id: r.get("id"),
                priority: r.get("priority"),
                apply_on: r.get("apply_on"),
                customer_id: r.get("customer_id"),
                customer_group_id: r.get("customer_group_id"),
                coupon_required: r.get("coupon_required"),
                rate_or_discount: r.get("rate_or_discount"),
                rate: r.get("rate"),
                discount_percentage: r.get("discount_percentage"),
                discount_amount: r.get("discount_amount"),
                valid_from: r.get("valid_from"),
            })
            .collect())
    }

    /// Structural `scope=order` candidates: active, in-window, audience matches, and the cart's
    /// subtotal clears the rule's `min_order_amount` floor. Same caller-supplied scope +
    /// defense-in-depth `company_id = $1` as [`Self::find_line_candidates`].
    pub async fn find_order_candidates(
        &self,
        pool: &PgPool,
        company_id: Uuid,
        at: chrono::DateTime<chrono::Utc>,
        customer_id: Option<Uuid>,
        customer_group_id: Option<Uuid>,
        subtotal: Decimal,
    ) -> Result<Vec<OrderRuleRow>, sqlx::Error> {
        let rows = company_scope::fetch_all_rows_scoped(
            pool,
            sqlx::query(
                r#"
                SELECT id, priority, customer_id, customer_group_id, coupon_required,
                       rate_or_discount::text AS rate_or_discount,
                       discount_percentage, discount_amount, stackable, valid_from
                FROM promo.pricing_rules
                WHERE company_id = $1
                  AND is_active = true
                  AND scope = 'order'
                  AND (metadata->>'deleted_at') IS NULL
                  AND valid_from <= $2
                  AND (valid_to IS NULL OR valid_to >= $2)
                  AND (customer_id IS NULL OR customer_id = $3)
                  AND (customer_group_id IS NULL OR customer_group_id = $4)
                  AND min_order_amount <= $5
                "#,
            )
            .bind(company_id)
            .bind(at)
            .bind(customer_id)
            .bind(customer_group_id)
            .bind(subtotal),
        )
        .await?;
        Ok(rows
            .into_iter()
            .map(|r| OrderRuleRow {
                id: r.get("id"),
                priority: r.get("priority"),
                customer_id: r.get("customer_id"),
                customer_group_id: r.get("customer_group_id"),
                coupon_required: r.get("coupon_required"),
                rate_or_discount: r.get("rate_or_discount"),
                discount_percentage: r.get("discount_percentage"),
                discount_amount: r.get("discount_amount"),
                stackable: r.get("stackable"),
                valid_from: r.get("valid_from"),
            })
            .collect())
    }
}

backbone_core::impl_crud_repository!(PricingRuleRepository, PricingRule, soft_delete);
