//! Repository for PromoBundle entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written PromoBundle SQL (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<PromoBundle, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use rust_decimal::Decimal;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::PromoBundle;

/// Table name for PromoBundle entities
pub const TABLE_NAME: &str = "promo.promo_bundles";

/// Repository for PromoBundle entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct PromoBundleRepository(
    backbone_orm::GenericCrudRepository<PromoBundle, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for PromoBundleRepository {
    type Target = backbone_orm::GenericCrudRepository<PromoBundle, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl PromoBundleRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// An active, in-window bundle, projected for the cart's bundle pass. The enum columns come back as
/// `::text` so the service reads them as plain strings.
pub struct BundleRow {
    pub id: Uuid,
    pub priority: i32,
    pub match_type: String,
    pub required_distinct: Option<i32>,
    pub reward: String,
    pub discount_percentage: Option<Decimal>,
    pub discount_amount: Option<Decimal>,
    pub reward_item_id: Option<Uuid>,
    pub reward_qty: Option<Decimal>,
    pub stackable: bool,
    pub valid_from: chrono::DateTime<chrono::Utc>,
}

/// Hand-written PromoBundle SQL. Lives here (not in the write service) per the module's 4-layer rule:
/// services orchestrate, repositories hold the SQL. Whether a bundle is actually SATISFIED by the
/// cart's lines is the service's decision — this is the structural filter only.
impl PromoBundleRepository {
    /// Active, in-window bundles whose `min_order_amount` floor the subtotal clears, ordered
    /// priority DESC → newest → id.
    ///
    /// RLS scope (ADR-0008): company on the cart — the caller wraps this in
    /// `with_company_scope(Some(company_id))`. The explicit `company_id = $1` stays as
    /// defense-in-depth.
    pub async fn find_active(
        &self,
        pool: &PgPool,
        company_id: Uuid,
        at: chrono::DateTime<chrono::Utc>,
        subtotal: Decimal,
    ) -> Result<Vec<BundleRow>, sqlx::Error> {
        let rows = company_scope::fetch_all_rows_scoped(
            pool,
            sqlx::query(
                r#"
                SELECT id, priority, match_type::text AS match_type, required_distinct,
                       reward::text AS reward, discount_percentage, discount_amount,
                       reward_item_id, reward_qty, stackable, valid_from
                FROM promo.promo_bundles
                WHERE company_id = $1
                  AND is_active = true
                  AND (metadata->>'deleted_at') IS NULL
                  AND valid_from <= $2
                  AND (valid_to IS NULL OR valid_to >= $2)
                  AND min_order_amount <= $3
                ORDER BY priority DESC, valid_from DESC, id ASC
                "#,
            )
            .bind(company_id)
            .bind(at)
            .bind(subtotal),
        )
        .await?;
        Ok(rows
            .into_iter()
            .map(|r| BundleRow {
                id: r.get("id"),
                priority: r.get("priority"),
                match_type: r.get("match_type"),
                required_distinct: r.get("required_distinct"),
                reward: r.get("reward"),
                discount_percentage: r.get("discount_percentage"),
                discount_amount: r.get("discount_amount"),
                reward_item_id: r.get("reward_item_id"),
                reward_qty: r.get("reward_qty"),
                stackable: r.get("stackable"),
                valid_from: r.get("valid_from"),
            })
            .collect())
    }
}

backbone_core::impl_crud_repository!(PromoBundleRepository, PromoBundle, soft_delete);
