//! Repository for PromoBundleComponent entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written PromoBundleComponent SQL (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<PromoBundleComponent, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use rust_decimal::Decimal;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::PromoBundleComponent;

/// Table name for PromoBundleComponent entities
pub const TABLE_NAME: &str = "promo.promo_bundle_components";

/// Repository for PromoBundleComponent entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct PromoBundleComponentRepository(
    backbone_orm::GenericCrudRepository<PromoBundleComponent, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for PromoBundleComponentRepository {
    type Target = backbone_orm::GenericCrudRepository<PromoBundleComponent, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl PromoBundleComponentRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// One bundle component: a selector + how much of it a single satisfied set needs. Carries its
/// `bundle_id` so the caller can group a batched read back onto its bundles.
pub struct BundleComponentRow {
    pub bundle_id: Uuid,
    pub apply_on: String,
    pub item_id: Option<Uuid>,
    pub item_group_id: Option<Uuid>,
    pub brand_id: Option<Uuid>,
    pub min_qty: Decimal,
}

/// Hand-written PromoBundleComponent SQL. Lives here (not in the write service) per the module's
/// 4-layer rule: services orchestrate, repositories hold the SQL.
impl PromoBundleComponentRepository {
    /// Every component of the given bundles, in ONE round trip (`bundle_id = ANY($2)`) rather than a
    /// query per bundle.
    ///
    /// RLS scope (ADR-0008): company on the cart — the caller wraps this in
    /// `with_company_scope(Some(company_id))`. The explicit `company_id = $1` stays as
    /// defense-in-depth.
    pub async fn find_for_bundles(
        &self,
        pool: &PgPool,
        company_id: Uuid,
        bundle_ids: &[Uuid],
    ) -> Result<Vec<BundleComponentRow>, sqlx::Error> {
        let rows = company_scope::fetch_all_rows_scoped(
            pool,
            sqlx::query(
                r#"
                SELECT bundle_id, apply_on::text AS apply_on, item_id, item_group_id, brand_id, min_qty
                FROM promo.promo_bundle_components
                WHERE company_id = $1
                  AND bundle_id = ANY($2)
                  AND (metadata->>'deleted_at') IS NULL
                "#,
            )
            .bind(company_id)
            .bind(bundle_ids),
        )
        .await?;
        Ok(rows
            .into_iter()
            .map(|r| BundleComponentRow {
                bundle_id: r.get("bundle_id"),
                apply_on: r.get("apply_on"),
                item_id: r.get("item_id"),
                item_group_id: r.get("item_group_id"),
                brand_id: r.get("brand_id"),
                min_qty: r.get("min_qty"),
            })
            .collect())
    }
}

backbone_core::impl_crud_repository!(PromoBundleComponentRepository, PromoBundleComponent, soft_delete);
