//! Repository for PromoCampaign entities
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<PromoCampaign, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::PromoCampaign;

/// Table name for PromoCampaign entities
pub const TABLE_NAME: &str = "promo_campaigns";

/// Repository for PromoCampaign entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct PromoCampaignRepository(
    backbone_orm::GenericCrudRepository<PromoCampaign, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for PromoCampaignRepository {
    type Target = backbone_orm::GenericCrudRepository<PromoCampaign, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl PromoCampaignRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

impl PromoCampaignRepository {
    /// Find promo_campaign by code (excludes soft-deleted)
    pub async fn find_by_code(&self, code: &str) -> Result<Option<PromoCampaign>> {
        self.find_by_text_field("code", code).await
    }

    /// Check if promo_campaign exists by code (excludes soft-deleted)
    pub async fn exists_by_code(&self, code: &str) -> Result<bool> {
        self.exists_by_text_field("code", code).await
    }

}

backbone_core::impl_crud_repository!(PromoCampaignRepository, PromoCampaign, soft_delete);
