//! Repository for PromoBundleGift entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom method
//! below holds the hand-written PromoBundleGift SQL (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<PromoBundleGift, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use rust_decimal::Decimal;
use sqlx::{PgPool, Row};
use uuid::Uuid;

// The typed multi-row read twins live only in the legacy `company_scope` module. Their
// connection discipline is what this repository needs — request-dedicated connection when
// the composing service bound one, plain pool otherwise. The helper's legacy task-local
// branch is never taken: this module sets no legacy scope of its own (ADR-0029).
use backbone_orm::company_scope::fetch_all_rows_scoped;

use crate::domain::entity::PromoBundleGift;

/// Table name for PromoBundleGift entities
pub const TABLE_NAME: &str = "promo.promo_bundle_gifts";

/// Repository for PromoBundleGift entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct PromoBundleGiftRepository(
    backbone_orm::GenericCrudRepository<PromoBundleGift, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for PromoBundleGiftRepository {
    type Target = backbone_orm::GenericCrudRepository<PromoBundleGift, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl PromoBundleGiftRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// One gift a bundle grants per satisfied set: the free item + how many of it a single set yields.
/// Carries its `bundle_id` so the caller can group a batched read back onto its bundles.
pub struct BundleGiftRow {
    pub bundle_id: Uuid,
    pub gift_item_id: Uuid,
    pub gift_qty: Decimal,
}

/// Hand-written PromoBundleGift SQL. Lives here (not in the write service) per the module's 4-layer
/// rule: services orchestrate, repositories hold the SQL.
impl PromoBundleGiftRepository {
    /// Every gift of the given bundles, in ONE round trip (`bundle_id = ANY($1)`) rather than a query
    /// per bundle.
    ///
    /// Tenant-agnostic (ADR-0029): the module ships no row fence — row scoping is the composing
    /// service's tenancy decorator.
    pub async fn find_for_bundles(
        &self,
        pool: &PgPool,
        bundle_ids: &[Uuid],
    ) -> Result<Vec<BundleGiftRow>, sqlx::Error> {
        let rows = fetch_all_rows_scoped(
            pool,
            sqlx::query(
                r#"
                SELECT bundle_id, gift_item_id, gift_qty
                FROM promo.promo_bundle_gifts
                WHERE bundle_id = ANY($1)
                  AND (metadata->>'deleted_at') IS NULL
                "#,
            )
            .bind(bundle_ids),
        )
        .await?;
        Ok(rows
            .into_iter()
            .map(|r| BundleGiftRow {
                bundle_id: r.get("bundle_id"),
                gift_item_id: r.get("gift_item_id"),
                gift_qty: r.get("gift_qty"),
            })
            .collect())
    }
}

backbone_core::impl_crud_repository!(PromoBundleGiftRepository, PromoBundleGift, soft_delete);
