//! Validator for AdPerformance entity
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<AdPerformance>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, RequiredString, RequiredUuid};
use crate::domain::entity::AdPerformance;

/// Validator type alias for AdPerformance entities.
pub type AdPerformanceValidator = EntityValidator<AdPerformance>;

/// Build a validator for AdPerformance with all schema-defined field rules.
pub fn ad_performance_validator() -> AdPerformanceValidator {
    EntityValidator::new()
        .rule(RequiredUuid::new("advertisement_id", |e: &AdPerformance| &e.advertisement_id))
        .rule(NonNegative::new("impressions", |e: &AdPerformance| e.impressions))
        .rule(NonNegative::new("unique_impressions", |e: &AdPerformance| e.unique_impressions))
        .rule(NonNegative::new("clicks", |e: &AdPerformance| e.clicks))
        .rule(NonNegative::new("unique_clicks", |e: &AdPerformance| e.unique_clicks))
        .rule(NonNegative::new("conversions", |e: &AdPerformance| e.conversions))
        .rule(NonNegative::new("conversion_value", |e: &AdPerformance| e.conversion_value))
        .rule(NonNegative::new("spend", |e: &AdPerformance| e.spend))
        .rule(NonNegative::new("budget_remaining", |e: &AdPerformance| e.budget_remaining))
        .rule(NonNegative::new("cpc", |e: &AdPerformance| e.cpc))
        .rule(NonNegative::new("cpm", |e: &AdPerformance| e.cpm))
        .rule(NonNegative::new("cpa", |e: &AdPerformance| e.cpa))
        .rule(NonNegative::new("shares", |e: &AdPerformance| e.shares))
        .rule(NonNegative::new("saves", |e: &AdPerformance| e.saves))
        .rule(NonNegative::new("avg_view_duration_seconds", |e: &AdPerformance| e.avg_view_duration_seconds))
        .rule(NonNegative::new("reach", |e: &AdPerformance| e.reach))
        .rule(NonNegative::new("frequency", |e: &AdPerformance| e.frequency))
        .rule(RequiredString::new("currency", |e: &AdPerformance| &e.currency))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
