//! Validator for CouponRedemption entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<CouponRedemption>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{RequiredString};
use crate::domain::entity::CouponRedemption;

/// Validator type alias for CouponRedemption entities.
pub type CouponRedemptionValidator = EntityValidator<CouponRedemption>;

/// Build a validator for CouponRedemption with all schema-defined field rules.
pub fn coupon_redemption_validator() -> CouponRedemptionValidator {
    EntityValidator::new()
        .rule(RequiredString::new("source_type", |e: &CouponRedemption| &e.source_type))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
