//! Validator for LoyaltyPointEntry entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<LoyaltyPointEntry>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, RequiredString};
use crate::domain::entity::LoyaltyPointEntry;

/// Validator type alias for LoyaltyPointEntry entities.
pub type LoyaltyPointEntryValidator = EntityValidator<LoyaltyPointEntry>;

/// Build a validator for LoyaltyPointEntry with all schema-defined field rules.
pub fn loyalty_point_entry_validator() -> LoyaltyPointEntryValidator {
    EntityValidator::new()
        .rule(RequiredString::new("source_type", |e: &LoyaltyPointEntry| &e.source_type))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
