//! Validator for LoyaltyProgram entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<LoyaltyProgram>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, RequiredString};
use crate::domain::entity::LoyaltyProgram;

/// Validator type alias for LoyaltyProgram entities.
pub type LoyaltyProgramValidator = EntityValidator<LoyaltyProgram>;

/// Build a validator for LoyaltyProgram with all schema-defined field rules.
pub fn loyalty_program_validator() -> LoyaltyProgramValidator {
    EntityValidator::new()
        .rule(RequiredString::new("program_name", |e: &LoyaltyProgram| &e.program_name))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
