//! Validator for LoyaltyOrderPoints entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<LoyaltyOrderPoints>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, RequiredString};
use crate::domain::entity::LoyaltyOrderPoints;

/// Validator type alias for LoyaltyOrderPoints entities.
pub type LoyaltyOrderPointsValidator = EntityValidator<LoyaltyOrderPoints>;

/// Build a validator for LoyaltyOrderPoints with all schema-defined field rules.
pub fn loyalty_order_points_validator() -> LoyaltyOrderPointsValidator {
    EntityValidator::new()
        .rule(RequiredString::new("order_ref_type", |e: &LoyaltyOrderPoints| &e.order_ref_type))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
