//! Entity validators
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::{ValidationError, ValidationErrors, ValidationResult, EntityValidator};

pub mod coupon_code_validator;
pub mod coupon_redemption_validator;
pub mod loyalty_program_validator;
pub mod loyalty_point_entry_validator;
pub mod pricing_rule_validator;

pub use coupon_code_validator::{CouponCodeValidator, coupon_code_validator};
pub use coupon_redemption_validator::{CouponRedemptionValidator, coupon_redemption_validator};
pub use loyalty_program_validator::{LoyaltyProgramValidator, loyalty_program_validator};
pub use loyalty_point_entry_validator::{LoyaltyPointEntryValidator, loyalty_point_entry_validator};
pub use pricing_rule_validator::{PricingRuleValidator, pricing_rule_validator};

// <<< CUSTOM
// END CUSTOM
