//! Validator for PricingRule entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<PricingRule>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, RequiredString};
use crate::domain::entity::PricingRule;

/// Validator type alias for PricingRule entities.
pub type PricingRuleValidator = EntityValidator<PricingRule>;

/// Build a validator for PricingRule with all schema-defined field rules.
pub fn pricing_rule_validator() -> PricingRuleValidator {
    EntityValidator::new()
        .rule(RequiredString::new("title", |e: &PricingRule| &e.title))
        .rule(NonNegative::new("priority", |e: &PricingRule| e.priority as i64))
        .rule(RequiredString::new("currency", |e: &PricingRule| &e.currency))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
