//! Validator for PromoCampaign entity
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<PromoCampaign>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, OptionalNotBlank, RequiredString};
use crate::domain::entity::PromoCampaign;

/// Validator type alias for PromoCampaign entities.
pub type PromoCampaignValidator = EntityValidator<PromoCampaign>;

/// Build a validator for PromoCampaign with all schema-defined field rules.
pub fn promo_campaign_validator() -> PromoCampaignValidator {
    EntityValidator::new()
        .rule(RequiredString::new("name", |e: &PromoCampaign| &e.name))
        .rule(RequiredString::new("code", |e: &PromoCampaign| &e.code))
        .rule(OptionalNotBlank::new("description", |e: &PromoCampaign| e.description.as_deref()))
        .rule(NonNegative::new("discount_value", |e: &PromoCampaign| e.discount_value))
        .rule(NonNegative::new("max_discount", |e: &PromoCampaign| e.max_discount))
        .rule(NonNegative::new("min_order_value", |e: &PromoCampaign| e.min_order_value))
        .rule(NonNegative::new("total_budget", |e: &PromoCampaign| e.total_budget))
        .rule(NonNegative::new("budget_used", |e: &PromoCampaign| e.budget_used))
        .rule(NonNegative::new("total_redemptions", |e: &PromoCampaign| e.total_redemptions))
        .rule(NonNegative::new("unique_users", |e: &PromoCampaign| e.unique_users))
        .rule(NonNegative::new("total_discount_given", |e: &PromoCampaign| e.total_discount_given))
        .rule(NonNegative::new("total_order_value", |e: &PromoCampaign| e.total_order_value))
        .rule(OptionalNotBlank::new("banner_image_url", |e: &PromoCampaign| e.banner_image_url.as_deref()))
        .rule(OptionalNotBlank::new("terms_and_conditions", |e: &PromoCampaign| e.terms_and_conditions.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
