//! Validator for PromoBundleComponent entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<PromoBundleComponent>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative};
use crate::domain::entity::PromoBundleComponent;

/// Validator type alias for PromoBundleComponent entities.
pub type PromoBundleComponentValidator = EntityValidator<PromoBundleComponent>;

/// Build a validator for PromoBundleComponent with all schema-defined field rules.
pub fn promo_bundle_component_validator() -> PromoBundleComponentValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
        // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
