//! Validator for PromoBundleGift entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<PromoBundleGift>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative};
use crate::domain::entity::PromoBundleGift;

/// Validator type alias for PromoBundleGift entities.
pub type PromoBundleGiftValidator = EntityValidator<PromoBundleGift>;

/// Build a validator for PromoBundleGift with all schema-defined field rules.
pub fn promo_bundle_gift_validator() -> PromoBundleGiftValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
        // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
