//! Validator for PromoBundle entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<PromoBundle>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, RequiredString};
use crate::domain::entity::PromoBundle;

/// Validator type alias for PromoBundle entities.
pub type PromoBundleValidator = EntityValidator<PromoBundle>;

/// Build a validator for PromoBundle with all schema-defined field rules.
pub fn promo_bundle_validator() -> PromoBundleValidator {
    EntityValidator::new()
        .rule(RequiredString::new("title", |e: &PromoBundle| &e.title))
        .rule(NonNegative::new("priority", |e: &PromoBundle| e.priority as i64))
        .rule(RequiredString::new("currency", |e: &PromoBundle| &e.currency))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
