//! Domain Entities
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod coupon_code;
pub mod coupon_redemption;
pub mod loyalty_program;
pub mod loyalty_point_entry;
pub mod pricing_rule;
pub mod promo_bundle;
pub mod promo_bundle_component;
pub mod loyalty_program_type;
pub mod loyalty_entry_type;
pub mod rule_scope;
pub mod apply_on;
pub mod rate_or_discount;
pub mod bundle_match;

// Re-exports
pub use coupon_code::CouponCode;
pub use coupon_code::CouponCodeBuilder;
pub use coupon_code::CouponCodeId;
pub use coupon_redemption::CouponRedemption;
pub use coupon_redemption::CouponRedemptionBuilder;
pub use coupon_redemption::CouponRedemptionId;
pub use loyalty_program::LoyaltyProgram;
pub use loyalty_program::LoyaltyProgramBuilder;
pub use loyalty_program::LoyaltyProgramId;
pub use loyalty_point_entry::LoyaltyPointEntry;
pub use loyalty_point_entry::LoyaltyPointEntryBuilder;
pub use loyalty_point_entry::LoyaltyPointEntryId;
pub use pricing_rule::PricingRule;
pub use pricing_rule::PricingRuleBuilder;
pub use pricing_rule::PricingRuleId;
pub use promo_bundle::PromoBundle;
pub use promo_bundle::PromoBundleBuilder;
pub use promo_bundle::PromoBundleId;
pub use promo_bundle_component::PromoBundleComponent;
pub use promo_bundle_component::PromoBundleComponentBuilder;
pub use promo_bundle_component::PromoBundleComponentId;
pub use loyalty_program_type::LoyaltyProgramType;
pub use loyalty_entry_type::LoyaltyEntryType;
pub use rule_scope::RuleScope;
pub use apply_on::ApplyOn;
pub use rate_or_discount::RateOrDiscount;
pub use bundle_match::BundleMatch;

// ==========================================================================
// Entity Trait
// ==========================================================================

use std::fmt::Debug;

/// Trait for domain entities
///
/// All generated entities implement this trait, providing
/// a common interface for working with domain objects.
pub trait Entity: Debug + Clone {
    /// The type of the entity's unique identifier
    type Id: Debug + Clone + PartialEq;

    /// Get the entity's unique identifier
    fn entity_id(&self) -> &Self::Id;

    /// Get the entity type name
    fn entity_type() -> &'static str;
}

// ==========================================================================
// Audit Metadata
// ==========================================================================

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

/// Audit metadata stored as JSONB in the database
///
/// This struct consolidates audit fields (timestamps and actors) into a single
/// JSONB column for efficient storage and flexible querying.
#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
pub struct AuditMetadata {
    /// Timestamp when the record was created
    #[serde(skip_serializing_if = "Option::is_none")]
    pub created_at: Option<DateTime<Utc>>,

    /// Timestamp when the record was last updated
    #[serde(skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<DateTime<Utc>>,

    /// Timestamp when the record was soft-deleted
    #[serde(skip_serializing_if = "Option::is_none")]
    pub deleted_at: Option<DateTime<Utc>>,

    /// User ID who created the record
    #[serde(skip_serializing_if = "Option::is_none")]
    pub created_by: Option<Uuid>,

    /// User ID who last updated the record
    #[serde(skip_serializing_if = "Option::is_none")]
    pub updated_by: Option<Uuid>,

    /// User ID who deleted the record
    #[serde(skip_serializing_if = "Option::is_none")]
    pub deleted_by: Option<Uuid>,
}

impl AuditMetadata {
    /// Create new audit metadata with created_at set to now
    pub fn new() -> Self {
        Self {
            created_at: Some(Utc::now()),
            ..Default::default()
        }
    }

    /// Create with creator ID
    pub fn with_creator(creator_id: Uuid) -> Self {
        Self {
            created_at: Some(Utc::now()),
            created_by: Some(creator_id),
            ..Default::default()
        }
    }

    /// Touch the record (update updated_at)
    pub fn touch(&mut self) {
        self.updated_at = Some(Utc::now());
    }

    /// Touch with updater ID
    pub fn touch_by(&mut self, updater_id: Uuid) {
        self.updated_at = Some(Utc::now());
        self.updated_by = Some(updater_id);
    }

    /// Soft delete the record
    pub fn soft_delete(&mut self) {
        self.deleted_at = Some(Utc::now());
    }

    /// Soft delete with deleter ID
    pub fn soft_delete_by(&mut self, deleter_id: Uuid) {
        self.deleted_at = Some(Utc::now());
        self.deleted_by = Some(deleter_id);
    }

    /// Restore a soft-deleted record
    pub fn restore(&mut self) {
        self.deleted_at = None;
        self.deleted_by = None;
    }

    /// Check if record is deleted
    pub fn is_deleted(&self) -> bool {
        self.deleted_at.is_some()
    }

    /// Check if record is active (not deleted)
    pub fn is_active(&self) -> bool {
        self.deleted_at.is_none()
    }
}
