//! Auth configuration for AdPerformance handlers
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<AdPerformance>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::AdPerformanceService;
use crate::domain::entity::AdPerformance;

/// Permission string constants for AdPerformance operations.
pub mod permissions {
    pub const LIST:        &str = "ad_performance:list";
    pub const READ:        &str = "ad_performance:read";
    pub const CREATE:      &str = "ad_performance:create";
    pub const UPDATE:      &str = "ad_performance:update";
    pub const DELETE:      &str = "ad_performance:delete";
    pub const RESTORE:     &str = "ad_performance:restore";
    pub const TRASH:       &str = "ad_performance:trash";
    pub const EMPTY_TRASH: &str = "ad_performance:empty_trash";
    pub const BULK_CREATE: &str = "ad_performance:bulk_create";
    pub const UPSERT:      &str = "ad_performance:upsert";
}

/// Resource policy for AdPerformance — maps CRUD actions to permission strings.
pub struct AdPerformancePolicy;

#[async_trait]
impl ResourcePolicy<AdPerformance> for AdPerformancePolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &AdPerformance,
        ctx: &backbone_auth::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read   => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update => permissions::UPDATE,
            ResourceAction::Delete => permissions::DELETE,
        };
        ctx.has_permission(required)
    }
}

/// Permission guard for AdPerformance handlers.
///
/// Wraps `AdPerformanceService` and checks `AdPerformancePolicy` before delegating.
pub type AdPerformanceGuard = PermissionGuard<AdPerformance, AdPerformanceService, AdPerformancePolicy>;

/// Service-integrated permission guard for AdPerformance (for use in generated handlers).
pub type AdPerformanceServiceGuard = ServicePermissionGuard<AdPerformance, AdPerformanceService, AdPerformancePolicy>;

// <<< CUSTOM
// END CUSTOM
