//! Auth configuration for CouponCode handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<CouponCode>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::CouponCodeService;
use crate::domain::entity::CouponCode;

/// Permission string constants for CouponCode operations.
pub mod permissions {
    pub const LIST:        &str = "coupon_code:list";
    pub const READ:        &str = "coupon_code:read";
    pub const CREATE:      &str = "coupon_code:create";
    pub const UPDATE:      &str = "coupon_code:update";
    pub const DELETE:      &str = "coupon_code:delete";
    pub const RESTORE:     &str = "coupon_code:restore";
    pub const TRASH:       &str = "coupon_code:trash";
    pub const EMPTY_TRASH: &str = "coupon_code:empty_trash";
    pub const BULK_CREATE: &str = "coupon_code:bulk_create";
    pub const UPSERT:      &str = "coupon_code:upsert";
}

/// Resource policy for CouponCode — maps CRUD actions to permission strings.
pub struct CouponCodePolicy;

#[async_trait]
impl ResourcePolicy<CouponCode> for CouponCodePolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &CouponCode,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for CouponCode handlers.
///
/// Wraps `CouponCodeService` and checks `CouponCodePolicy` before delegating.
pub type CouponCodeGuard = PermissionGuard<CouponCode>;

/// Service-integrated permission guard for CouponCode (for use in generated handlers).
pub type CouponCodeServiceGuard = ServicePermissionGuard<CouponCode, CouponCodeService, CouponCodePolicy>;

// <<< CUSTOM
// END CUSTOM
