//! Auth configuration for LoyaltyPointEntry handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<LoyaltyPointEntry>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::LoyaltyPointEntryService;
use crate::domain::entity::LoyaltyPointEntry;

/// Permission string constants for LoyaltyPointEntry operations.
pub mod permissions {
    pub const LIST:        &str = "loyalty_point_entry:list";
    pub const READ:        &str = "loyalty_point_entry:read";
    pub const CREATE:      &str = "loyalty_point_entry:create";
    pub const UPDATE:      &str = "loyalty_point_entry:update";
    pub const DELETE:      &str = "loyalty_point_entry:delete";
    pub const RESTORE:     &str = "loyalty_point_entry:restore";
    pub const TRASH:       &str = "loyalty_point_entry:trash";
    pub const EMPTY_TRASH: &str = "loyalty_point_entry:empty_trash";
    pub const BULK_CREATE: &str = "loyalty_point_entry:bulk_create";
    pub const UPSERT:      &str = "loyalty_point_entry:upsert";
}

/// Resource policy for LoyaltyPointEntry — maps CRUD actions to permission strings.
pub struct LoyaltyPointEntryPolicy;

#[async_trait]
impl ResourcePolicy<LoyaltyPointEntry> for LoyaltyPointEntryPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &LoyaltyPointEntry,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for LoyaltyPointEntry handlers.
///
/// Wraps `LoyaltyPointEntryService` and checks `LoyaltyPointEntryPolicy` before delegating.
pub type LoyaltyPointEntryGuard = PermissionGuard<LoyaltyPointEntry>;

/// Service-integrated permission guard for LoyaltyPointEntry (for use in generated handlers).
pub type LoyaltyPointEntryServiceGuard = ServicePermissionGuard<LoyaltyPointEntry, LoyaltyPointEntryService, LoyaltyPointEntryPolicy>;

// <<< CUSTOM
// END CUSTOM
