//! Auth configuration for PricingRule handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<PricingRule>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::PricingRuleService;
use crate::domain::entity::PricingRule;

/// Permission string constants for PricingRule operations.
pub mod permissions {
    pub const LIST:        &str = "pricing_rule:list";
    pub const READ:        &str = "pricing_rule:read";
    pub const CREATE:      &str = "pricing_rule:create";
    pub const UPDATE:      &str = "pricing_rule:update";
    pub const DELETE:      &str = "pricing_rule:delete";
    pub const RESTORE:     &str = "pricing_rule:restore";
    pub const TRASH:       &str = "pricing_rule:trash";
    pub const EMPTY_TRASH: &str = "pricing_rule:empty_trash";
    pub const BULK_CREATE: &str = "pricing_rule:bulk_create";
    pub const UPSERT:      &str = "pricing_rule:upsert";
}

/// Resource policy for PricingRule — maps CRUD actions to permission strings.
pub struct PricingRulePolicy;

#[async_trait]
impl ResourcePolicy<PricingRule> for PricingRulePolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &PricingRule,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for PricingRule handlers.
///
/// Wraps `PricingRuleService` and checks `PricingRulePolicy` before delegating.
pub type PricingRuleGuard = PermissionGuard<PricingRule>;

/// Service-integrated permission guard for PricingRule (for use in generated handlers).
pub type PricingRuleServiceGuard = ServicePermissionGuard<PricingRule, PricingRuleService, PricingRulePolicy>;

// <<< CUSTOM
// END CUSTOM
