//! Auth configuration for PromoBundleGift handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<PromoBundleGift>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::PromoBundleGiftService;
use crate::domain::entity::PromoBundleGift;

/// Permission string constants for PromoBundleGift operations.
pub mod permissions {
    pub const LIST:        &str = "promo_bundle_gift:list";
    pub const READ:        &str = "promo_bundle_gift:read";
    pub const CREATE:      &str = "promo_bundle_gift:create";
    pub const UPDATE:      &str = "promo_bundle_gift:update";
    pub const DELETE:      &str = "promo_bundle_gift:delete";
    pub const RESTORE:     &str = "promo_bundle_gift:restore";
    pub const TRASH:       &str = "promo_bundle_gift:trash";
    pub const EMPTY_TRASH: &str = "promo_bundle_gift:empty_trash";
    pub const BULK_CREATE: &str = "promo_bundle_gift:bulk_create";
    pub const UPSERT:      &str = "promo_bundle_gift:upsert";
}

/// Resource policy for PromoBundleGift — maps CRUD actions to permission strings.
pub struct PromoBundleGiftPolicy;

#[async_trait]
impl ResourcePolicy<PromoBundleGift> for PromoBundleGiftPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &PromoBundleGift,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for PromoBundleGift handlers.
///
/// Wraps `PromoBundleGiftService` and checks `PromoBundleGiftPolicy` before delegating.
pub type PromoBundleGiftGuard = PermissionGuard<PromoBundleGift>;

/// Service-integrated permission guard for PromoBundleGift (for use in generated handlers).
pub type PromoBundleGiftServiceGuard = ServicePermissionGuard<PromoBundleGift, PromoBundleGiftService, PromoBundleGiftPolicy>;

// <<< CUSTOM
// END CUSTOM
