//! Auth configuration for PromoBundle handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<PromoBundle>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::PromoBundleService;
use crate::domain::entity::PromoBundle;

/// Permission string constants for PromoBundle operations.
pub mod permissions {
    pub const LIST:        &str = "promo_bundle:list";
    pub const READ:        &str = "promo_bundle:read";
    pub const CREATE:      &str = "promo_bundle:create";
    pub const UPDATE:      &str = "promo_bundle:update";
    pub const DELETE:      &str = "promo_bundle:delete";
    pub const RESTORE:     &str = "promo_bundle:restore";
    pub const TRASH:       &str = "promo_bundle:trash";
    pub const EMPTY_TRASH: &str = "promo_bundle:empty_trash";
    pub const BULK_CREATE: &str = "promo_bundle:bulk_create";
    pub const UPSERT:      &str = "promo_bundle:upsert";
}

/// Resource policy for PromoBundle — maps CRUD actions to permission strings.
pub struct PromoBundlePolicy;

#[async_trait]
impl ResourcePolicy<PromoBundle> for PromoBundlePolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &PromoBundle,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for PromoBundle handlers.
///
/// Wraps `PromoBundleService` and checks `PromoBundlePolicy` before delegating.
pub type PromoBundleGuard = PermissionGuard<PromoBundle>;

/// Service-integrated permission guard for PromoBundle (for use in generated handlers).
pub type PromoBundleServiceGuard = ServicePermissionGuard<PromoBundle, PromoBundleService, PromoBundlePolicy>;

// <<< CUSTOM
// END CUSTOM
