//! Auth configuration for PromoCampaign handlers
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<PromoCampaign>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::PromoCampaignService;
use crate::domain::entity::PromoCampaign;

/// Permission string constants for PromoCampaign operations.
pub mod permissions {
    pub const LIST:        &str = "promo_campaign:list";
    pub const READ:        &str = "promo_campaign:read";
    pub const CREATE:      &str = "promo_campaign:create";
    pub const UPDATE:      &str = "promo_campaign:update";
    pub const DELETE:      &str = "promo_campaign:delete";
    pub const RESTORE:     &str = "promo_campaign:restore";
    pub const TRASH:       &str = "promo_campaign:trash";
    pub const EMPTY_TRASH: &str = "promo_campaign:empty_trash";
    pub const BULK_CREATE: &str = "promo_campaign:bulk_create";
    pub const UPSERT:      &str = "promo_campaign:upsert";
}

/// Resource policy for PromoCampaign — maps CRUD actions to permission strings.
pub struct PromoCampaignPolicy;

#[async_trait]
impl ResourcePolicy<PromoCampaign> for PromoCampaignPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &PromoCampaign,
        ctx: &backbone_auth::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read   => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update => permissions::UPDATE,
            ResourceAction::Delete => permissions::DELETE,
        };
        ctx.has_permission(required)
    }
}

/// Permission guard for PromoCampaign handlers.
///
/// Wraps `PromoCampaignService` and checks `PromoCampaignPolicy` before delegating.
pub type PromoCampaignGuard = PermissionGuard<PromoCampaign, PromoCampaignService, PromoCampaignPolicy>;

/// Service-integrated permission guard for PromoCampaign (for use in generated handlers).
pub type PromoCampaignServiceGuard = ServicePermissionGuard<PromoCampaign, PromoCampaignService, PromoCampaignPolicy>;

// <<< CUSTOM
// END CUSTOM
