//! Auth configuration for ProviderPromo handlers
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<ProviderPromo>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::ProviderPromoService;
use crate::domain::entity::ProviderPromo;

/// Permission string constants for ProviderPromo operations.
pub mod permissions {
    pub const LIST:        &str = "provider_promo:list";
    pub const READ:        &str = "provider_promo:read";
    pub const CREATE:      &str = "provider_promo:create";
    pub const UPDATE:      &str = "provider_promo:update";
    pub const DELETE:      &str = "provider_promo:delete";
    pub const RESTORE:     &str = "provider_promo:restore";
    pub const TRASH:       &str = "provider_promo:trash";
    pub const EMPTY_TRASH: &str = "provider_promo:empty_trash";
    pub const BULK_CREATE: &str = "provider_promo:bulk_create";
    pub const UPSERT:      &str = "provider_promo:upsert";
}

/// Resource policy for ProviderPromo — maps CRUD actions to permission strings.
pub struct ProviderPromoPolicy;

#[async_trait]
impl ResourcePolicy<ProviderPromo> for ProviderPromoPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &ProviderPromo,
        ctx: &backbone_auth::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read   => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update => permissions::UPDATE,
            ResourceAction::Delete => permissions::DELETE,
        };
        ctx.has_permission(required)
    }
}

/// Permission guard for ProviderPromo handlers.
///
/// Wraps `ProviderPromoService` and checks `ProviderPromoPolicy` before delegating.
pub type ProviderPromoGuard = PermissionGuard<ProviderPromo, ProviderPromoService, ProviderPromoPolicy>;

/// Service-integrated permission guard for ProviderPromo (for use in generated handlers).
pub type ProviderPromoServiceGuard = ServicePermissionGuard<ProviderPromo, ProviderPromoService, ProviderPromoPolicy>;

// <<< CUSTOM
// END CUSTOM
