//! Advertisement API Integration Tests
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Tests the Advertisement CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::helpers::CommonUtils;

// ============================================================================
// ADVERTISEMENT TEST DATA GENERATOR
// ============================================================================

/// Test data generator for Advertisement
pub struct AdvertisementTestData;

impl TestDataGenerator for AdvertisementTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "ad_number": null,
            "provider_id": null,
            "placement": null,
            "position": null,
            "headline": null,
            "description": "Test description",
            "image_url": null,
            "image_url_mobile": null,
            "click_url": null,
            "action_type": null,
            "action_reference": null,
            "target_zones": null,
            "target_services": null,
            "target_audience": null,
            "status": null,
            "start_at": now,
            "end_at": now,
            "currency": null,
            "billing_model": null,
            "bid_amount": null,
            "daily_budget": null,
            "total_budget": null,
            "budget_spent": null,
            "max_impressions": null,
            "max_clicks": null,
            "frequency_cap": null,
            "total_impressions": null,
            "total_clicks": null,
            "total_conversions": null,
            "conversion_value": null,
            "click_through_rate": null,
            "conversion_rate": null,
            "approved_at": now,
            "approved_by": null,
            "rejection_reason": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "ad_number": null,
            "provider_id": null,
            "placement": null,
            "position": null,
            "headline": null,
            "description": "Test description",
            "image_url": null,
            "image_url_mobile": null,
            "click_url": null,
            "action_type": null,
            "action_reference": null,
            "target_zones": null,
            "target_services": null,
            "target_audience": null,
            "status": null,
            "start_at": now,
            "end_at": now,
            "currency": null,
            "billing_model": null,
            "bid_amount": null,
            "daily_budget": null,
            "total_budget": null,
            "budget_spent": null,
            "max_impressions": null,
            "max_clicks": null,
            "frequency_cap": null,
            "total_impressions": null,
            "total_clicks": null,
            "total_conversions": null,
            "conversion_value": null,
            "click_through_rate": null,
            "conversion_rate": null,
            "approved_at": now,
            "approved_by": null,
            "rejection_reason": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// ADVERTISEMENT API TEST
// ============================================================================

/// Advertisement API test suite
pub struct AdvertisementApiTest {
    inner: GenericCrudTest<AdvertisementTestData>,
}

impl AdvertisementApiTest {
    pub fn new() -> Self {
        let config = CrudTestConfig::new("/api/v1/advertisements", "Advertisement");
        Self {
            inner: GenericCrudTest::new(config, AdvertisementTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for AdvertisementApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_advertisement_crud() {
        let mut test = AdvertisementApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add Advertisement specific tests here
// <<< CUSTOM TESTS END >>>
