//! CouponRedemption API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the CouponRedemption CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// COUPONREDEMPTION TEST DATA GENERATOR
// ============================================================================

/// Test data generator for CouponRedemption
pub struct CouponRedemptionTestData;

impl TestDataGenerator for CouponRedemptionTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "coupon_id": Uuid::new_v4().to_string(),
            "pricing_rule_id": Uuid::new_v4().to_string(),
            "source_type": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "source_id": Uuid::new_v4().to_string(),
            "redeemed_at": now,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "coupon_id": Uuid::new_v4().to_string(),
            "pricing_rule_id": Uuid::new_v4().to_string(),
            "source_type": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "source_id": Uuid::new_v4().to_string(),
            "redeemed_at": now,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/coupon_codes", &super::coupon_code_api_test::CouponCodeTestData).await {
            deps.push(("coupon_id".to_string(), id));
        }
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/pricing_rules", &super::pricing_rule_api_test::PricingRuleTestData).await {
            deps.push(("pricing_rule_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// COUPONREDEMPTION API TEST
// ============================================================================

/// CouponRedemption API test suite
pub struct CouponRedemptionApiTest {
    inner: GenericCrudTest<CouponRedemptionTestData>,
}

impl CouponRedemptionApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/coupon_redemptions", "CouponRedemption");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, CouponRedemptionTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for CouponRedemptionApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_coupon_redemption_crud() {
        let mut test = CouponRedemptionApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add CouponRedemption specific tests here
// <<< CUSTOM TESTS END >>>
