//! CouponCode API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the CouponCode CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// COUPONCODE TEST DATA GENERATOR
// ============================================================================

/// Test data generator for CouponCode
pub struct CouponCodeTestData;

impl TestDataGenerator for CouponCodeTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "code": format!("TEST_{}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "pricing_rule_id": Uuid::new_v4().to_string(),
            "description": null,
            "max_use": null,
            "used_count": 1,
            "valid_from": now,
            "valid_upto": null,
            "is_active": false,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "code": format!("TEST_{}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "pricing_rule_id": Uuid::new_v4().to_string(),
            "description": null,
            "max_use": null,
            "used_count": 1,
            "valid_from": now,
            "valid_upto": null,
            "is_active": false,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/pricing_rules", &super::pricing_rule_api_test::PricingRuleTestData).await {
            deps.push(("pricing_rule_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// COUPONCODE API TEST
// ============================================================================

/// CouponCode API test suite
pub struct CouponCodeApiTest {
    inner: GenericCrudTest<CouponCodeTestData>,
}

impl CouponCodeApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/coupon_codes", "CouponCode");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, CouponCodeTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for CouponCodeApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_coupon_code_crud() {
        let mut test = CouponCodeApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add CouponCode specific tests here
// <<< CUSTOM TESTS END >>>
