//! Integration Test Implementations
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Contains CRUD API tests for all entities.

pub mod crud_test_base;

pub mod ad_performance_api_test;
pub mod advertisement_api_test;
pub mod provider_promo_api_test;
pub mod promo_campaign_api_test;

// Re-exports for convenience
pub use crud_test_base::*;
pub use ad_performance_api_test::*;
pub use advertisement_api_test::*;
pub use provider_promo_api_test::*;
pub use promo_campaign_api_test::*;
