//! PricingRule API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the PricingRule CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// PRICINGRULE TEST DATA GENERATOR
// ============================================================================

/// Test data generator for PricingRule
pub struct PricingRuleTestData;

impl TestDataGenerator for PricingRuleTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "title": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "priority": 1,
            "scope": "line",
            "min_order_amount": 0,
            "stackable": false,
            "apply_on": "item",
            "item_id": null,
            "item_group_id": null,
            "brand_id": null,
            "customer_id": null,
            "customer_group_id": null,
            "min_qty": 0,
            "max_qty": null,
            "min_amount": 0,
            "rate_or_discount": "rate",
            "rate": null,
            "discount_percentage": null,
            "discount_amount": null,
            "currency": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "valid_from": now,
            "valid_to": null,
            "coupon_required": false,
            "is_active": false,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "title": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "priority": 1,
            "scope": "line",
            "min_order_amount": 0,
            "stackable": false,
            "apply_on": "item",
            "item_id": null,
            "item_group_id": null,
            "brand_id": null,
            "customer_id": null,
            "customer_group_id": null,
            "min_qty": 0,
            "max_qty": null,
            "min_amount": 0,
            "rate_or_discount": "rate",
            "rate": null,
            "discount_percentage": null,
            "discount_amount": null,
            "currency": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "valid_from": now,
            "valid_to": null,
            "coupon_required": false,
            "is_active": false,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// PRICINGRULE API TEST
// ============================================================================

/// PricingRule API test suite
pub struct PricingRuleApiTest {
    inner: GenericCrudTest<PricingRuleTestData>,
}

impl PricingRuleApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/pricing_rules", "PricingRule");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, PricingRuleTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for PricingRuleApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_pricing_rule_crud() {
        let mut test = PricingRuleApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add PricingRule specific tests here
// <<< CUSTOM TESTS END >>>
