//! PromoBundle API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the PromoBundle CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// PROMOBUNDLE TEST DATA GENERATOR
// ============================================================================

/// Test data generator for PromoBundle
pub struct PromoBundleTestData;

impl TestDataGenerator for PromoBundleTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "title": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "priority": 1,
            "match_type": "all_of",
            "required_distinct": null,
            "reward": "rate",
            "discount_percentage": null,
            "discount_amount": null,
            "reward_item_id": null,
            "reward_qty": null,
            "currency": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "min_order_amount": 0,
            "stackable": false,
            "valid_from": now,
            "valid_to": null,
            "is_active": false,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "title": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "priority": 1,
            "match_type": "all_of",
            "required_distinct": null,
            "reward": "rate",
            "discount_percentage": null,
            "discount_amount": null,
            "reward_item_id": null,
            "reward_qty": null,
            "currency": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "min_order_amount": 0,
            "stackable": false,
            "valid_from": now,
            "valid_to": null,
            "is_active": false,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// PROMOBUNDLE API TEST
// ============================================================================

/// PromoBundle API test suite
pub struct PromoBundleApiTest {
    inner: GenericCrudTest<PromoBundleTestData>,
}

impl PromoBundleApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/promo_bundles", "PromoBundle");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, PromoBundleTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for PromoBundleApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_promo_bundle_crud() {
        let mut test = PromoBundleApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add PromoBundle specific tests here
// <<< CUSTOM TESTS END >>>
