//! PromoCampaign API Integration Tests
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Tests the PromoCampaign CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::helpers::CommonUtils;

// ============================================================================
// PROMOCAMPAIGN TEST DATA GENERATOR
// ============================================================================

/// Test data generator for PromoCampaign
pub struct PromoCampaignTestData;

impl TestDataGenerator for PromoCampaignTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "code": format!("TEST_{}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "description": "Test description",
            "promo_type": null,
            "discount_value": null,
            "max_discount": null,
            "min_order_value": null,
            "min_items": null,
            "applicable_services": null,
            "applicable_providers": null,
            "applicable_zones": null,
            "target_audience": null,
            "target_user_ids": null,
            "first_order_only": null,
            "status": null,
            "start_at": now,
            "end_at": now,
            "total_budget": null,
            "budget_used": null,
            "max_redemptions": null,
            "max_per_user": null,
            "total_redemptions": null,
            "unique_users": null,
            "total_discount_given": null,
            "total_order_value": null,
            "funded_by": null,
            "platform_share": null,
            "display_on_app": null,
            "banner_image_url": null,
            "terms_and_conditions": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "code": format!("TEST_{}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "description": "Test description",
            "promo_type": null,
            "discount_value": null,
            "max_discount": null,
            "min_order_value": null,
            "min_items": null,
            "applicable_services": null,
            "applicable_providers": null,
            "applicable_zones": null,
            "target_audience": null,
            "target_user_ids": null,
            "first_order_only": null,
            "status": null,
            "start_at": now,
            "end_at": now,
            "total_budget": null,
            "budget_used": null,
            "max_redemptions": null,
            "max_per_user": null,
            "total_redemptions": null,
            "unique_users": null,
            "total_discount_given": null,
            "total_order_value": null,
            "funded_by": null,
            "platform_share": null,
            "display_on_app": null,
            "banner_image_url": null,
            "terms_and_conditions": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// PROMOCAMPAIGN API TEST
// ============================================================================

/// PromoCampaign API test suite
pub struct PromoCampaignApiTest {
    inner: GenericCrudTest<PromoCampaignTestData>,
}

impl PromoCampaignApiTest {
    pub fn new() -> Self {
        let config = CrudTestConfig::new("/api/v1/promo_campaigns", "PromoCampaign");
        Self {
            inner: GenericCrudTest::new(config, PromoCampaignTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for PromoCampaignApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_promo_campaign_crud() {
        let mut test = PromoCampaignApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add PromoCampaign specific tests here
// <<< CUSTOM TESTS END >>>
