//! Promo Module Handlers
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! This module provides:
//! - AppState dependency injection container
//! - Custom handler integration points

use std::sync::Arc;

// Import all services
use crate::application::service::AdPerformanceService;
use crate::application::service::AdvertisementService;
use crate::application::service::ProviderPromoService;
use crate::application::service::PromoCampaignService;

/// Application state for dependency injection.
///
/// This struct holds references to all module services
/// and is passed to HTTP handlers via Axum's State extractor.
///
/// # Example
///
/// ```ignore
/// use axum::extract::State;
///
/// async fn custom_handler(
///     State(state): State<AppState>,
/// ) -> impl IntoResponse {
///     // Access services via state
/// }
/// ```
#[derive(Clone)]
pub struct AppState {
    /// AdPerformance service
    pub ad_performance_service: Arc<AdPerformanceService>,
    /// Advertisement service
    pub advertisement_service: Arc<AdvertisementService>,
    /// ProviderPromo service
    pub provider_promo_service: Arc<ProviderPromoService>,
    /// PromoCampaign service
    pub promo_campaign_service: Arc<PromoCampaignService>,
}

impl AppState {
    /// Create a new AppState with all services.
    pub fn new(
        ad_performance_service: Arc<AdPerformanceService>,
        advertisement_service: Arc<AdvertisementService>,
        provider_promo_service: Arc<ProviderPromoService>,
        promo_campaign_service: Arc<PromoCampaignService>
    ) -> Self {
        Self {
            ad_performance_service,
            advertisement_service,
            provider_promo_service,
            promo_campaign_service,
        }
    }

    /// Create AppState from module instance.
    pub fn from_module(module: &crate::PromoModule) -> Self {
        Self {
            ad_performance_service: module.ad_performance_service.clone(),
            advertisement_service: module.advertisement_service.clone(),
            provider_promo_service: module.provider_promo_service.clone(),
            promo_campaign_service: module.promo_campaign_service.clone(),
        }
    }
}

/// Builder for AppState.
///
/// Allows incremental construction of AppState.
#[derive(Default)]
pub struct AppStateBuilder {
    ad_performance_service: Option<Arc<AdPerformanceService>>,
    advertisement_service: Option<Arc<AdvertisementService>>,
    provider_promo_service: Option<Arc<ProviderPromoService>>,
    promo_campaign_service: Option<Arc<PromoCampaignService>>,
}

impl AppStateBuilder {
    /// Create a new builder.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the AdPerformance service.
    pub fn with_ad_performance_service(mut self, service: Arc<AdPerformanceService>) -> Self {
        self.ad_performance_service = Some(service);
        self
    }

    /// Set the Advertisement service.
    pub fn with_advertisement_service(mut self, service: Arc<AdvertisementService>) -> Self {
        self.advertisement_service = Some(service);
        self
    }

    /// Set the ProviderPromo service.
    pub fn with_provider_promo_service(mut self, service: Arc<ProviderPromoService>) -> Self {
        self.provider_promo_service = Some(service);
        self
    }

    /// Set the PromoCampaign service.
    pub fn with_promo_campaign_service(mut self, service: Arc<PromoCampaignService>) -> Self {
        self.promo_campaign_service = Some(service);
        self
    }

    /// Build the AppState.
    ///
    /// # Panics
    ///
    /// Panics if any required service is not set.
    pub fn build(self) -> AppState {
        AppState {
            ad_performance_service: self.ad_performance_service.expect("ad_performance_service is required"),
            advertisement_service: self.advertisement_service.expect("advertisement_service is required"),
            provider_promo_service: self.provider_promo_service.expect("provider_promo_service is required"),
            promo_campaign_service: self.promo_campaign_service.expect("promo_campaign_service is required"),
        }
    }
}
