//! Promo Module Handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides:
//! - AppState dependency injection container
//! - Custom handler integration points

use std::sync::Arc;

// Import all services
use crate::application::service::CouponCodeService;
use crate::application::service::CouponRedemptionService;
use crate::application::service::LoyaltyProgramService;
use crate::application::service::LoyaltyPointEntryService;
use crate::application::service::PricingRuleService;

/// Application state for dependency injection.
///
/// This struct holds references to all module services
/// and is passed to HTTP handlers via Axum's State extractor.
///
/// # Example
///
/// ```ignore
/// use axum::extract::State;
///
/// async fn custom_handler(
///     State(state): State<AppState>,
/// ) -> impl IntoResponse {
///     // Access services via state
/// }
/// ```
#[derive(Clone)]
pub struct AppState {
    /// CouponCode service
    pub coupon_code_service: Arc<CouponCodeService>,
    /// CouponRedemption service
    pub coupon_redemption_service: Arc<CouponRedemptionService>,
    /// LoyaltyProgram service
    pub loyalty_program_service: Arc<LoyaltyProgramService>,
    /// LoyaltyPointEntry service
    pub loyalty_point_entry_service: Arc<LoyaltyPointEntryService>,
    /// PricingRule service
    pub pricing_rule_service: Arc<PricingRuleService>,
}

impl AppState {
    /// Create a new AppState with all services.
    pub fn new(
        coupon_code_service: Arc<CouponCodeService>,
        coupon_redemption_service: Arc<CouponRedemptionService>,
        loyalty_program_service: Arc<LoyaltyProgramService>,
        loyalty_point_entry_service: Arc<LoyaltyPointEntryService>,
        pricing_rule_service: Arc<PricingRuleService>
    ) -> Self {
        Self {
            coupon_code_service,
            coupon_redemption_service,
            loyalty_program_service,
            loyalty_point_entry_service,
            pricing_rule_service,
        }
    }

    /// Create AppState from module instance.
    pub fn from_module(module: &crate::PromoModule) -> Self {
        Self {
            coupon_code_service: module.coupon_code_service.clone(),
            coupon_redemption_service: module.coupon_redemption_service.clone(),
            loyalty_program_service: module.loyalty_program_service.clone(),
            loyalty_point_entry_service: module.loyalty_point_entry_service.clone(),
            pricing_rule_service: module.pricing_rule_service.clone(),
        }
    }
}

/// Builder for AppState.
///
/// Allows incremental construction of AppState.
#[derive(Default)]
pub struct AppStateBuilder {
    coupon_code_service: Option<Arc<CouponCodeService>>,
    coupon_redemption_service: Option<Arc<CouponRedemptionService>>,
    loyalty_program_service: Option<Arc<LoyaltyProgramService>>,
    loyalty_point_entry_service: Option<Arc<LoyaltyPointEntryService>>,
    pricing_rule_service: Option<Arc<PricingRuleService>>,
}

impl AppStateBuilder {
    /// Create a new builder.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the CouponCode service.
    pub fn with_coupon_code_service(mut self, service: Arc<CouponCodeService>) -> Self {
        self.coupon_code_service = Some(service);
        self
    }

    /// Set the CouponRedemption service.
    pub fn with_coupon_redemption_service(mut self, service: Arc<CouponRedemptionService>) -> Self {
        self.coupon_redemption_service = Some(service);
        self
    }

    /// Set the LoyaltyProgram service.
    pub fn with_loyalty_program_service(mut self, service: Arc<LoyaltyProgramService>) -> Self {
        self.loyalty_program_service = Some(service);
        self
    }

    /// Set the LoyaltyPointEntry service.
    pub fn with_loyalty_point_entry_service(mut self, service: Arc<LoyaltyPointEntryService>) -> Self {
        self.loyalty_point_entry_service = Some(service);
        self
    }

    /// Set the PricingRule service.
    pub fn with_pricing_rule_service(mut self, service: Arc<PricingRuleService>) -> Self {
        self.pricing_rule_service = Some(service);
        self
    }

    /// Build the AppState.
    ///
    /// # Panics
    ///
    /// Panics if any required service is not set.
    pub fn build(self) -> AppState {
        AppState {
            coupon_code_service: self.coupon_code_service.expect("coupon_code_service is required"),
            coupon_redemption_service: self.coupon_redemption_service.expect("coupon_redemption_service is required"),
            loyalty_program_service: self.loyalty_program_service.expect("loyalty_program_service is required"),
            loyalty_point_entry_service: self.loyalty_point_entry_service.expect("loyalty_point_entry_service is required"),
            pricing_rule_service: self.pricing_rule_service.expect("pricing_rule_service is required"),
        }
    }
}
