//! Public API exports for Promo module
//!
//! This module defines the public API that other modules can depend on.
//! It includes type-safe IDs, DTOs, and public events.
//!
//! Generated by backbone-schema. Custom code sections are preserved.

// Exports will be generated here by backbone-schema
// Use: backbone schema generate promo --target export
