//! HTTP route configuration
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides consolidated Axum route configuration using backbone-core's
//! BackboneCrudHandler for all 12 standard Backbone CRUD endpoints per entity.

use axum::Router;
use std::sync::Arc;

use super::{
    coupon_code_handler::create_coupon_code_routes,
    coupon_redemption_handler::create_coupon_redemption_routes,
    loyalty_program_handler::create_loyalty_program_routes,
    loyalty_point_entry_handler::create_loyalty_point_entry_routes,
    pricing_rule_handler::create_pricing_rule_routes,
    promo_bundle_handler::create_promo_bundle_routes,
    promo_bundle_component_handler::create_promo_bundle_component_routes,
};

use crate::application::service::{
    CouponCodeService,
    CouponRedemptionService,
    LoyaltyProgramService,
    LoyaltyPointEntryService,
    PricingRuleService,
    PromoBundleService,
    PromoBundleComponentService,
};

/// Services collection for all CRUD endpoints
pub struct HttpServices {
    pub coupon_code: Arc<CouponCodeService>,
    pub coupon_redemption: Arc<CouponRedemptionService>,
    pub loyalty_program: Arc<LoyaltyProgramService>,
    pub loyalty_point_entry: Arc<LoyaltyPointEntryService>,
    pub pricing_rule: Arc<PricingRuleService>,
    pub promo_bundle: Arc<PromoBundleService>,
    pub promo_bundle_component: Arc<PromoBundleComponentService>,
}

/// Configure all HTTP routes for this module using Axum and BackboneCrudHandler.
///
/// Each entity gets 12 standard Backbone CRUD endpoints:
/// 1. GET /api/v1/{collection} - List with pagination
/// 2. POST /api/v1/{collection} - Create
/// 3. GET /api/v1/{collection}/:id - Get by ID
/// 4. PUT /api/v1/{collection}/:id - Full update
/// 5. PATCH /api/v1/{collection}/:id - Partial update
/// 6. DELETE /api/v1/{collection}/:id - Soft delete
/// 7. POST /api/v1/{collection}/bulk - Bulk create
/// 8. POST /api/v1/{collection}/upsert - Upsert
/// 9. GET /api/v1/{collection}/trash - List deleted
/// 10. POST /api/v1/{collection}/:id/restore - Restore
/// 11. DELETE /api/v1/{collection}/empty - Empty trash
/// 12. GET /api/v1/{collection}/:id/deleted - Get deleted by ID
pub fn configure_routes(services: HttpServices) -> Router {
    Router::new()
        // CouponCode routes (12 Backbone endpoints)
        .merge(create_coupon_code_routes(services.coupon_code))
        // CouponRedemption routes (12 Backbone endpoints)
        .merge(create_coupon_redemption_routes(services.coupon_redemption))
        // LoyaltyProgram routes (12 Backbone endpoints)
        .merge(create_loyalty_program_routes(services.loyalty_program))
        // LoyaltyPointEntry routes (12 Backbone endpoints)
        .merge(create_loyalty_point_entry_routes(services.loyalty_point_entry))
        // PricingRule routes (12 Backbone endpoints)
        .merge(create_pricing_rule_routes(services.pricing_rule))
        // PromoBundle routes (12 Backbone endpoints)
        .merge(create_promo_bundle_routes(services.promo_bundle))
        // PromoBundleComponent routes (12 Backbone endpoints)
        .merge(create_promo_bundle_component_routes(services.promo_bundle_component))
}

/// Create an individual entity's routes (for modular configuration)
pub mod individual {
    use super::*;

    pub fn coupon_code_routes(service: Arc<CouponCodeService>) -> Router {
        create_coupon_code_routes(service)
    }

    pub fn coupon_redemption_routes(service: Arc<CouponRedemptionService>) -> Router {
        create_coupon_redemption_routes(service)
    }

    pub fn loyalty_program_routes(service: Arc<LoyaltyProgramService>) -> Router {
        create_loyalty_program_routes(service)
    }

    pub fn loyalty_point_entry_routes(service: Arc<LoyaltyPointEntryService>) -> Router {
        create_loyalty_point_entry_routes(service)
    }

    pub fn pricing_rule_routes(service: Arc<PricingRuleService>) -> Router {
        create_pricing_rule_routes(service)
    }

    pub fn promo_bundle_routes(service: Arc<PromoBundleService>) -> Router {
        create_promo_bundle_routes(service)
    }

    pub fn promo_bundle_component_routes(service: Arc<PromoBundleComponentService>) -> Router {
        create_promo_bundle_component_routes(service)
    }

}
