//! Public events for Promo module
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! These events are published by this module for other modules to subscribe to.
//! Events are the primary mechanism for cross-module communication.

use serde::{Deserialize, Serialize};
use chrono::{DateTime, Utc};

use super::types::*;

// ============================================================================
// ADPERFORMANCE EVENTS
// ============================================================================

/// Event published when a AdPerformance is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AdPerformanceCreatedEvent {
    pub id: AdPerformanceId,
    pub data: AdPerformanceDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a AdPerformance is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AdPerformanceUpdatedEvent {
    pub id: AdPerformanceId,
    pub data: AdPerformanceDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a AdPerformance is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AdPerformanceDeletedEvent {
    pub id: AdPerformanceId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// ADVERTISEMENT EVENTS
// ============================================================================

/// Event published when a Advertisement is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AdvertisementCreatedEvent {
    pub id: AdvertisementId,
    pub data: AdvertisementDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Advertisement is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AdvertisementUpdatedEvent {
    pub id: AdvertisementId,
    pub data: AdvertisementDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Advertisement is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AdvertisementDeletedEvent {
    pub id: AdvertisementId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// PROVIDERPROMO EVENTS
// ============================================================================

/// Event published when a ProviderPromo is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProviderPromoCreatedEvent {
    pub id: ProviderPromoId,
    pub data: ProviderPromoDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ProviderPromo is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProviderPromoUpdatedEvent {
    pub id: ProviderPromoId,
    pub data: ProviderPromoDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ProviderPromo is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProviderPromoDeletedEvent {
    pub id: ProviderPromoId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// PROMOCAMPAIGN EVENTS
// ============================================================================

/// Event published when a PromoCampaign is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PromoCampaignCreatedEvent {
    pub id: PromoCampaignId,
    pub data: PromoCampaignDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a PromoCampaign is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PromoCampaignUpdatedEvent {
    pub id: PromoCampaignId,
    pub data: PromoCampaignDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a PromoCampaign is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PromoCampaignDeletedEvent {
    pub id: PromoCampaignId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// MODULE EVENT ENUM
// ============================================================================

/// All events published by Promo module
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum PromoEvent {
    AdPerformanceCreated(AdPerformanceCreatedEvent),
    AdPerformanceUpdated(AdPerformanceUpdatedEvent),
    AdPerformanceDeleted(AdPerformanceDeletedEvent),
    AdvertisementCreated(AdvertisementCreatedEvent),
    AdvertisementUpdated(AdvertisementUpdatedEvent),
    AdvertisementDeleted(AdvertisementDeletedEvent),
    ProviderPromoCreated(ProviderPromoCreatedEvent),
    ProviderPromoUpdated(ProviderPromoUpdatedEvent),
    ProviderPromoDeleted(ProviderPromoDeletedEvent),
    PromoCampaignCreated(PromoCampaignCreatedEvent),
    PromoCampaignUpdated(PromoCampaignUpdatedEvent),
    PromoCampaignDeleted(PromoCampaignDeletedEvent),
}

/// Metadata for module events
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PromoEventMetadata {
    pub module: &'static str,
    pub version: &'static str,
}

impl Default for PromoEventMetadata {
    fn default() -> Self {
        Self {
            module: "promo",
            version: "1.0",
        }
    }
}

// ============================================================================
// CUSTOM EVENTS
// ============================================================================

// <<< CUSTOM EVENTS START >>>
// Add custom public events here
// <<< CUSTOM EVENTS END >>>
