//! Public events for Promo module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These events are published by this module for other modules to subscribe to.
//! Events are the primary mechanism for cross-module communication.

use serde::{Deserialize, Serialize};
use chrono::{DateTime, Utc};

use super::types::*;

// ============================================================================
// COUPONCODE EVENTS
// ============================================================================

/// Event published when a CouponCode is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CouponCodeCreatedEvent {
    pub id: CouponCodeId,
    pub data: CouponCodeDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a CouponCode is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CouponCodeUpdatedEvent {
    pub id: CouponCodeId,
    pub data: CouponCodeDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a CouponCode is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CouponCodeDeletedEvent {
    pub id: CouponCodeId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// COUPONREDEMPTION EVENTS
// ============================================================================

/// Event published when a CouponRedemption is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CouponRedemptionCreatedEvent {
    pub id: CouponRedemptionId,
    pub data: CouponRedemptionDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a CouponRedemption is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CouponRedemptionUpdatedEvent {
    pub id: CouponRedemptionId,
    pub data: CouponRedemptionDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a CouponRedemption is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CouponRedemptionDeletedEvent {
    pub id: CouponRedemptionId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// LOYALTYPROGRAM EVENTS
// ============================================================================

/// Event published when a LoyaltyProgram is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LoyaltyProgramCreatedEvent {
    pub id: LoyaltyProgramId,
    pub data: LoyaltyProgramDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a LoyaltyProgram is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LoyaltyProgramUpdatedEvent {
    pub id: LoyaltyProgramId,
    pub data: LoyaltyProgramDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a LoyaltyProgram is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LoyaltyProgramDeletedEvent {
    pub id: LoyaltyProgramId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// LOYALTYPOINTENTRY EVENTS
// ============================================================================

/// Event published when a LoyaltyPointEntry is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LoyaltyPointEntryCreatedEvent {
    pub id: LoyaltyPointEntryId,
    pub data: LoyaltyPointEntryDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a LoyaltyPointEntry is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LoyaltyPointEntryUpdatedEvent {
    pub id: LoyaltyPointEntryId,
    pub data: LoyaltyPointEntryDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a LoyaltyPointEntry is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LoyaltyPointEntryDeletedEvent {
    pub id: LoyaltyPointEntryId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// PRICINGRULE EVENTS
// ============================================================================

/// Event published when a PricingRule is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PricingRuleCreatedEvent {
    pub id: PricingRuleId,
    pub data: PricingRuleDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a PricingRule is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PricingRuleUpdatedEvent {
    pub id: PricingRuleId,
    pub data: PricingRuleDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a PricingRule is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PricingRuleDeletedEvent {
    pub id: PricingRuleId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// MODULE EVENT ENUM
// ============================================================================

/// All events published by Promo module
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum PromoEvent {
    CouponCodeCreated(CouponCodeCreatedEvent),
    CouponCodeUpdated(CouponCodeUpdatedEvent),
    CouponCodeDeleted(CouponCodeDeletedEvent),
    CouponRedemptionCreated(CouponRedemptionCreatedEvent),
    CouponRedemptionUpdated(CouponRedemptionUpdatedEvent),
    CouponRedemptionDeleted(CouponRedemptionDeletedEvent),
    LoyaltyProgramCreated(LoyaltyProgramCreatedEvent),
    LoyaltyProgramUpdated(LoyaltyProgramUpdatedEvent),
    LoyaltyProgramDeleted(LoyaltyProgramDeletedEvent),
    LoyaltyPointEntryCreated(LoyaltyPointEntryCreatedEvent),
    LoyaltyPointEntryUpdated(LoyaltyPointEntryUpdatedEvent),
    LoyaltyPointEntryDeleted(LoyaltyPointEntryDeletedEvent),
    PricingRuleCreated(PricingRuleCreatedEvent),
    PricingRuleUpdated(PricingRuleUpdatedEvent),
    PricingRuleDeleted(PricingRuleDeletedEvent),
}

/// Metadata for module events
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PromoEventMetadata {
    pub module: &'static str,
    pub version: &'static str,
}

impl Default for PromoEventMetadata {
    fn default() -> Self {
        Self {
            module: "promo",
            version: "1.0",
        }
    }
}

// ============================================================================
// CUSTOM EVENTS
// ============================================================================

// <<< CUSTOM EVENTS START >>>
// Add custom public events here
// <<< CUSTOM EVENTS END >>>
