//! Promo Module Exports
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module defines the public API that Promo exposes to other modules.
//! Other modules should ONLY depend on types defined here, not internal types.
//!
//! ## Usage from other modules
//!
//! ```text
//! use promo::exports::{CouponCodeDto, PromoQueryService};
//! ```

mod types;
mod services;
mod events;

// Re-export all public types
pub use types::*;
pub use services::*;
pub use events::*;

// ============================================================================
// EXPORT SUMMARY
// ============================================================================

/// Summary of what this module exports
///
/// ## Public Types
/// - `CouponCodeDto` - Data transfer object for CouponCode
/// - `CouponCodeSummary` - Summary view of CouponCode
/// - `CouponCodeId` - Type-safe ID wrapper
/// - `CouponRedemptionDto` - Data transfer object for CouponRedemption
/// - `CouponRedemptionSummary` - Summary view of CouponRedemption
/// - `CouponRedemptionId` - Type-safe ID wrapper
/// - `LoyaltyProgramDto` - Data transfer object for LoyaltyProgram
/// - `LoyaltyProgramSummary` - Summary view of LoyaltyProgram
/// - `LoyaltyProgramId` - Type-safe ID wrapper
/// - `LoyaltyPointEntryDto` - Data transfer object for LoyaltyPointEntry
/// - `LoyaltyPointEntrySummary` - Summary view of LoyaltyPointEntry
/// - `LoyaltyPointEntryId` - Type-safe ID wrapper
/// - `PricingRuleDto` - Data transfer object for PricingRule
/// - `PricingRuleSummary` - Summary view of PricingRule
/// - `PricingRuleId` - Type-safe ID wrapper
///
/// ## Public Services
/// - `PromoQueryService` - Read-only queries
///
/// ## Public Events
/// - `CouponCodeCreatedEvent` - Published when CouponCode is created
/// - `CouponCodeUpdatedEvent` - Published when CouponCode is updated
/// - `CouponCodeDeletedEvent` - Published when CouponCode is deleted
/// - `CouponRedemptionCreatedEvent` - Published when CouponRedemption is created
/// - `CouponRedemptionUpdatedEvent` - Published when CouponRedemption is updated
/// - `CouponRedemptionDeletedEvent` - Published when CouponRedemption is deleted
/// - `LoyaltyProgramCreatedEvent` - Published when LoyaltyProgram is created
/// - `LoyaltyProgramUpdatedEvent` - Published when LoyaltyProgram is updated
/// - `LoyaltyProgramDeletedEvent` - Published when LoyaltyProgram is deleted
/// - `LoyaltyPointEntryCreatedEvent` - Published when LoyaltyPointEntry is created
/// - `LoyaltyPointEntryUpdatedEvent` - Published when LoyaltyPointEntry is updated
/// - `LoyaltyPointEntryDeletedEvent` - Published when LoyaltyPointEntry is deleted
/// - `PricingRuleCreatedEvent` - Published when PricingRule is created
/// - `PricingRuleUpdatedEvent` - Published when PricingRule is updated
/// - `PricingRuleDeletedEvent` - Published when PricingRule is deleted
pub struct ExportSummary;
