//! Public types for Promo module
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! These DTOs are the ONLY types other modules should use.
//! They are decoupled from internal domain entities.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

// ============================================================================
// ADPERFORMANCE TYPES
// ============================================================================

/// Type-safe ID for AdPerformance
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct AdPerformanceId(pub Uuid);

impl AdPerformanceId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for AdPerformanceId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<AdPerformanceId> for Uuid {
    fn from(id: AdPerformanceId) -> Self {
        id.0
    }
}

/// Data transfer object for AdPerformance
///
/// This is the public representation of AdPerformance for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AdPerformanceDto {
    pub id: AdPerformanceId,
    pub advertisement_id: Uuid,
    pub provider_id: Option<Uuid>,
    pub date: NaiveDate,
    pub hour: Option<i32>,
    pub ad_type: AdType,
    pub placement: AdPlacement,
    pub status: AdStatus,
    pub impressions: i32,
    pub unique_impressions: i32,
    pub clicks: i32,
    pub unique_clicks: i32,
    pub ctr: Option<Decimal>,
    pub conversions: i32,
    pub conversion_rate: Option<Decimal>,
    pub conversion_value: Decimal,
    pub spend: Decimal,
    pub budget_remaining: Option<Decimal>,
    pub cpc: Option<Decimal>,
    pub cpm: Option<Decimal>,
    pub cpa: Option<Decimal>,
    pub roi: Option<Decimal>,
    pub roas: Option<Decimal>,
    pub shares: i32,
    pub saves: i32,
    pub engagement_rate: Option<Decimal>,
    pub avg_view_duration_seconds: Option<i32>,
    pub reach: i32,
    pub frequency: Option<Decimal>,
    pub audience_demographics: serde_json::Value,
    pub by_device: serde_json::Value,
    pub by_platform: serde_json::Value,
    pub by_region: serde_json::Value,
    pub quality_score: Option<Decimal>,
    pub relevance_score: Option<Decimal>,
    pub currency: String,
    pub metadata: serde_json::Value,
}

/// Summary view of AdPerformance for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AdPerformanceSummary {
    pub id: AdPerformanceId,
    pub status: AdStatus,
}

/// Reference to AdPerformance for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AdPerformanceRef {
    pub id: AdPerformanceId,
}

// ============================================================================
// ADVERTISEMENT TYPES
// ============================================================================

/// Type-safe ID for Advertisement
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct AdvertisementId(pub Uuid);

impl AdvertisementId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for AdvertisementId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<AdvertisementId> for Uuid {
    fn from(id: AdvertisementId) -> Self {
        id.0
    }
}

/// Data transfer object for Advertisement
///
/// This is the public representation of Advertisement for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AdvertisementDto {
    pub id: AdvertisementId,
    pub name: String,
    pub ad_number: String,
    pub provider_id: Uuid,
    pub placement: AdPlacement,
    pub position: Option<i32>,
    pub headline: Option<String>,
    pub description: Option<String>,
    pub image_url: String,
    pub image_url_mobile: Option<String>,
    pub click_url: Option<String>,
    pub action_type: Option<String>,
    pub action_reference: Option<String>,
    pub target_zones: serde_json::Value,
    pub target_services: serde_json::Value,
    pub target_audience: String,
    pub status: AdStatus,
    pub start_at: DateTime<Utc>,
    pub end_at: DateTime<Utc>,
    pub currency: String,
    pub billing_model: AdBillingModel,
    pub bid_amount: Decimal,
    pub daily_budget: Option<Decimal>,
    pub total_budget: Option<Decimal>,
    pub budget_spent: Decimal,
    pub max_impressions: Option<i32>,
    pub max_clicks: Option<i32>,
    pub frequency_cap: Option<i32>,
    pub total_impressions: i32,
    pub total_clicks: i32,
    pub total_conversions: i32,
    pub conversion_value: Decimal,
    pub click_through_rate: Option<Decimal>,
    pub conversion_rate: Option<Decimal>,
    pub approved_at: Option<DateTime<Utc>>,
    pub approved_by: Option<Uuid>,
    pub rejection_reason: Option<String>,
    pub metadata: serde_json::Value,
}

/// Summary view of Advertisement for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AdvertisementSummary {
    pub id: AdvertisementId,
    pub name: String,
    pub status: AdStatus,
}

/// Reference to Advertisement for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AdvertisementRef {
    pub id: AdvertisementId,
}

// ============================================================================
// PROVIDERPROMO TYPES
// ============================================================================

/// Type-safe ID for ProviderPromo
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct ProviderPromoId(pub Uuid);

impl ProviderPromoId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for ProviderPromoId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<ProviderPromoId> for Uuid {
    fn from(id: ProviderPromoId) -> Self {
        id.0
    }
}

/// Data transfer object for ProviderPromo
///
/// This is the public representation of ProviderPromo for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProviderPromoDto {
    pub id: ProviderPromoId,
    pub provider_id: Uuid,
    pub outlet_id: Option<Uuid>,
    pub promo_name: String,
    pub promo_code: Option<String>,
    pub description: Option<String>,
    pub promo_type: PromoType,
    pub discount_value: Decimal,
    pub max_discount: Option<Decimal>,
    pub currency: String,
    pub min_order_amount: Option<Decimal>,
    pub min_weight_kg: Option<Decimal>,
    pub applicable_services: serde_json::Value,
    pub applicable_categories: serde_json::Value,
    pub valid_from: DateTime<Utc>,
    pub valid_until: DateTime<Utc>,
    pub usage_limit: Option<i32>,
    pub usage_limit_per_customer: Option<i32>,
    pub usage_count: i32,
    pub eligible_customers: PromoEligibility,
    pub eligible_tiers: serde_json::Value,
    pub is_active: bool,
    pub is_public: bool,
    pub is_stackable: bool,
    pub banner_url: Option<String>,
    pub terms_conditions: Option<String>,
    pub metadata: serde_json::Value,
}

/// Summary view of ProviderPromo for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProviderPromoSummary {
    pub id: ProviderPromoId,
    pub promo_name: String,
}

/// Reference to ProviderPromo for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProviderPromoRef {
    pub id: ProviderPromoId,
}

// ============================================================================
// PROMOCAMPAIGN TYPES
// ============================================================================

/// Type-safe ID for PromoCampaign
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct PromoCampaignId(pub Uuid);

impl PromoCampaignId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for PromoCampaignId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<PromoCampaignId> for Uuid {
    fn from(id: PromoCampaignId) -> Self {
        id.0
    }
}

/// Data transfer object for PromoCampaign
///
/// This is the public representation of PromoCampaign for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PromoCampaignDto {
    pub id: PromoCampaignId,
    pub name: String,
    pub code: String,
    pub description: Option<String>,
    pub promo_type: CampaignPromoType,
    pub discount_value: Decimal,
    pub max_discount: Option<Decimal>,
    pub min_order_value: Option<Decimal>,
    pub min_items: Option<i32>,
    pub applicable_services: serde_json::Value,
    pub applicable_providers: serde_json::Value,
    pub applicable_zones: serde_json::Value,
    pub target_audience: CampaignTarget,
    pub target_user_ids: serde_json::Value,
    pub first_order_only: bool,
    pub status: CampaignStatus,
    pub start_at: DateTime<Utc>,
    pub end_at: DateTime<Utc>,
    pub total_budget: Option<Decimal>,
    pub budget_used: Decimal,
    pub max_redemptions: Option<i32>,
    pub max_per_user: i32,
    pub total_redemptions: i32,
    pub unique_users: i32,
    pub total_discount_given: Decimal,
    pub total_order_value: Decimal,
    pub funded_by: CampaignFunder,
    pub platform_share: Decimal,
    pub display_on_app: bool,
    pub banner_image_url: Option<String>,
    pub terms_and_conditions: Option<String>,
    pub metadata: serde_json::Value,
}

/// Summary view of PromoCampaign for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PromoCampaignSummary {
    pub id: PromoCampaignId,
    pub name: String,
    pub status: CampaignStatus,
}

/// Reference to PromoCampaign for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PromoCampaignRef {
    pub id: PromoCampaignId,
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

// <<< CUSTOM TYPES START >>>
// Add custom public types here
// <<< CUSTOM TYPES END >>>
