//! Use case type aliases for Advertisement aggregate
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateAdvertisementDto, UpdateAdvertisementDto};
use crate::application::service::AdvertisementService;
use crate::domain::entity::Advertisement;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateAdvertisementUseCase = CreateUseCase<Advertisement, CreateAdvertisementDto, AdvertisementService>;
pub type UpdateAdvertisementUseCase = UpdateUseCase<Advertisement, UpdateAdvertisementDto, AdvertisementService>;
pub type GetAdvertisementUseCase    = GetUseCase<Advertisement, AdvertisementService>;
pub type DeleteAdvertisementUseCase = DeleteUseCase<Advertisement, AdvertisementService>;
pub type ListAdvertisementUseCase   = ListUseCase<Advertisement, AdvertisementService>;

// <<< CUSTOM
// END CUSTOM
