//! Use case type aliases for CouponRedemption aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateCouponRedemptionDto, UpdateCouponRedemptionDto};
use crate::application::service::CouponRedemptionService;
use crate::domain::entity::CouponRedemption;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateCouponRedemptionUseCase = CreateUseCase<CouponRedemption, CreateCouponRedemptionDto, CouponRedemptionService>;
pub type UpdateCouponRedemptionUseCase = UpdateUseCase<CouponRedemption, UpdateCouponRedemptionDto, CouponRedemptionService>;
pub type GetCouponRedemptionUseCase    = GetUseCase<CouponRedemption, CouponRedemptionService>;
pub type DeleteCouponRedemptionUseCase = DeleteUseCase<CouponRedemption, CouponRedemptionService>;
pub type ListCouponRedemptionUseCase   = ListUseCase<CouponRedemption, CouponRedemptionService>;

// <<< CUSTOM
// END CUSTOM
