//! Use case type aliases for LoyaltyProgram aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateLoyaltyProgramDto, UpdateLoyaltyProgramDto};
use crate::application::service::LoyaltyProgramService;
use crate::domain::entity::LoyaltyProgram;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateLoyaltyProgramUseCase = CreateUseCase<LoyaltyProgram, CreateLoyaltyProgramDto, LoyaltyProgramService>;
pub type UpdateLoyaltyProgramUseCase = UpdateUseCase<LoyaltyProgram, UpdateLoyaltyProgramDto, LoyaltyProgramService>;
pub type GetLoyaltyProgramUseCase    = GetUseCase<LoyaltyProgram, LoyaltyProgramService>;
pub type DeleteLoyaltyProgramUseCase = DeleteUseCase<LoyaltyProgram, LoyaltyProgramService>;
pub type ListLoyaltyProgramUseCase   = ListUseCase<LoyaltyProgram, LoyaltyProgramService>;

// <<< CUSTOM
// END CUSTOM
