//! Application use cases
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Each entity contributes 5 type aliases (create, update, get, delete, list).

pub mod base;
pub use base::{UseCaseError, UseCaseResult, UseCaseHooks};

pub mod ad_performance_usecases;
pub mod advertisement_usecases;
pub mod provider_promo_usecases;
pub mod promo_campaign_usecases;

pub use ad_performance_usecases::{
    CreateAdPerformanceUseCase, UpdateAdPerformanceUseCase, GetAdPerformanceUseCase,
    DeleteAdPerformanceUseCase, ListAdPerformanceUseCase,
};
pub use advertisement_usecases::{
    CreateAdvertisementUseCase, UpdateAdvertisementUseCase, GetAdvertisementUseCase,
    DeleteAdvertisementUseCase, ListAdvertisementUseCase,
};
pub use provider_promo_usecases::{
    CreateProviderPromoUseCase, UpdateProviderPromoUseCase, GetProviderPromoUseCase,
    DeleteProviderPromoUseCase, ListProviderPromoUseCase,
};
pub use promo_campaign_usecases::{
    CreatePromoCampaignUseCase, UpdatePromoCampaignUseCase, GetPromoCampaignUseCase,
    DeletePromoCampaignUseCase, ListPromoCampaignUseCase,
};

// <<< CUSTOM
// END CUSTOM
