//! Application use cases
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity contributes 5 type aliases (create, update, get, delete, list).

pub mod base;
pub use base::{UseCaseError, UseCaseResult, UseCaseHooks};

pub mod coupon_code_usecases;
pub mod coupon_redemption_usecases;
pub mod loyalty_program_usecases;
pub mod loyalty_point_entry_usecases;
pub mod pricing_rule_usecases;

pub use coupon_code_usecases::{
    CreateCouponCodeUseCase, UpdateCouponCodeUseCase, GetCouponCodeUseCase,
    DeleteCouponCodeUseCase, ListCouponCodeUseCase,
};
pub use coupon_redemption_usecases::{
    CreateCouponRedemptionUseCase, UpdateCouponRedemptionUseCase, GetCouponRedemptionUseCase,
    DeleteCouponRedemptionUseCase, ListCouponRedemptionUseCase,
};
pub use loyalty_program_usecases::{
    CreateLoyaltyProgramUseCase, UpdateLoyaltyProgramUseCase, GetLoyaltyProgramUseCase,
    DeleteLoyaltyProgramUseCase, ListLoyaltyProgramUseCase,
};
pub use loyalty_point_entry_usecases::{
    CreateLoyaltyPointEntryUseCase, UpdateLoyaltyPointEntryUseCase, GetLoyaltyPointEntryUseCase,
    DeleteLoyaltyPointEntryUseCase, ListLoyaltyPointEntryUseCase,
};
pub use pricing_rule_usecases::{
    CreatePricingRuleUseCase, UpdatePricingRuleUseCase, GetPricingRuleUseCase,
    DeletePricingRuleUseCase, ListPricingRuleUseCase,
};

// <<< CUSTOM
// END CUSTOM
