//! Use case type aliases for PromoBundleGift aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreatePromoBundleGiftDto, UpdatePromoBundleGiftDto};
use crate::application::service::PromoBundleGiftService;
use crate::domain::entity::PromoBundleGift;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreatePromoBundleGiftUseCase = CreateUseCase<PromoBundleGift, CreatePromoBundleGiftDto, PromoBundleGiftService>;
pub type UpdatePromoBundleGiftUseCase = UpdateUseCase<PromoBundleGift, UpdatePromoBundleGiftDto, PromoBundleGiftService>;
pub type GetPromoBundleGiftUseCase    = GetUseCase<PromoBundleGift, PromoBundleGiftService>;
pub type DeletePromoBundleGiftUseCase = DeleteUseCase<PromoBundleGift, PromoBundleGiftService>;
pub type ListPromoBundleGiftUseCase   = ListUseCase<PromoBundleGift, PromoBundleGiftService>;

// <<< CUSTOM
// END CUSTOM
