//! Use case type aliases for PromoBundleComponent aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreatePromoBundleComponentDto, UpdatePromoBundleComponentDto};
use crate::application::service::PromoBundleComponentService;
use crate::domain::entity::PromoBundleComponent;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreatePromoBundleComponentUseCase = CreateUseCase<PromoBundleComponent, CreatePromoBundleComponentDto, PromoBundleComponentService>;
pub type UpdatePromoBundleComponentUseCase = UpdateUseCase<PromoBundleComponent, UpdatePromoBundleComponentDto, PromoBundleComponentService>;
pub type GetPromoBundleComponentUseCase    = GetUseCase<PromoBundleComponent, PromoBundleComponentService>;
pub type DeletePromoBundleComponentUseCase = DeleteUseCase<PromoBundleComponent, PromoBundleComponentService>;
pub type ListPromoBundleComponentUseCase   = ListUseCase<PromoBundleComponent, PromoBundleComponentService>;

// <<< CUSTOM
// END CUSTOM
