//! Use case type aliases for ProviderPromo aggregate
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateProviderPromoDto, UpdateProviderPromoDto};
use crate::application::service::ProviderPromoService;
use crate::domain::entity::ProviderPromo;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateProviderPromoUseCase = CreateUseCase<ProviderPromo, CreateProviderPromoDto, ProviderPromoService>;
pub type UpdateProviderPromoUseCase = UpdateUseCase<ProviderPromo, UpdateProviderPromoDto, ProviderPromoService>;
pub type GetProviderPromoUseCase    = GetUseCase<ProviderPromo, ProviderPromoService>;
pub type DeleteProviderPromoUseCase = DeleteUseCase<ProviderPromo, ProviderPromoService>;
pub type ListProviderPromoUseCase   = ListUseCase<ProviderPromo, ProviderPromoService>;

// <<< CUSTOM
// END CUSTOM
