//! HTTP handlers
//!
//! Auto-generated by backbone-schema. Do not edit manually.
//!
//! These handlers use Axum and backbone-core's BackboneCrudHandler
//! to provide all 12 standard Backbone CRUD endpoints.

pub mod ad_performance_handler;
pub mod advertisement_handler;
pub mod provider_promo_handler;
pub mod promo_campaign_handler;

// <<< CUSTOM
// END CUSTOM

// Re-exports
pub use ad_performance_handler::create_ad_performance_routes;
pub use advertisement_handler::create_advertisement_routes;
pub use provider_promo_handler::create_provider_promo_routes;
pub use promo_campaign_handler::create_promo_campaign_routes;
// <<< CUSTOM
// END CUSTOM
